### ISSUE TITLE
Grouped Device Deployments

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#1509]
### Description

First requested here: https://github.com/flowforge/flowforge/issues/1323

Capturing this in an Epic for planning purposes and to discuss high-level complexities and possible solutions/approaches on how best to tackle it.

### Customer Problem:
A single instance of Node-RED can contain multiple tabs, and flows. These flows may communicate with each other, but equally, they can be completely standalone.

Currently, we enable the capturing of a Snapshot of the full instance, that can then be deployed out to remote devices via the FlowForge Device Agent. Any instances with multiple tabs are fully captured in a snapshot, so all tabs are deployed to a Device.

Also, it is currently only possible to set a single "Target Snapshot" for devices attached to a project, so all devices will run that single snapshot.

### Requirements

- It has been requested that we enable "tagging" of a device, so that it is possible to deploy a particular tab to a set of devices.
- In addition to the tagging, we are also looking at the ability to group/tag devices for the purposes of Staged Deployments (see https://github.com/flowforge/flowforge/issues/1492).

### Proposal
Work here breaks into two parts:

1) Grouping of devices within a single Project to control which target snapshot is deployed to which device. (see https://github.com/flowforge/flowforge/issues/1492 where we define that some devices belong to different "stages" of deployment)
2) The ability to snapshot/deploy just a single tab of a Project, rather than the full `flow.json` - Raised as a separate epic: https://github.com/flowforge/flowforge/issues/1694

```[tasklist]
### Tasks
- [ ] https://github.com/flowforge/flowforge/issues/2340
- [ ] https://github.com/flowforge/flowforge/issues/2655
```

**Comment by knolleary** [comment]
Want to be a little careful here as I think there are two different epics here:

 - Grouping Devices
 - Tab-level Snapshots

They both feed into a bigger picture but there's no inherent cross-dependency between them as concepts. I'm wary of lumping them together, so I'm going to pull 'Tab-level Snapshots' out as its own Epic.

**Comment by MarianRaphael** [comment]
See also: https://github.com/flowforge/flowforge-device-agent/issues/79
