### ISSUE TITLE
Teams dropdown list is not scrollable

### ISSUE THREAD

**Issue by Pezmc** [FlowFuse/flowfuse#1532]
### Current Behavior

A user with a large amount of teams or a small screen, currently can't view teams at the bottom of the list

<img width="325" alt="Screenshot 2023-01-11 at 11 22 22" src="https://user-images.githubusercontent.com/507155/211781757-a6dcc7e8-3bc6-466a-b49f-1dff75df7fc8.png">

### Expected Behavior

Should be able to view the teams at the bottom of the list

### Steps To Reproduce

Add a large amount of teams or have a small browser window

### Environment

- FlowForge version: 1.3
- Node.js version: n/a
- npm version: n/a
- Platform/OS: macOS
- Browser: Chrome/Safari

**Comment by sumitshinde-84** [comment]
I am Working on it
