### ISSUE TITLE
Identify current issues with Node-RED dashboard

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/flowfuse#1648]
### Epic

#1647

### Description

Before FlowForge can make a large investment into Node-RED Dashboard, it should be clearly understood what issues or features would improve on the status quo.

This issue is the place to capture input from the Node-RED community on what individual wishes and requirements are.

**Comment by joepavitt** [comment]
Given we now have Node-RED Dashboard 2.0, and have [plenty of issues there](https://github.com/orgs/FlowFuse/projects/15/views/1) - closing this
