### ISSUE TITLE
Test Coverage for Team Library

### ISSUE THREAD

**Issue by Pezmc** [FlowFuse/flowfuse#1708]
### Description

Team library is an EE edition feature, which meant it didn't receive E2E test coverage on the first go-around.

There's now a `cy.enableBilling()` option, which should make it possible to test.

Separately; there needs to be a wider discussion around how the E2E tests for EE features should be grouped.

### Epic/Story

#1597

**Comment by joepavitt** [comment]
We do now have EE test coverage, but the chore of including Team Library coverage hasn't yet been completed

**Comment by joepavitt** [comment]
Closed by https://github.com/FlowFuse/flowfuse/commit/63f29ceb251c0d2ac45d558f62558d89cf4195b7
