### ISSUE TITLE
Update filter default options to say 'All XYZ' rather than 'Not specified'

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#1785]
In our filterable views, eg AuditLogs, the default labels for the filters is 'Not specified' if nothing is selected.

That makes me feel like I need to select something, even if it's actually the appropriate (non-)selection.

I think it would be better for them to say 'All XYZ' - that is a better reflection of what that filter is doing at that point in time.

<img width="166" alt="image" src="https://user-images.githubusercontent.com/51083/224002154-53b3a6d5-7a96-47e6-a396-5258a187a60b.png">

_Originally posted by @knolleary in https://github.com/flowforge/flowforge/issues/1782#issuecomment-1461794951_

**Comment by joepavitt** [comment]
verified in staging
