### ISSUE TITLE
Unable to set project/instance type of a legacy project in FF 1.5.0

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#1856]
### Current Behavior

I have an old project with no projectType set.  When I attempt to "change instance type" I get the below error...

![image](https://user-images.githubusercontent.com/44235289/226329042-d5858a60-7d17-43f3-90a7-2b4f3c8e3e3c.png)

### Expected Behavior

In prior versions of FF, we were told that the project had no type & were offered a means to set its type
![image](https://user-images.githubusercontent.com/44235289/226329169-10e8f38e-4867-4987-bda5-9d0028d5b4e2.png)

### Steps To Reproduce

You will need a legacy project to test this but essentially;
* select the instance
* attempt to "change instance type" to "something"

See video:

https://user-images.githubusercontent.com/44235289/226329360-50fb0266-b01d-445d-9833-612d34d0cff7.mp4

### Environment

- FlowForge version: 1.5
- Node.js version: 16
- npm version: 8
- Platform/OS: Windows 11
- Browser: Chrome

**Comment by joepavitt** [comment]
Don't think we've had many people hitting this issue, and given no updated in over a year, will close
