### ISSUE TITLE
Stripe does not allow a subscription with more than 50 keys

### ISSUE THREAD

**Issue by Pezmc** [FlowFuse/flowfuse#1948]
### Description

```
[2023-04-11T01:36:57.225Z] WARN: Problem adding project to subscription
Metadata can have up to 50 keys, but you've set 51. Email us at support+metadata@stripe.com for more information.
```

This is likely due to projects not being removed from a subscription entirely when deleted. I believe it's set to false right now for both suspend and delete.

**Comment by knolleary** [comment]
This does put a limit of 50 instances within a team. We need to review our use of metadata and not rely on it.

**Comment by Pezmc** [comment]
Off the top of my head, there's no logic based on the subscription project metadata (only `free_trial` flag), and it's stored solely for informational purposes in Stripe, but indeed we should review.

**Comment by knolleary** [comment]
Closing as we no longer use stripe meta-data to track instance ids.
