### ISSUE TITLE
Iterate on "You've been invited to FlowForge" email

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#1967]
### Description

<img width="807" alt="Screenshot 2023-04-12 at 12 52 43" src="https://user-images.githubusercontent.com/99246719/231448862-5d2c5f73-c37e-4542-882f-0a6b787558f4.png">

G-Mail flagged this as "looking phissy" when it arrived in my inbox. We should seek to improve the styling of this to make it look more professional and legitimate.

We've had a lot of stale invites for FlowForge Cloud, this could likely be a reason why, as it doesn't look trustworthy.

**Comment by joepavitt** [comment]
useful guide on the things to account for: https://blog.hubspot.com/marketing/html-email

**Comment by iskerrett** [comment]
FWIW, it would be nice to move all of the FF Cloud generated email into Hubspot. This way we can create a consistent look for our emails and track their success.

**Comment by hardillb** [comment]
These have to work for none FlowForge Cloud instances that don't have HubSpot.

**Comment by Yndira-FlowForge** [comment]
Here's a proposal:

Desktop

![Image](https://github.com/flowforge/flowforge/assets/129537638/e2b2413c-bfb5-4329-ac92-03d6283a96c9)

Mobile

![Image](https://github.com/flowforge/flowforge/assets/129537638/6ccf2d8a-a778-4d7c-85fa-1a7d78f0c81a)

> useful guide on the things to account for: https://blog.hubspot.com/marketing/html-email

@joepavitt I read the article. They suggested a platform where you can create the email with visual tools and then export a zip with the html and images, you can also send test emails to see how they look/behave on different email clients and devices.

I just built it there, already sent you an invitation, a test email (check your spam folder please, the sender is BEE Pro), and the folder with the html and images is in our [drive](https://drive.google.com/drive/folders/1UFtymw9FAxDn4NLar7_wQjKqWZJmecFr?usp=sharing). They add their logo at the bottom but I just removed it from our html.

Not sure how you get the name of the FF team or the link for the button, will need your help with that.

**Comment by joepavitt** [comment]
Thanks Yndira. Going to need to work out how we architect the actual sender of the e-mails given @hardillb's point above. We should be utilising something like HubSpot if we can, but do need a backup option inside FF to handle non FF Cloud installs.

**Comment by Yndira-FlowForge** [comment]
I guess I misunderstood what he said, I thought we couldn't use HubSpot.

For some reason, an html + images is what I thought you needed to be able to include the non FF Cloud installs.

I can build it in HubSpot too, and create a template for all our emails...

@iskerrett gave me access and I did check it out, but couldn't find an option to export it as a zip (now I realise it might be a permissions issue)

Let me know when you've figured out next steps ;)

**Comment by Pezmc** [comment]
> Currently the email templates are in the source code, it may make sense to move them to the DB and allow them to be edited in the admin settings.

Unless we're going to build change tracking etc, I feel like this adds a lot of complexity without much benefit. A middleground could be have a folder of .html templates that is read, so if an end user wanted to change them, they can just change the .html.

But that's getting off topic on this issue, the above proposed changes look like a notable improvement 👍

**Comment by Yndira-E** [comment]
Being addressed with new branding in https://github.com/FlowFuse/flowfuse/issues/4039
