### ISSUE TITLE
SOC2 certification

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#2020]
SOC2 is an industry standard certification for the procedures a company has when it comes to security. It covers a wide range of topics focused on information security and privacy.

When companies are evaluating their vendors, this type of certification is often a pre-requisite to doing business.

We have already started our journey towards SOC2, with an aim to complete SOC2 Type 1 by end of Q2 and then maintain an ongoing SOC2 Type 2 certification.

Whilst this epic is the high-level item for tracking our progress, we are using Vanta as our SOC2 auditing and compliance monitoring platform.

During the initial adoption phase, due to the security-focused nature of this work, we will track internal progress via Vanta and issues on our private repositories as appropriate.

We will update this issue as key milestones are achieved in the process.

**Comment by robmarcer** [comment]
requested by - https://app-eu1.hubspot.com/contacts/26586079/record/0-2/6568939245

**Comment by MarianRaphael** [comment]
FlowFuse has achieved SOC 2 Type 1 compliance!
