### ISSUE TITLE
Allows httpStatic to be used

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#211]
### Epic

#209

### Description

This needs some careful discussion before we decide to do this. Allowing a user to upload arbitrary content that is served from a FF hosted application brings a number of complications around managing that content.

**As a:** User

**I want to:** Configure httpStatic and upload files

**So that:** My project can serve static content

**Comment by MarianRaphael** [comment]
Related Issue: [Allow local configuration of https/httpStatic on a device ](https://github.com/flowforge/flowforge-device-agent/issues/110)

**Comment by knolleary** [comment]
Closing as this will get picked up as part of #4194
