### ISSUE TITLE
Support for Node 18 in our stacks

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#2181]
### Description

We currently base our stacks on node.js 16. We need a plan to support node 18 - particularly as we have seen cases of nodes that only support node 18 or later (eg node-red-contrib-salesforce).

1. We cannot just update all exists to Node 18 as that could break existing instances if they have nodes that don't support 18. I think this is rare, but not impossible.
2. Should the choice of node.js version be something the user is given?
   - with our existing stack model, we could create two sets of stacks for each Node-RED version - one node 16 and one node 18. However for many users, the choice of node.js version is irrelevant and this would force them to pick from a long list.
   - we could role out node 18 with just the Node-RED 3.1 stack. Users on existing stacks will stay on Node 16 and they can make a more considered decision to update their stack to Node-RED 3.1/Node 18. If something doesn't work, then can change they stack back to the Node-RED 3.0.x/Node 16 one.

We need to test/validate node 18 in the stack. All of our nr-launcher and plugin code will run in that version of node - we currently only test on node 16. So whilst the stack work described above is *mostly* admin tasks in the platform, we need to do some engineering work to validate our code on node 18.

The one breaking change between node 16 and node 18 that we've seen come up in some unexpected contexts is the dns resolution order has changed. Previously it would return ipv4 addresses first. It now returns them in whatever order the dns resolve provides them in - often resulting in getting an ipv6 address pack. That can cause unexpected issues. We have done some future proofing against that in the launcher by using `127.0.0.1` rather than `localhost` - but we need to fully validate that.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
> we could role out node 18 with just the Node-RED 3.1 stack. Users on existing stacks will stay on Node 16 and they can make a more considered decision to update their stack to Node-RED 3.1/Node 18. If something doesn't work, then can change they stack back to the Node-RED 3.0.x/Node 16 one.

That seems like a nice approach,

And, I believe we could, (at a future point  / if requested), support setting up a stack with different nodejs version?
