### ISSUE TITLE
Change text in the sign-up page

### ISSUE THREAD

**Issue by Yndira-FlowForge** [FlowFuse/flowfuse#2485]
### Description

We'd like to increase conversion rate in our sign-up page.

## Current status

Conversion rate for the **last 7 days**:
<img width="1073" alt="Screenshot 2023-07-26 at 09 52 53" src="https://github.com/flowforge/flowforge/assets/129537638/868bdfbe-f672-4dcf-8ff0-ad8b37d32e7c">

Conversion rate for the **last 14 days**:
<img width="1079" alt="Screenshot 2023-07-26 at 09 54 25" src="https://github.com/flowforge/flowforge/assets/129537638/228ec4d4-0144-49f2-9de3-9a98af5b28a8">

Conversion rate for the **last 30 days**:
<img width="1078" alt="Screenshot 2023-07-26 at 09 54 47" src="https://github.com/flowforge/flowforge/assets/129537638/f3368ed7-d2cf-4ebe-8e48-795a2264fd08">

## Requested changes

@iskerrett suggested we changed some of the text in that page and check if it has an impact, all the requested changes are [here](https://www.figma.com/file/hXDN5PnY3TmeQSv3n7Hna5?node-id=2322:23422&mode=design#497081192).

## How success looks like

Ideally, we aim to achieve a 50% conversion rate. We will assess the numbers one week after implementing the changes to see how it is progressing.

[Here's an article](https://www.heap.io/blog/good-conversion-rate-signup-flow) with benchmarks on sign-up page conversions for reference.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-FlowForge** [comment]
@iskerrett It would look like this with the changes applied:
<img width="1439" alt="Screenshot 2023-07-13 at 15 21 04" src="https://github.com/flowforge/flowforge/assets/129537638/6a05721a-87e3-4a4b-a381-8091818bafea">

@joepavitt please take a look as well, currently, there are three items to the left, but in this version there are only two, so I aligned the title of the left side with the first form field.

[Here's the figma file](https://www.figma.com/file/rMB2w5ZZUtTC0nxbwLYKJY/FlowForge-Platform?type=design&node-id=2642%3A20547&mode=design&t=ouuLVrHKjqPEmHGk-1), in case you'd like to add comments to it.

**Comment by joepavitt** [comment]
Reads a little odd with the 2 x "with Node-RED", don't think the second one is necessary?

**Comment by iskerrett** [comment]
I am fine with deleting the second 'with Node-RED'. We are focused on increasing FF Cloud sign-ups, regardless of their interest. This test is to see if we simplifying this page we can get more people to sign-up.

**Comment by iskerrett** [comment]
@joepavitt is it possible @Yndira-FlowForge can make these changes?  If not, when do you expect to get to them?

**Comment by joepavitt** [comment]
Anybody can sign into FlowForge (that's an admin, although I think admin creds are in 1Password) and can make them. I've only got an hour or so left of my day today and need to prioritise Dashboard stuff due to impending Alpha release. I'm out tomorrow and Thursday, so earliest would realistically be Friday.

They're not too complicated to change though, so any of the dev team can help here.

**Comment by hardillb** [comment]
@Yndira-FlowForge or @joepavitt can somebody tell me what the URL for the credit card graphic in the new layout is? All the other graphics are loaded from `https://flowforge.com/images/pictograms/`

**Comment by Yndira-FlowForge** [comment]
Hi @hardillb is this one https://flowforge.com/images/pictograms/no_credit_card.png

**Comment by hardillb** [comment]
Should be done

![image](https://github.com/flowforge/flowforge/assets/1800845/dda9cf9d-1e71-411b-9e6c-985f419a6784)

**Comment by Yndira-FlowForge** [comment]
Thanks @hardillb!

Could the credit card pictogram be center-aligned with the text next to it? It would also be nice to have a bit more vertical spacing between the elements.

[Here's the figma file](https://www.figma.com/file/rMB2w5ZZUtTC0nxbwLYKJY/FlowForge-Platform?type=design&node-id=2642%3A20547&mode=design&t=ouuLVrHKjqPEmHGk-1) if you wanna check the distances.

<img width="288" alt="Screenshot 2023-07-18 at 18 10 13" src="https://github.com/flowforge/flowforge/assets/129537638/2bec1425-45ae-42c3-9f60-6aac202d226d">

**Comment by Yndira-FlowForge** [comment]
Thanks @hardillb for fixing it! 

it's like this now:

<img width="1052" alt="Screenshot 2023-07-18 at 19 09 40" src="https://github.com/flowforge/flowforge/assets/129537638/a14966c4-8479-478f-aa68-2c79e8016d9a">

We'll check [the numbers](https://eu.posthog.com/insights/dbkPqclR) next week.
