### ISSUE TITLE
Device Editor: change websocket handling for scalability

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#2514]
### Description

When the Device Editor is enabled the Device Agent creates a WebSocket connection back to the Forge App.

When a user access the Node-RED editor, the requests are sent to the Forge App (including its own WebSocket) and then tunnelled over the Device Agent's WebSocket.

If there are two instances of the Forge App, only one of them will hold the Device Agent WebSocket connection. If the requests to access the Node-RED editor are load balanced between the instances, only those that arrive at the 'connected' instance will be handled - the others will be dropped.

Even if we enable some form of 'sticky' session to ensure requests for a single browser session are all sent to one instance, we would need a way to direct that to the 'right' instance.

#### Possible solutions

1. Move the proxy to a separate service.
    - **Pros**
         - removes the load of the device editor from the main forge app.
    - **Cons**
         - Device Agent needs to be told where to connect to. All existing agents assume its the forge app - so we have a legacy support issue. Might be possible to tell the websocket to redirect... not sure.
         - Another service to maintain that will have all the same scalability challenges over session/websocket stickiness if the service were to be scaled horizontally.

2. Sticky sessions in nginx
    - **Cons**
        - Still need a way to get the requests to the 'right' instance where the Device Agent tunnel is connected.

**Comment by knolleary** [comment]
With the current architecture, restarting the forge app interrupts ongoing editor sessions. As we move to a CI/CD approach, this could potentially happen more often and start impacting users.

@MarianRaphael We should prioritise this task, or investigate other potential mitigations to ensure any impact is minimal.

**Comment by knolleary** [comment]
I've pulled this item under the epic #2782 which is a broader topic around scalability. Moving the tunnel handling to a separate service might *not* be the right solution, but this issue should be used to track identifying and implementing whatever is needed to address this particular scalability issue.

**Comment by MarianRaphael** [comment]
Investigation issue: https://github.com/flowforge/flowforge/issues/2725

**Comment by knolleary** [comment]
@hardillb @ppawlowski would like your input here on what we can do with sticky sessions in the ingress.

To summarise the problem - for the device editor, we use persistent websocket connections. One is from the Device to the platform, the other is from the user's browser to the platform. For the Device Editor to work, those two websockets need to land on the *same running copy* of the platform. Do we have any means to use some sort of hashing of some attribute of a request to direct requests to a consistent instance?

**Comment by hardillb** [comment]
The second and third annotations here (https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md) appear to be how to control this on nginx.

It appears the only option is cookie based, so we would need the device agent to be updated to accept a cookie being set in an inital request and to then use that for all subsequent requests.

The client side should be handled automatically by the browser

The problem would be linking both sides, as even if we kicked off opening the tunnel from the users browser we would still need a way to force the device agent to bind to the same backend instance.

The only way i can see to make it work is if we could get the users browser to share the cookie with the device agent as part of the handshake that opened the tunnel.

Just my initial brain dump of thoughts

**Comment by ppawlowski** [comment]
I've done some research on the topic of scalable websocket service architecture and it seems like the ultimate solution is to use publish-subscriber solution:
https://tsh.io/blog/how-to-scale-websocket/
https://hackernoon.com/scaling-websockets-9a31497af051

Additionally, together with sticky sessions, we need to change the load balancing algorithm from _round robin_ to _least connections_ to direct new requests to the instance with less established connections.

The downside of the sticky session is:
* Kubernetes Horizontal Pod Autoscaler might be useless since an overloaded pod will trigger new pods to create but they will handle only new traffic
* overloaded pod will have an impact on overall frontend stability and response time to customers - IMO we should consider separating frontend from backend logic

**Comment by hardillb** [comment]
Idea:

Extend the enable editor command sent to the device to include a WebSocket connection URL, this tells the device agent explicitly where to connect to.

The same hostname can be used to generate the device editor URL. This removes the need to load balance.

The forge app would need to keep a list of Device Editor access hosts to pick from.

Legacy device agent versions would still connect to the "main" instance based on device agent version.

Not as elegant as an auto scaling/loadbalaner affinity solution, but probably easier to implement.

**Comment by hardillb** [comment]
A quick test of the nginx affinity ingress annotations mentioned above appears to work as expected for basic HTTP connections. I need to double check it also works for WebSocket connections.

The only key for the mapping is the cookie.

Will need to think how this applies to both browsers and device agents reconnecting

**Comment by hardillb** [comment]
Yep, this all works, but it does require a way to share the cookie value between both the device-agent and the browser

**Comment by hardillb** [comment]
Basic draft implementation PRs queued up.

Will need Ingress annotations adding on Kube cluster to enable and multiple forge app instances to test properly.

Also requires all Device Agents to be updated to work for all.
