### ISSUE TITLE
Send email alerts to users when their instances crash or restart

### ISSUE THREAD

**Issue by robmarcer** [FlowFuse/flowfuse#2518]
### Description

**As a:**

User of FlowForge

**I want to:**

Get alerts (probably by email) when there are issues with my instance which will stop my flows from running.

**So that:**

If an instance crashes, or ends up in a crash loop I can take steps to resolve the problem.

### Which customers would this be availble to

Licensed Edition (EE)
Teams Tier

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

## Scope (Marian edit)

- [ ] Email Notification Setup: Introduce the capability to add an email address under the Instance Settings General tab. This will serve as the destination for alerts.

- [ ] Notification Preferences: Implement a drop-down menu in the Instance Settings to allow users to subscribe to notifications for specific Audit log events. Users should be able to select multiple events for which they wish to receive notifications. The options in this drop-down menu should include:

- Instance Crash
- Instance Restart
- Node-RED Stopped
- Instance suspended 

- [ ] Alert Behavior: Upon the occurrence of any selected event, the system will automatically send a standard email notification to the specified email address, informing the user of the event.
- [ ] Owner privileges required

**Comment by MarianRaphael** [comment]
- The user should be able to turn on/off these alerts from the settings
- The user should be able to select which instances they want to monitor for issues (default off)
- When an issue is resolved and the instance is back to normal, the user should receive a confirmation email stating the same

**Comment by robmarcer** [comment]
Customer who wants this feature - https://app-eu1.hubspot.com/contacts/26586079/contact/3501

**Comment by robmarcer** [comment]
Another customer vote for this - https://app-eu1.hubspot.com/contacts/26586079/record/0-1/1761151

**Comment by hardillb** [comment]
I think a first step towards this is that the launcher should raise audit log events when it restarts Node-RED due to an unexpected exit. At the moment we just place an entry in the Node-RED logs.

https://github.com/FlowFuse/nr-launcher/blob/f1b879d6953a91dc0aae09b703e8b3dfa4b88194/lib/launcher.js#L442

If we raise an Audit Log entry we would then have something to hook the emails to.

**Comment by MarianRaphael** [comment]
Yes, as mentioned in the description:
- Instance Crash
- Instance Restart
- Node-RED Stopped
- Instance suspended

What would be the difference between  "it restarts Node-RED due to an unexpected exit" and the log entries  "Instance Crash" and "Node-RED Stopped"?

**Comment by hardillb** [comment]
"Unexpected exit" is "Instance Crashed"

"Stopped" is either NR has crashed in safe mode (which probably means a very broken node doing things before any instances of the node are instantiated) or a failure to install the dependencies at startup.

**Comment by hardillb** [comment]
OK, we already have Node-RED crashed audit events, need to workout where they are getting raised from

**Comment by hardillb** [comment]
Found, but I still think we should add an extra Audit log event for when the launcher puts the instance into safe mode.

**Comment by MarianRaphael** [comment]
Based on the [Slack discussion](https://flowforgeworkspace.slack.com/archives/C03387T7UFP/p1702464266803109):
The email could be spam if it's not verified is a good point. Let's make it a list of the owners.

**Comment by MarianRaphael** [comment]
Documentation: https://github.com/FlowFuse/flowfuse/pull/3244

**Comment by hardillb** [comment]
Verified on staging, but needed to enable flowfuse.com domain on staging AWS SES service to allow sending to that domain.
