### ISSUE TITLE
FF Admins should still be able to interact with a team's UI when there is a billing problem

### ISSUE THREAD

**Issue by robmarcer** [FlowFuse/flowfuse#2528]
### Description

Currently when a team needs to correct a billing issues they cannot access the UI of FlowForge until that issue is resolved. They are redirected back to billing no matter what they try to view.

FF Admins should still be able to access the team so they can provide support to customers.

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by joepavitt** [comment]
Curious here @robmarcer - if it's a billing issue, i.e. they've not paid us, then I'm not sure why we should be giving access to their resources to debug/fix/deploy, etc.

**Comment by robmarcer** [comment]
I don't have to give them access, I (as an admin) want to be able to access their team to understand their usage so I can encourage them to fix the billing problem.

**Comment by robmarcer** [comment]
Exactly. :-)

**Comment by cstns** [comment]
What state does the subscription need to be in order for the redirect to be triggered? I assumed past_due would suffice but I'm able to freely browse the app.
