### ISSUE TITLE
ff_snapshot_name returns incorrect value on devices

### ISSUE THREAD

**Issue by robmarcer** [FlowFuse/flowfuse#2534]
### Current Behavior

After updating the snapshot running on a device the old env var for ff_snapshot_name is still returned to flows running on the device.

### Expected Behavior

The correct ff_snapshot_name should be returned.

### Steps To Reproduce

Update the snapshot running on a device.

Access ff_snapshot_name from the flow.

The old ff_snapshot_name is shown from before the new snapshot was deployed.

### Environment

- FlowForge version: 1.9.3 Cloud
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by joepavitt** [comment]
Still worth keeping open @robmarcer?

**Comment by robmarcer** [comment]
I've not seen this issue in months and I use ff_snapshot_name almost daily in demos. If this ever was a bug it seems to no longer be evident.
