### ISSUE TITLE
Funky alignment of elements of Forgot Password page

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#2552]
### Current Behavior

https://github.com/flowforge/flowforge/assets/44235289/582dc30e-79ba-463a-81c8-5cccb6e4639e

### Expected Behavior

Should look better

### Steps To Reproduce

goto forgot password page

### Environment

- FlowForge version: 1.9.4 - current
- Platform/OS: Windows
- Browser: chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
This isn't limited to the Forgot Password page; the setup wizard suffers the same fate. Something must have changed in some common css here.

**Comment by hardillb** [comment]
The password field is fixed, I'll have a quick look at the setup wizard and see if it can be fixed the same way
