### ISSUE TITLE
Add LDAP to SSO support

### ISSUE THREAD

**Issue by zackwasli** [FlowFuse/flowfuse#2558]
### Description

It would be useful to support a wider range of SSO protocols like LDAP, in addition to SAML (currently supported)

## Requested by

-https://app-eu1.hubspot.com/contacts/26586079/record/0-2/9822854636
-https://app-eu1.hubspot.com/contacts/26586079/record/0-2/10135626714

**Comment by MarianRaphael** [comment]
Requested by: https://app-eu1.hubspot.com/contacts/26586079/record/0-2/9822854636

**Comment by hardillb** [comment]
This could be done by inserting something like keycloak, I have a local test setup for SSO which uses my local LDAP as the source of users/groups. Would be zero code change for FF, but is one more thing to manage.
