### ISSUE TITLE
Can not delete a trial account

### ISSUE THREAD

**Issue by iskerrett** [FlowFuse/flowfuse#2559]
### Current Behavior

If I open a trial account, then I decide I am finish my trail and want to delete my account. I go to User Settings and press Delete Account. I get the error message 'Can not delete the last owner of a team'.  However, I didn't invite any team members so it is even possible to delete this account?

### Expected Behavior

I would expect we want to allow people to delete their accounts after completing their trial.

### Environment

- FlowForge version: 1.10

## Feature request and Scope (Marian)

Implement a more intuitive account deletion process. Specifically, when a user who is the last member and owner of a team attempts to delete their account, a pop-up should automatically appear. This pop-up will prompt the user with the option to also delete their team(s) where they are the sole remaining owner. This change will replace the current error message ('Cannot delete') with a proactive solution, simplifying the account deletion process for individual users and ensuring a smoother user experience.

### Have you provided an initial effort estimate for this issue?

I am not a FlowForge team member

**Comment by hardillb** [comment]
@MarianRaphael can we schedule something around this. While we want to keep users it shouldn't be because they can't work out how to leave.

**Comment by MarianRaphael** [comment]
FYI - I added a Scope

**Comment by hardillb** [comment]
Yep, doing it steps, but will look at that bit next

**Comment by hardillb** [comment]
Verified deleting teams with Applications, Instances and devices on staging.

Nick to test deleting a team with expired team (but should be no different)

**Comment by knolleary** [comment]
Spotted an issue trying to delete expired team. Investigating.

**Comment by knolleary** [comment]
I can successfully delete a team with an expired trial locally. However there is a team on staging that appears to be in that state, but the delete fails.

Need to poke into the database to understand how/why it is failing.

**Comment by hardillb** [comment]
@knolleary did you get to the bottom of this?

**Comment by knolleary** [comment]
I think this was a result of Stripe cancelling the subscription after 3 months (as it does by default on the test account). That got things in to a weird state. Happy to close this off.
