### ISSUE TITLE
Possibility of orphaned devices and storage items connected to teams

### ISSUE THREAD

**Issue by Pezmc** [FlowFuse/flowfuse#2569]
### Current Behavior

When instances, teams, devices, applications or users are deleted, several related models are left behind orphaned in the database.

On a quick review; this includes: 
 - Devices for Instances
 - ProjectSnapshots for Instances
 - DeviceSettings for Devices
 - AccessTokens for Users
 - Invitations for Users

### Expected Behavior

These tables should also be cleaned up to prevent orphaned data being left behind; there are potential privacy and security implications if they sit in the database forever.

Proposal:
 - Research into what data is left orphaned
 - For each decide whether to:
   - Keep the data around for audit purposes and have the default SET NULL
   - Set ON DELETE for immediate removal
   - Manually clean-up as part of related object deletion
   - Block deletion of the parent object if there are still children (how teams/application currently behave for instances)
   - Allow orphaned record, but have a cron that cleans them up after X days (to allow recovery) 
   - Set a "deleted" flag on those tables and schedule a cron that cleans up after X days (to allow recovery)

### Steps To Reproduce

Delete a team/instance and check the database for any orphaned r

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Pezmc** [comment]
Related to https://github.com/FlowFuse/CloudProject/issues/335

**Comment by joepavitt** [comment]
@knolleary any idea on the status of this? Was marked for `2.1`, and has been sat in "todo" for a while?

**Comment by knolleary** [comment]
@joepavitt Need to re-review the full list of potentially orphaned items. Some bits (like Devices) may have been addressed by other work in the meantime.

I'll put this on my pile - its a pretty small shelf-contained chore that'll be good to get done.

**Comment by knolleary** [comment]
Have reviewed the list. Only one immediate action to take - #4063 - then we can close this off.
