### ISSUE TITLE
Feedback to user that a restart is required after settings changes

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#2581]
### Description

<img width="1728" alt="Screenshot 2023-08-11 at 14 35 10" src="https://github.com/flowforge/flowforge/assets/99246719/0a6c214d-d8b1-4c38-b667-246dacc2b8e5">

If a user changes the theme, a restart of the Editor is required for this to take effect, however, we don't ever tell the user this, and it's not intuitive given that changes are "saved".

We should provide feedback, potentially in the confirmation alert, that a restart is required.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
I _think_ I'm right in saying that _all_ options in this Settings page would actually mean a restart is required in order to see any affect? Not just the theme as was originally raised.

**Comment by Steve-Mcl** [comment]
> I _think_ I'm right in saying that _all_ options in this Settings page would actually mean a restart is required in order to see any affect? Not just the theme as was originally raised.

Yeah, they all update the node-red settings file which means they are not picked up until a restart.

NOTE: I am pretty sure there are other places where this is true also. For example, applying security for dashboard requires a restart to (and perhaps others)

Should i do a sweep or just concentrate on the page this issue discusses.
