### ISSUE TITLE
Add menu item 'Assign to Application Instance' to the device management menu

### ISSUE THREAD

**Issue by griemenschneider** [FlowFuse/flowfuse#2663]
### Description

As a FF device administrator I want to quickly move devices between application instances as part of our normal usage of the DevOps pipeline. It would be a nice feature to allow devices move devices between instances with less clicks. Use case: we want to pull a handful of devices from our PROD instance to a STAGE instance to conduct acceptance testing before we push the code all the way down the pipeline. Current pattern is ‘Remove from Application Instance’ and then ‘Assign to Instance’ – but could there be another option in this menu ‘Assign to Application Instance’ that just does these two steps in one click? Doing so would be less clunky and also reduce downtime of devices are they move between instances.

The proposal is to add a menu item to this device management menu:

![image](https://github.com/flowforge/flowforge/assets/135891848/18c2ab85-9077-4904-8ddf-898088f85347)

### Have you provided an initial effort estimate for this issue?

I am not a FlowForge team member

**Comment by MarianRaphael** [comment]
An additional “Reassign button” as option

**Comment by MarianRaphael** [comment]
See also: https://github.com/FlowFuse/flowfuse/issues/2800
