### ISSUE TITLE
Allow an Instance Template to be restricted to particular TeamTypes

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#2709]
### Description

_This issue is a result of discussion in https://github.com/flowforge/flowforge-nr-launcher/pull/145_

Currently all Templates are available to all teams/users on the platform.

The requirement here is to be able to restrict a Template to certain TeamTypes. By default, a Template will be available to all TeamTypes (as is the case today). But the admin will be able to restrict it to one or more TeamTypes.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by zackwasli** [comment]
Nick are you able to please post the HubSpot link for the customer who requested this feature?

**Comment by knolleary** [comment]
This was raised as my proposed fix for the customer issue https://github.com/FlowFuse/nr-launcher/pull/145

However, the customer request was eventually resolved another way. As such, I've removed the customer label from this story.

On balance, there is no real demand for this feature as described and i. I'm going to close it off.
