### ISSUE TITLE
Possibility of extending the trial period

### ISSUE THREAD

**Issue by Yndira-E** [FlowFuse/flowfuse#2722]
### Description

We're considering implementing an ongoing survey for users who are ending their trial period. As an incentive, we would like to offer an extension of the trial period, which could be either 7 or 14 days more. However, at the moment, it's not technically possible.

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by joepavitt** [comment]
Trial period has since been changed - no longer relevant here
