### ISSUE TITLE
Assign stand-alone Devices to DevOps pipeline

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#2756]
### Epic

https://github.com/flowforge/flowforge/issues/2334

### Description

Allow FlowForge Users, to assign their stand-alone devices to DevOps pipelines (source and target stage). This feature should follow the behavior implemented in the "Push Snapshots Through DevOps Pipeline" (#2651) issue.

## Requirements

As we already have the functionality to assign devices directly to applications (#2619) and create snapshots (#2609), it is the next step to extend this to DevOps pipelines.

##  User Story

As a FlowForge User who works primarily with Devices,
I want the possibility to assign my stand-alone Devices to DevOps Pipelines,
So that I can promote my developed snapshots from a Device to another Device (or instance).

### Which customers would this be availble to

Licensed Edition (EE)

### Acceptance Criteria

- [x] Ability to assign a stand-alone Device to a DevOps Pipeline as a source and/or target stage
- [ ] The operation of stand-alone devices in the pipeline should follow the logic and behavior implemented in "Push Snapshots Through DevOps Pipeline" (#2651)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by MarianRaphael** [comment]
Keep in mind the next iteration will include Device tagging

**Comment by Pezmc** [comment]
Edge cases of note (rough notes from Pez)

 - Snapshots for devices can only be created in dev mode - device must be in dev mode to generate a source snapshot
 - Device might be tied to an instance, or an application

Currently stages are 1:1 mapped to instances at the application layer (but 1:many at the database layer). After the proposed changes in this issue, a stage can be end alone.

A stage will now be able to have:
 - An instance
 - A device via an instance
 - A device directly from the application

Open question: Does dev-ops pipelines replace the need for devices to be tied to instance in the first place?
Currently pipelines is EE only, so we'd need to consider the business implications of that.

We need to talk through device tagging and device pipeline overlap and use cases; and what is out of scope.

Open qs:
 - What combinations to support today? Down the line
 - What is the UI/UX for those?

**Comment by Pezmc** [comment]
Verified on staging, follow up issues for polish created: #3112, #3113, #3114
