### ISSUE TITLE
Notifications Inbox

### ISSUE THREAD

**Issue by sammachin** [FlowFuse/flowfuse#277]
### Description

**As a:** User

**I want to:** See a consolidated list of my notifications and be able to action/delete them.

**So that:** I have a clear view of important changes/activity that has taken place on FlowFuse

### Development Plan

```[tasklist]
### Primary Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/4113
- [ ] https://github.com/FlowFuse/flowfuse/issues/4158
- [ ] https://github.com/FlowFuse/flowfuse/issues/4165
- [ ] https://github.com/FlowFuse/flowfuse/issues/4184
- [ ] https://github.com/FlowFuse/flowfuse/issues/4245
```

```[tasklist]
### Follow On Tasks
- [ ] Notifications: Provide notifications for Device/Instance crashes
```

```[tasklist]
### Extra Tasks
- [ ] Admin panel for sending notifications to users
```

**Comment by sammachin** [comment]
@joepavitt why did we think this was a v1 item?

**Comment by sammachin** [comment]
@joepavitt I've removed the v1 label as its not on the critical path, however I do agree that in terms of UX its something we should have soon, with your upcoming availability in mind it would be good to have the design work done.

**Comment by joepavitt** [comment]
Will slip to 1.2

**Comment by joepavitt** [comment]
@knolleary was just thinking about this a little more, another opportunity here is to send notifications when new headline features are released - could help gauge interest, and make sure users are aware of the new functionality?
