### ISSUE TITLE
Assign Device to Instance/Application in Device Page & Devices Screen

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#2800]
### Description

Currently, the only place you can assign a Device to an Instance/Application is at `/devices`. Whilst this makes sense, there are multiple other places that we should also enable this that users will likely go:

- `/devices/<device-id>` - on the Overview screen, if no Application/Instance has been assigned, offer an option to assign the device, or add an "Actions" button top-right as we have for Applications/Instances, that also provides this functionality.
- `applications/<application_id>/devices` - Here we see a list of (if any) devices bound to this Application. There exists no functionality here though to bind more devices to this Application.
- `instances/<instance_id>/devices` - Here we see a list of (if any) devices bound to this Instance. There exists no functionality here though to bind more devices to this Instance.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by MarianRaphael** [comment]
Actually, an issue that is planned is going exactly in the described direction. See: https://github.com/FlowFuse/flowfuse/issues/2663
The idea here was to add a Reassign button at different locations.
