### ISSUE TITLE
Accessing instance throws me into redirect loop

### ISSUE THREAD

**Issue by lgrkvst** [FlowFuse/flowfuse#2841]
### Current Behavior

When accessing an ff instance, I'm stuck in a redirect loop which can only be interrupted by deleting cookies.

![ff_redirect_loop_360](https://github.com/flowforge/flowforge/assets/4451499/75935297-1e34-42f3-9025-bba9fda942f6)

### Expected Behavior

User is redirected once to the The FlowFuse login window.

### Steps To Reproduce

1. Make sure you're logged into your ff app as an admin.
2. Using API calls and the admin's pat, create a new user (`createDefaultTeam: true`), application and instance.
3. In a new browser window, access the newly created instance.
4. Get stuck in an eternal 402 -> 302 loop

Regarding step 2, API calls, it's possible the bug is reproducible when accessing an instance which is point-and-click-created by a non-admin user (belonging to a group which excludes the admin user).

### Environment

- FlowForge version: v1.11.3 Enterprise Edition (Docker version)
- Node.js version: v16.20.2
- npm version: N/A
- Platform/OS: Linux
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I am not a FlowForge team member

**Comment by knolleary** [comment]
There is an upstream issue for this here: https://github.com/node-red/node-red/issues/4363

This is a side-effect of the `autoLogin` option we use in Node-RED.

With that option enabled, Node-RED will automatically bounce the user to the configured SSO login endpoint. In this instance, you are already logged in as Admin, who doesn't have permission to access the editor. So the login fails. Node-RED refreshes and then the `autoLogin` option kicks in again.

We need a way to break out of this loop.

**Comment by lgrkvst** [comment]
Possibly related to https://github.com/flowforge/flowforge/issues/1184?

**Comment by knolleary** [comment]
Have identified the fix for the Node-RED side of this. That will be in the next 3.1.x and 4.x releases.

https://github.com/node-red/node-red/pull/4684

**Comment by knolleary** [comment]
Marking as Needs Verification as we have no further work to be done on the FF side - but will need to verify once the new NR releases are available.

**Comment by knolleary** [comment]
Verified with beta 3
