### ISSUE TITLE
Loading Device page briefly flashes a red banner at top of page

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#2853]
### Current Behavior

When loading a Device page directly (ie paste URL, hit enter - not via navigating around the app), a red banner briefly flashes across the top. Could be the billing or trial notification banner - too fast to spot which.

This only seems to happen on the Device page. Suggests some state is initialised the wrong way and the banner is being shown before the API request completes to realise it shouldn't be shown.

### Expected Behavior

No flash of a banner

### Steps To Reproduce

 - Load a Device page

### Environment

- FlowForge version: 1.12

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
I have been through every page where we display devices (app + instance) and lists of devices on both staging and local.

I even simulated a slow network in dev tools.

This issue appears to be resolved (likely by other works since raised).

Please re-open if necessary.
