### ISSUE TITLE
Add flow.json to Templates

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#2854]
### Description

Add the option to include a flow.json Node-RED file in the FlowFuse Templates.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Tasks
- [ ] Build a flow.json database
```

**Comment by hardillb** [comment]
Will this need to include credentials as well?

**Comment by MarianRaphael** [comment]
ee feature
