### ISSUE TITLE
Create UI for selecting Flow Blueprints when creating instance

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#2874]
Part of #2828 MVP

Design proposals by @joepavitt in https://github.com/FlowFuse/flowfuse/issues/2828#issuecomment-1735335432

This will require the CRUD api to be delivered in #2871 

The `InstanceForm` component will need to be updated to allow the FlowTemplate selection to be made.

**Comment by MarianRaphael** [comment]
@Yndira-FlowForge first iteration

- Very simple selection while creating an instance
- Default selection should be "Blank" Node-RED

**Comment by Yndira-FlowForge** [comment]
Hi, I've spoken with @MarianRaphael, and we looked at the screen for creating an instance. We agreed on having the default-blank template already selected, and the option to choose a different template, perhaps with a button that opens a modal window displaying a list of templates.

As I examined all the elements and options we already have in place, trying to determine the best location for this feature, I noticed that we already have something labeled "template" when creating an instance. The "default" option is already preselected. Initially, I thought that maybe @Pezmc had already started working on the smallest possible iteration. However, after discussing it with him, I understood that this is a different type of template.

<img width="1181" alt="Screenshot 2023-10-10 at 16 55 16" src="https://github.com/FlowFuse/flowfuse/assets/129537638/d84cb3f9-7a5d-4873-a977-801b6b120c11">

<img width="1184" alt="Screenshot 2023-10-10 at 16 55 28" src="https://github.com/FlowFuse/flowfuse/assets/129537638/9a2decdc-390d-4d81-b5bf-8a186467cc3b">

Should we consider renaming these options? Having two items labeled "template" can be confusing. While one would be referred to as a 'Flow Template,' are we planning to keep the other one simply as 'template'? I don't see a description explaining what it means...

**Comment by knolleary** [comment]
In production, we only have one (Project) Template, which causes this row to be hidden as there is no choice for the user. In staging we have two templates - hence why it shows that row.

For the majority of FF Cloud users, the existing 'Template' terminology isn't going to be something they have had to learn about. So I think we do have some ability to relabel if we see fit.

**Comment by knolleary** [comment]
@Pezmc I've added a couple curl commands [here](https://github.com/FlowFuse/flowfuse/issues/2871#issuecomment-1755829289) for listing and injecting templates into the database.

**Comment by Yndira-FlowForge** [comment]
@MarianRaphael I know we discussed a pop-up, but how about this for the smallest possible iteration?

This would be more aligned with:

> A single new row in the Create Instance form, which defaults already to "Blank Template" and provides an option to "Choose Another/Alternative

1st state: without choosing an instance type.
![Create Application](https://github.com/FlowFuse/flowfuse/assets/129537638/26f2eeba-23b1-4adb-8d0a-a2264e4d4555)

2nd state: after choosing the instance type
![Create Application](https://github.com/FlowFuse/flowfuse/assets/129537638/a0a23701-8d67-439c-bcd0-9ad5925be272)

**Comment by MarianRaphael** [comment]
Yes, this works for the first iteration. The next step, as discussed, would be to implement a popup following Joe's proposal: https://github.com/FlowFuse/flowfuse/issues/2828#issuecomment-1735335432
