### ISSUE TITLE
Leaving device developer mode no longer warns user to create a snapshot

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#2875]
### Current Behavior

With the new pretty toggle button to enter and exit developer mode, users are no longer warned about possible loss of work when exiting developer mode due to changes being overwritten by a target change or flow-vs-snapshot difference being detected.

### Expected Behavior

Consider re-introducing the "Are you sure" dialog along with the warning about loss of work

### Steps To Reproduce

1. Enter dev mode
2. make a change to flows & deploy
3. Exit developer mode

### Environment

- FlowForge version: 1.12
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
See Example 4 in UI Components: https://flowfuse.github.io/forge-ui-components/#ff-toggle-switch
