### ISSUE TITLE
"Open Editor" enabled by default when in Developer Mode

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#2884]
### Description

From discussion with @Steve-Mcl and @ZJvandeWeg (https://flowforgeworkspace.slack.com/archives/C03FAUBPPJ7/p1696424993218099)

If Editor Access is not enabled at that point, we enable it ourselves, tell them it's opening connection, etc. and then open the Editor.

Existing UX around opening/closing tunnel still exists.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Linked with https://github.com/FlowFuse/flowfuse/issues/2885

**Comment by MarianRaphael** [comment]
In addition, rename the "Standard" Device Mode to "Fleet Mode." This way, users can easily switch between Developer and Fleet modes, making it clear which mode is intended for each use case.

**Comment by joepavitt** [comment]
I remember raising the concept of "Fleet" previously when working on terminology on the website, but recall @iskerrett saying that the user of "fleet" here wasn't appropriate. Will let Ian explain more detail on why that's the case.

**Comment by joepavitt** [comment]
Fleets would be consistent with SageMaker for example though: https://docs.aws.amazon.com/sagemaker/latest/dg/edge-device-fleet.html

**Comment by iskerrett** [comment]
It was more in the context of Fleet Management. This is typically used for tracking trucks, cars, etc.

**Comment by MarianRaphael** [comment]
What is about "Group Mode"?

**Comment by knolleary** [comment]
@MarianRaphael can we have a separate issue raised related to any renaming of what non-dev device is? It touches a lot more than the original purpose of this issue and isn't otherwise mentioned in the description here.

**Comment by MarianRaphael** [comment]
> can we have a separate issue raised related to any renaming

Absolutely, good point: https://github.com/FlowFuse/flowfuse/issues/3005

**Comment by Pezmc** [comment]
Verified on staging
