### ISSUE TITLE
Unable to administer last device in list due to chat widget

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#2897]
### Current Behavior

The chat widget is blocking access to the dropdown menu for the last device in the list.

<img width="232" alt="image" src="https://github.com/FlowFuse/flowfuse/assets/51083/b34d7667-3c65-479d-a2c4-c4076932d39c">

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
The workaround was to make the window sufficiently wide to get the chat widget moved out of the way.

**Comment by Steve-Mcl** [comment]
> The workaround was to make the window sufficiently wide to get the chat widget moved out of the way.

This is no longer possible.

![image](https://github.com/user-attachments/assets/a9217090-1453-4748-9831-ae2a660265c0)


@joepavitt could we move the chat bubble [to the left ](https://community.hubspot.com/t5/HubSpot-Ideas/More-Chat-Widget-Styling-Options/idc-p/242873/highlight/true#M26799)where there typically is nothing there (may need to change up char bubble colours for contrast).  
Or perhaps it can be draggable ([ref](https://community.hubspot.com/t5/HubSpot-Ideas/More-Chat-Widget-Styling-Options/idc-p/872624/highlight/true#M159101))?

**Comment by joepavitt** [comment]
Let's go draggable please Steve

**Comment by Steve-Mcl** [comment]
Still waiting feedback: https://community.hubspot.com/t5/HubSpot-Ideas/More-Chat-Widget-Styling-Options/idc-p/1034107/highlight/true#M192193

**Comment by knolleary** [comment]
fyi - reported by a customer: https://app-eu1.hubspot.com/contacts/26586079/record/0-1/28296901

**Comment by joepavitt** [comment]
Quick fix - add a large amount of padding to the bottom of the list

**Comment by Steve-Mcl** [comment]
Nick has stated on Slack there is still pages in admin views that have this overlap issue. In particular team types.

I will raise an issue as a follow up task
