### ISSUE TITLE
Link to change team type hidden

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#2904]
### Current Behavior

The "here" is a link, but the styling makes it near impossible to find

![image](https://github.com/FlowFuse/flowfuse/assets/1800845/f4747cc5-dc9f-4d62-bc74-365f0f38d32f)

### Expected Behavior

A big blue button rather than a hidden link

### Steps To Reproduce

Team -> Settings -> Edit team settings

### Environment

- FlowForge version: 1.12.3
- Node.js version: NA
- npm version: NA
- Platform/OS: NA
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by iskerrett** [comment]
I am curious what is the expected behaviour of clicking the 'here' link? If I click it, I am sent to the Billing Payment page.

**Comment by ZJvandeWeg** [comment]
@knolleary @joepavitt Should this also be on the billing page, instead of the settings?

**Comment by ZJvandeWeg** [comment]
Agree that the design was too feature rich to be practical for engineering in an MVP.

@MarianRaphael would be nice to reopen the linked issue?
