### ISSUE TITLE
Allow new users to be created on first SSO logon

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#2919]
### Description

**As a** FlowFuse Admin 
**I want** to enable new users to be created on first login via SSO
**So that** I do not need to pre-create new users in FlowFuse with a matching email address

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
A very high level description of how this could work and what open questions we'd need to address:

 - Add an option to the SSO config option to enable user-provisioning
 - When a user logs in for the first time, we need to see what profile information we are able to get via SAML to populate the user object in our database. I suspect this could end up being fairly provider-specific...
 - There is then the decision of what team to put them in. If the 'auto-create team on sign-up' option is enabled (as we do in FF Cloud), we *could* treat this the same. However, if an org has setup SSO with us, it's unlikely they want each user to be put in a new Trial team. This suggests the SSO config needs to include nominating a default Team that new users should be added to.
 - Related to the above is #2829 which is about getting a user's team membership via the SAML config. There are lots of open questions about how that would work.

**Comment by hardillb** [comment]
Just a thought I forgot to add, we may not need to enable this on ff-cloud, it may be of more use to self hosting deployments.

**Comment by knolleary** [comment]
Complete via https://github.com/FlowFuse/flowfuse/pull/4207
