### ISSUE TITLE
Layout difference between creating application+instance vs creating an instance

### ISSUE THREAD

**Issue by Yndira-FlowForge** [FlowFuse/flowfuse#2920]
### Current Behavior

When creating an application `/applications/create`, whenever presented three options to choose from, let's say in the type of instance section, it will present a single option in the first row, and the other two in the second row:
<img width="599" alt="Screenshot 2023-10-10 at 19 05 49" src="https://github.com/FlowFuse/flowfuse/assets/129537638/8e3e9458-6e95-413e-babc-7a1ce722bedd">

However, if the application has been created, and the instance is being created through `/instances/create`, then it presents it in the expected way, two options in the first row, and one in the second:
<img width="606" alt="Screenshot 2023-10-10 at 19 06 11" src="https://github.com/FlowFuse/flowfuse/assets/129537638/2d8d9324-e794-4a78-80cf-61fba509d1f1">

### Expected Behavior

When presenting three options, the first two should be displayed in the first row, and the last one in the second, like this:
<img width="606" alt="Screenshot 2023-10-10 at 19 06 11" src="https://github.com/FlowFuse/flowfuse/assets/129537638/2d8d9324-e794-4a78-80cf-61fba509d1f1">

### Steps To Reproduce

Create an application `/applications/create`
Create a new instance for that application through `/instances/create`

### Environment

- FlowFuse version: v1.12.3
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by knolleary** [comment]
Figured out the cause - https://github.com/FlowFuse/flowfuse/pull/2836

In the Application Create page, we made it optional to also create an Instance. In doing so, the Instance options are indented. This is squashing the horizontal space available for the selection tiles and causing a different wrapping behaviour.

As for the fix... that'll need some poking to work out.
