### ISSUE TITLE
Page Not Found 404

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/flowfuse#2929]
### Current Behavior

1. Select an application
2. Attempt to go back to applications via the three lines. I call it a hamburger and then click applications.
3. Displays 404

### Expected Behavior

I expect it to return to Applications Page.

### Steps To Reproduce

See Current behavior

### Environment

- FlowForge version: v1.12.3
- Node.js version:
- npm version:
- Platform/OS: Windows
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by knolleary** [comment]
To remove any uncertainty, can you grab a screenshot to show exactly what you're clicking on?

**Comment by gdziuba** [comment]
https://github.com/FlowFuse/flowfuse/assets/8887166/4ad8dbb7-0b94-4883-9e09-5164820b4c9b

**Comment by Pezmc** [comment]
I believe it's this issue: https://github.com/FlowFuse/flowfuse/issues/2934
