### ISSUE TITLE
Flow Blueprints: Admin UI improvemenets

### ISSUE THREAD

**Issue by Pezmc** [FlowFuse/flowfuse#2945]
Follow up to #2929 as part of https://github.com/FlowFuse/flowfuse/issues/2872

Need to look at the validation of the Flows object. In the database, we store it as:
```
{
    flows: [ usual array of nodes ],
    credentials: { object of credentials }
}
```

If some exports a flow from the editor, they just get the `[ usual array of nodes]` bit - and pasting that in here would be invalid.

I think the UI could provide a bit more help here to avoid an unexpected error if they get that format wrong.

I suggest splitting the Flows box into two - Flows and Credentials. And doing the work to split them apart/recombine in the expected format.

_Originally posted by @knolleary in https://github.com/FlowFuse/flowfuse/issues/2923#issuecomment-1761077094_

**Comment by joepavitt** [comment]
Closed by #3887
