### ISSUE TITLE
Update Blueprint selection UI as per designs

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#2948]
We've shipped the MVP of Blueprints that allows a simple selection to be made as part of the Create Instance form.

This UX will not scale beyond 3 or so blueprints - the more blueprints we add today, the worse the UX will become.

Designs were prepared in #2828 for a more scalable solution with much better UX that we should commit to as soon as we plan to go beyond a small number of Blueprints.

There did remain an open UX question on the design around the interaction between the blueprint selection screen and the CreateInstance form - that will need resolving before this can be implemented.

Addition from @MarianRaphael 
## User Story
As a FlowFuse user,
I want to easily access and view a comprehensive list of all available blueprints,
so that I can efficiently identify and select the one that best suits my specific needs without unnecessary delay.

## Design
<img width="1163" alt="270637154-fbd868d8-026e-4247-9f75-8448253bfd9c" src="https://github.com/FlowFuse/flowfuse/assets/73583313/cc56de9a-5f4e-461a-b3d5-77a6798bb3ad">

### Overview Page

- Image 
- Title
- Description
- Category

### Instance creation page

- "Blank Blueprint" is still pre-selected.
- A button linked to the overview page allows the user to change the blueprint from the overview page.

## Not in Scope (potential follow-ups)

- Filter
- Category icons
- Preview function

**Comment by Pezmc** [comment]
For this to be considered complete, https://github.com/FlowFuse/CloudProject/issues/308 must be completed as part of the release.

**Comment by knolleary** [comment]
We have now shipped the next iteration of this that largely aligns with the designs above. I'm going to close this issue as complete.

Any further features can be raised as additional items and added as tasks to #2828
