### ISSUE TITLE
Generate public catalog of FlowFuse recommended nodes

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#2951]
### Description

Via #2759 and #2809 we plan to host a private npm registery and create a corresponding catalog for its contents.

As a smaller first iteration, this task is to create a public catalog of nodes that FlowFuse recommends. These will still be hosted on public npm - we won't be taking on any maintenance responsibility.

The catalog will be public and pre-configured in any FF hosted instance.

### Proposed solution - MVP

1. Create a repository to host the catalog.
2. Within the repo, have a text file listing the nodes to include in the catalog
3. Create a GH workflow that periodically pulls the Node-RED public catalog and filters it for the nodes in our list.
4. Generate our catalog and commit back to the repo - use gh-pages to serve the catalog

Once that exists, we need to look at how to include the catalog by default. For FF Cloud we can update the Template to include in the list of custom catalogs. For self-hosted, we should update the default template to include it - but may need something more for existing installs to pick it up (as they will already have their Template created).

### Future

1. Add tasks to the workflow to do automated scanning of the modules (vulnerability scanning, other tasks tbd) and generate a report

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
- [x] create repo (https://github.com/FlowFuse/ff-catalogue)
- [x] write tool
- [ ] setup github action
- [ ] setup github pages

**Comment by hardillb** [comment]
https://catalog.flowfuse.com/catalogue.json

**Comment by MarianRaphael** [comment]
See for the definition of "certified nodes": https://github.com/FlowFuse/flowfuse/issues/1901

**Comment by MarianRaphael** [comment]
I suggest adding to the catalogue our template. https://github.com/FlowFuse/CloudProject/issues/279
