### ISSUE TITLE
FlowFuse PAT for Node-RED Http Endpoints

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#2964]
### Description

As a FlowFuse User
I want to use the FlowFuse access tokens (PAT) to access my Node-RED HTTP endpoints, which are secured with "FlowFuse User Authentication"
So that I can securely access my HTTP endpoints even with SSO enabled.

### Which customers would this be availble to

Licensed Edition (EE)
Team

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Follow-up
- [ ] https://github.com/FlowFuse/flowfuse/issues/2703
```

**Comment by knolleary** [comment]
Increasing the sizing as this is potentially quick tricky to get right.

**Comment by robmarcer** [comment]
An alternative  would be to allow a team to CRUD a list of tokens (seems like a pretty standard feature for various other platforms I use) which can then be used to protect their APIs. It would need to be on a per-instance basis. I think if all things are equal, putting it in HTTP Node Security would be a slightly better solution than using the FF PATs.

https://d.pr/i/rkp9Lw

**Comment by robmarcer** [comment]
We have a customer who has specifically requested the ability to issue tokens to protect APIs.

**Comment by knolleary** [comment]
@robmarcer if there's a requirement for per-instance tokens, then doing this via our existing access tokens wouldn't be appropriate (because they are tied to the user). So you are right to say having some instance-specific token capability would be needed.

There is also the issue that we currently don't have the ability to reduce the scope of a token - so you effectively have to provide full access to your FF account. We've already had feedback on that - see #2703 for enabling reduced-scope tokens.

To summarise:

 - Option 1: Allow existing User PATs to secure HTTP endpoints
    - Pros: we already have PATs
    - Cons: they are user-scoped, so would apply to *all* instances by default
    - Cons: leaking of the token gives *full* access to the whole FF user account, not just the individual instance.
    - Mitigation: provide a way to reduce scope of a token - potentially only specific instances. I would be super uncomfortable shipping this without the ability to reduce the token scope first.

 - Option 2: Allow user to create 'instance' tokens to secure HTTP endpoints
     - Pros: specific to an instance
     - Cons: another set of tokens to manage (although we have all the bits in place to do it)

**Comment by MarianRaphael** [comment]
@robmarcer I want to better understand the customer requirements. Is it about a general way to secure the HTTP endpoints, or is a more granular approach (per instance) requested?

**Comment by knolleary** [comment]
@hardillb Marian and I did discuss this a couple weeks ago, but failed to capture the outcome. I would like @MarianRaphael to confirm, but Option 2 (new instance-specific tokens) is my preferred route as the risk of exposing full access to significant.

That said, I can see that #2703 has also been scheduled - which is a prereq if we take Option 1.

In terms of overall development cost:
 - option 1 will require #2703 - and that needs more design work around how we reduce the scope of a token both technically and in the UI.
 - option 2 requires a 'new' type of access token - but at this stage, we have well-established patterns for doing that and can reuse much of the UI used by user access tokens.

On balance, I'd say option 2 is actually the easier route to take.

Both approaches will need to also figure out how to modify the adminAuth setup in the launcher to allow the tokens to be used. Whilst we confirm the choice of opt1/opt2, you could certainly make a start on this part of the problem.

**Comment by hardillb** [comment]
@knolleary why does this need to impact the `adminAuth` section? I thought this was targeted at things mounted on the `httpNodeRoot`?

**Comment by knolleary** [comment]
@hardillb yep, mistyped - it's the node auth middleware  stuff in the launcher.

**Comment by hardillb** [comment]
Do we want to add some level of token cache in the middleware to reduce load on the Forge app?

If so how long?

**Comment by joepavitt** [comment]
What's the ETA on this @hardillb?
