### ISSUE TITLE
Update Setup Billing page to offer Team Type selection

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#2970]
Part of #2905

The purpose here is to improve the UX around conversion from Trial to paid user.

When a user signs up, they get a Starter Team in Trial mode. They are directed to the Team Billing page where they are invited to go add their details in stripe. With the work delivered in #2963, this results in their trial ending.

This issue is to update the Team Billing page for a Trial Mode user to offer a selection of the available Team Types before going to stripe. This would allow a Trial mode user to go straight to the Team/Enterprise tier, rather than it being a two-stage process (set up billing, *then* change team type).

I've copied in below input from @joepavitt on the design for this particular aspect.

The Description of the team tiers is currently optimised for the tile selection display which is limited in space. We could stick with that for a first iteration, or if we want the larger scale display, we need to consider how that impacts the existing 'change team type' view.

---

_The following originally posted by @joepavitt in https://github.com/FlowFuse/flowfuse/issues/2328#issuecomment-1624032062_

Quick thoughts based on https://github.com/flowforge/flowforge/issues/2328#issuecomment-1612963139 (note the empty state graphic will be updated to reflect the page, just put that in as a placeholder), where the rows in the plan options would be driven by what they're using right now in their Team, e.g. in this example we have 2 x Team Members, 1 x Instance and 2 x Devices.

"Upgrade to _Tier_" options would then go to Stripe.

### Figma Prototype

https://www.figma.com/proto/rMB2w5ZZUtTC0nxbwLYKJY/FlowForge-Platform?page-id=0%3A1&type=design&node-id=2493-18259&viewport=-7845%2C-5052%2C0.74&scaling=min-zoom&starting-point-node-id=2493%3A18259&show-proto-sidebar=1&mode=design&t=DhF8dJvDse2TG530-1

### Static Screenshots:

<img width="1705" alt="Screenshot 2023-07-06 at 18 13 55" src="https://github.com/flowforge/flowforge/assets/99246719/6937f37f-5cd2-487f-9b85-c80684fb545f">

<img width="1682" alt="Screenshot 2023-07-06 at 18 14 01" src="https://github.com/flowforge/flowforge/assets/99246719/e1d382fc-56c1-45d5-9f6d-94b02f3954a1">

**Comment by knolleary** [comment]
Via #3092 the billing setup workflow has been updated. However the team type selection via still uses the original TileSelection component which doesn't match the ideal designs.

Closing this issue as the workflow has been improved. Will raise a separate issue to address the design of the TeamType selection page itself.

**Comment by Pezmc** [comment]
Verified: I was able to change team type back and forth on staging.

![Image](https://github.com/FlowFuse/flowfuse/assets/507155/e9eb03d1-bf45-4187-bd9a-1d40fd19fbe5)
![Image](https://github.com/FlowFuse/flowfuse/assets/507155/92346c1d-b147-4d3a-a5a8-8069e93a8a22)
