### ISSUE TITLE
NodeJS 18 based stacks

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#2975]
### Description

Since NodeJS 16 is now EoL we should make NodeJS 18 stacks available on FlowFuse Cloud

Should these be in addition or should we just update the standard stacks?

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by MarianRaphael** [comment]
I thought we updated the Node-RED 3.1 Stacks to Node.js 18?
See https://github.com/FlowFuse/flowfuse/issues/2181

**Comment by hardillb** [comment]
The beta of 3.1 was at 18, but the production is 16. See the comment on the change

**Comment by MarianRaphael** [comment]
I wasn't aware we switched back to 16 after the beta. Nevertheless, I would suggest migrating to Node.js 18 for 3.1 (and all subsequent stacks), even if that could break existing instances that have nodes not supporting 18. The workaround here would be the 3.0.2 stack.
