### ISSUE TITLE
Show the security settings applied to a NR instances in info

### ISSUE THREAD

**Issue by robmarcer** [FlowFuse/flowfuse#2976]
### Description

As a FF user who is building Dashboards or APIs,

I want to clearly see what HTTP security settings I have applied to an instance,

to reduce the possibility of accidentally leaking sensitive information online.

![screenshot_2023-10-18_at_10 54 18](https://github.com/FlowFuse/flowfuse/assets/92092324/66a96f30-9640-4962-bdbd-0d15f5568b7b)

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by hardillb** [comment]
Verified on Staging
