### ISSUE TITLE
Context delete audit log missing image and text

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/flowfuse#2983]
### Current Behavior

![Screenshot 2023-10-20 at 10 56 50](https://github.com/FlowFuse/flowfuse/assets/2529595/1122ac09-8a4d-4cd1-aa1e-9742fd8bf4a0)

### Expected Behavior

An image, and description that persistent? context was cleared

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
Duplicate of #2840 

FOA of @MarianRaphael

**Comment by Steve-Mcl** [comment]
Closed by https://github.com/FlowFuse/flowfuse/pull/3078
