### ISSUE TITLE
Quick Start Guide for Deploying Agents

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/flowfuse#3022]
### Description

Build a streamlined process for deploying agents.  

Includes the following:

- [x] Installation
- [x] Device Addition
- [x] Configure Device
- [x] Link Device
- [x] Develop on Device
- [x] Snapshots

**Comment by joepavitt** [comment]
Step 2 of "Configure Device Agent" I think needs to reference the `--ui-port` option in some way, to make it clear that's where the `8081` has come from

**Comment by joepavitt** [comment]
Step 2 in "Link Device to Application" and Ste; 3 of "Enabled Developer Mode" both say _Locate your Device_, however they actually require slightly different actions.

For the first instance, they're clicking the three-dots on the given row their Device is available, still in the "Devices" page.

For the second instance, they need to click the row first, then, they'll the Developer Mode options in the top-right.

**Comment by joepavitt** [comment]
Otherwise, this is excellent. Much cleaner than what we have, and easy to follow.

**Comment by gdziuba** [comment]
> Step 2 of "Configure Device Agent" I think needs to reference the `--ui-port` option in some way, to make it clear that's where the `8081` has come from

I linked to the documentation just below.

**Comment by joepavitt** [comment]
> I linked to the documentation just below.

Step 2 of "Configure Device Agent", not the first section of "Install Device Agent Software"

**Comment by gdziuba** [comment]
> > I linked to the documentation just below.
> 
> Step 2 of "Configure Device Agent", not the first section of "Install Device Agent Software"

Gotcha.  Yes.  I will add context.

**Comment by gdziuba** [comment]
@joepavitt 

Edits completed.

[Pull request here ](https://github.com/FlowFuse/flowfuse/pull/3016)

![image](https://github.com/FlowFuse/flowfuse/assets/8887166/61baaf64-971b-4ca4-94eb-196cbcfd841c)
