### ISSUE TITLE
Improve discovery/visibility and strengthen association with Node-RED

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#3059]
### Description

_Similar to recent raised issue "Node-RED does not appear in popular topics related to FBP / Visual Programming" on the Node-RED repository._

Browsing low-code / flow based projects on GH I noted that Node-RED and FlowFuse do not feature in prominent GH topics:

https://github.com/topics/low-code
https://github.com/topics/no-code
https://github.com/topics/visual-programming
https://github.com/topics/flow-based-programming

I propose we add the following keywords to make stronger associations with Node-RED and improve discoverability:

```
    "keywords": [
        "visual-programming",
        "flow-based-programming",
        "no-code",
        "low-code",
        "low-code-platform",
        "low-code-development",
        "low-code-development-platform"
    ],
```

Additionally, a strong graphic should accompany our project to make it stand out like other platforms

e.g:

### Node-RED
![image](https://github.com/FlowFuse/flowfuse/assets/44235289/70187951-4514-4271-a9b1-8eb57377f1c6)

### Others
![image](https://github.com/FlowFuse/flowfuse/assets/44235289/58b8d8ca-a301-404b-adce-973b90b8eca9)

---

Discussed here: https://flowforgeworkspace.slack.com/archives/C021LKE5EAY/p1699085711757419

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
And this is the rather lacklustre view people see if they manage to spot FlowFuse while browsing the label `low-code` 

![image](https://github.com/FlowFuse/flowfuse/assets/44235289/ed5707c7-25f7-46e9-9407-a65b13258e5a)

👆 This tells me absolutely nothing (though I can infer from the "low-code" tag is has _something_ to do with low-code)

<br>

Below are some better examples with only a handful more stars...

![image](https://github.com/FlowFuse/flowfuse/assets/44235289/9f33a251-673f-419d-8de0-b5ee8cfcfefa)


---

Instructions on how to set this up: https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/customizing-your-repositorys-social-media-preview

**Comment by Steve-Mcl** [comment]
In addition to the graphic, we should in some way describe what we offer in the "About" section.

Currently, it states "The FlowFuse Platform" 🙄 
![image](https://github.com/FlowFuse/flowfuse/assets/44235289/5c16a4a8-a146-4d27-8b88-2fd218c18e53)




Taking the lead from out current motto on the FlowFuse home page, I suggest we update the "About" section to say something along the lines of **"Build bespoke, flexible, and resilient manufacturing low-code applications with FlowFuse and Node-RED"**


![image](https://github.com/FlowFuse/flowfuse/assets/44235289/698b1d5d-9a64-492e-b326-5c3d98496ca3)

**Comment by Steve-Mcl** [comment]
Re-opening until image is added and the "About" section are improved.

**Comment by Steve-Mcl** [comment]
> Taking the lead from out current motto on the FlowFuse home page, I suggest we update the "About" section to say something along the lines of **"Build bespoke, flexible, and resilient manufacturing low-code applications with FlowFuse and Node-RED"**
> 
> ![image](https://user-images.githubusercontent.com/44235289/283164918-698b1d5d-9a64-492e-b326-5c3d98496ca3.png)

@ZJvandeWeg is this something you can do?

**Comment by knolleary** [comment]
@Steve-Mcl I've updated the repo description.

**Comment by Yndira-FlowForge** [comment]
Hi, here's the image: https://github.com/FlowFuse/website/issues/1322#issuecomment-1814834629

**Comment by ZJvandeWeg** [comment]
@Steve-Mcl @knolleary I did it just know, let me know if the result is not what you hoped it would be.

**Comment by Steve-Mcl** [comment]
@ZJvandeWeg perfect imho...

![Screenshot_20231116-191930](https://github.com/FlowFuse/flowfuse/assets/44235289/ee9cd467-d505-4782-ba05-83922e1ca553)


If you and Nick are happy too, please close the issue

**Comment by ZJvandeWeg** [comment]
@knolleary consider adding a social tile for Node-RED too

**Comment by knolleary** [comment]
Done 
<img width="771" alt="image" src="https://github.com/FlowFuse/flowfuse/assets/51083/7414db2f-5bdb-4e2f-bd22-17e059d9f1eb">
