### ISSUE TITLE
Missing/error in documentation for migration & templating

### ISSUE THREAD

**Issue by hyamanieu** [FlowFuse/flowfuse#3082]
### Description

There are missing information in the documentation:

- in https://flowfuse.com/docs/upgrade/ , it's missing the "details of how to upgrade". I believe this subsection should be removed from all "Upgrading to x.x" sections, and simply be the first "general" section, while pointing the administrator to specific changes in specific updates in the following sections.
- In https://flowfuse.com/docs/install/docker/#upgrade:
  - it's missing information on comparing etc/flowforge.yml besides docker-compose.yml
  - it would be ideal to add the full CLI to do some of the things: `wget` of the latest tar, `tar -xzvf`, etc
  - of course the best would be to find a way to make a script, but I guess the folder structure may need to be changed.

I have found also a mistake:
- in https://flowfuse.com/docs/user/filenodes/#enabling-persistent-file-storage : `10-file-js` should be replaced by `10-file.js`

**Comment by hardillb** [comment]
@hyamanieu Thanks for raising this.

I've fixed the typo in the file nodes doc and we can look at improving the upgrade docs for Docker. If you have suggestions please feel free to open a PR against the docs, they are all hosted in this repo under the `docs` directory.

**Comment by hyamanieu** [comment]
Thanks for merging @knolleary , i'm closing this issue.
