### ISSUE TITLE
Pipeline stage permits action "Create new snapshot"

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#3109]
### Current Behavior

Possible to have a Stage Type "Device" with action type "Create snapshot"
![chrome_oxljfS7SJm](https://github.com/FlowFuse/flowfuse/assets/44235289/ab92f864-655b-4b81-8883-d3524161f275)

### Expected Behavior

Dropdown should NOT include "create snapshot" when the stage type is "device"

### Steps To Reproduce

* Select stage type instance
* choose item "Create Snapshot" in the "select action"
* Select "stage type" "device"

You will see the "select action" dropdown keeps the invalid choice "Create Snapshot"

### Environment

- FlowForge version: 1.13.x-git
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Pezmc** [comment]
Verified on staging.
