### ISSUE TITLE
UI Concept - RBAC for Instances and Devices

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3120]
Create a UI concept for the option to limit roles and the associated privileges for selected instances. One approach could be a selection screen where everything is preselected, allowing the possibility to deselect certain instances and devices.

## Scope

See #3093

**Comment by MarianRaphael** [comment]
Concept idea: User Groups within the Team

**Comment by MarianRaphael** [comment]
@Yndira-FlowForge, thank you for providing the list of different options. We agreed on Option Three, as mentioned in #3093. Could you create a draft design for this option?

**Comment by Yndira-FlowForge** [comment]
Hi @MarianRaphael @joepavitt
I'm using the Meta Business page as a reference. I think the equivalent would be adding an "Instance Access" tab inside the instance, or "Device Access", or "Device Group Access" where applicable.

![Instance](https://github.com/FlowFuse/flowfuse/assets/129537638/f4805b92-5e61-4d84-87aa-a3beb1ee6796)

I'm unsure about allowing editing the user role from these pages, and if we do, the modal should warn that this will affect the user role across all the platform. Because that would be the case, right?

Also, would we allow inviting a new member from these pages? Or only users that are already members of the team?

**Comment by MarianRaphael** [comment]
I think the top navigation bar is too "prominent" of a place. My suggestion would be to place it in a submenu under settings. The overall look is good.

**Comment by Yndira-FlowForge** [comment]
Ok, so it would be something like this:
![Instance](https://github.com/FlowFuse/flowfuse/assets/129537638/f52f6b3f-83b3-42d5-94b6-91a41ee4add7)


What about this?

> I'm unsure about allowing editing the user role from these pages, and if we do, the modal should warn that this will affect the user role across all the platform. Because that would be the case, right?

If we don't allow role editing, we could replace the three dots to the right with a single button to remove users from the list:
<img width="226" alt="Screenshot 2023-12-18 at 15 09 16" src="https://github.com/FlowFuse/flowfuse/assets/129537638/5935dcb8-e6a7-43ac-80ea-0207828fcbb5">

**Comment by joepavitt** [comment]
Differentiation needs to be regarding access to _this_ instance. Don't want confusion arising around a user thinking this button removes them from FF/Team entirely.

**Comment by Yndira-FlowForge** [comment]
@joepavitt What do you think about displaying all team members? This way is clear they're still part of the team, but you get a clear view of who does and doesn't have access to the instance.

![Instance RBAC](https://github.com/FlowFuse/flowfuse/assets/129537638/4a534392-2c53-4681-b237-6c018c81e9d9)

**Comment by joepavitt** [comment]
So, as things stand, all team members have access to all Instances. The only way a user would _not_ have access anymore is if someone, in this view, had explicitly removed access. As such, I agree with the concept of leaving those team members listed as "No Access" users in this view.

**Comment by Yndira-FlowForge** [comment]
Good point. We could keep the button in a disabled state and add a tooltip:
![Instance RBAC_tootlip](https://github.com/FlowFuse/flowfuse/assets/129537638/8c413465-5108-4b38-9c89-abb5c9b45784)

Alternatively, we could replace the button with text, which is more straightforward but not as visually consistent as the other option:
<img width="408" alt="Screenshot 2023-12-21 at 12 59 08" src="https://github.com/FlowFuse/flowfuse/assets/129537638/ad37d39d-6064-4621-b7bd-d3539a2c313e">

**Comment by MarianRaphael** [comment]
> I would also make a point that "owner" role always has access and cannot be removed. I think this functionality should be possible on "Members" only?

In general, I would agree that there should be a role that can't be removed. However, the issue I see here pertains to our specific customer example. In this scenario, certain users should have Owner roles for some instances (e.g., changing configurations, etc.) but not for others. The simplest solution would be to create an additional role above the current Owner rights or to transfer some functions from Owner to Member.

@Yndira-FlowForge I like the design!

**Comment by joepavitt** [comment]
> The simplest solution would be to create an additional role above the current Owner rights or to transfer some functions from Owner to Member.

Having Instance-specific roles is by no means "simple"

**Comment by MarianRaphael** [comment]
What I mean is to introduce a kind of Admin role, which differs from the Owner privileges only in that this role can't be removed from instance-specific access.
