### ISSUE TITLE
Device quick start "Linux" need update 

### ISSUE THREAD

**Issue by grawsom** [FlowFuse/flowfuse#3128]
### Description

Hi  - on https://flowfuse.com/docs/device-agent/quickstart/ under linux instructions there is some missing change.
It shows - npm install -g @flowfuse/flowfuse-device-agent
Should be - npm install -g @flowfuse/device-agent

**Comment by hardillb** [comment]
Hi,

Thanks for raising this, we have published the  v1.14.0 release to both packages so the instructions should still get the latest version, but the docs do need to be updated.

**Comment by hardillb** [comment]
Doh, just seen the difference.

Fixing
