### ISSUE TITLE
add new property to catalogue schema to show compatibility issues before installing a package

### ISSUE THREAD

**Issue by AllanOricil** [FlowFuse/flowfuse#3136]
### Description

Currently there is no way to determine if a package is or not compatible with the running node-red instance before installing it. User waits a few seconds before an error is displayed showing that the package's engine isn't compatible with the running node version.

To solve this issue I would like to add a new attribute to the catalogue's schema so that Users can see before installing engine compatibility issues:

````json
{
    ...
    modules: [
        {
             ...
             "engines": {
                 "node-red" : ">= 3",
                 "node" : ">= 18"
             }
        }
    ]
}
````

Then you can use this new `engines` attribute to render the catalogue entry with a label saying "incompatible" when either the running node-red, or node, version isn't compatible. You can also disable the "install" button. When hovering over the disabled "install" button, a message like the following is displayed: "node isn't compatible because $REASON"

![image](https://github.com/FlowFuse/flowfuse/assets/55927613/d07a167c-323e-4b74-9959-be63e78a61cd)

### Have you provided an initial effort estimate for this issue?

I have not provided an initial effort estimate

**Comment by hardillb** [comment]
The catalogue is entirely handled by Node-RED, there is nothing to change in FlowFuse here
