### ISSUE TITLE
Pipeline execution status for Device Groups

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3142]
## User Story
**As a:** FlowFuse User

**I want:**

1. To have an overview page for device groups that shows which devices are currently running the assigned target snapshot.
2. To receive notifications about the overall result of the deployment, including information about devices that are not responsive.

**So that:**

1. I can quickly and effectively understand the status of my assigned target snapshot across different devices in my fleet.
2. I have the transparency and information needed to take appropriate action regarding the deployment and management of my fleet.

## Acceptance Criteria

**Overview Page:**
- [ ] - The overview page should clearly display all devices within a selected device group.
- [ ] - Each device should be marked to indicate whether it is running the assigned target snapshot or not.
- [ ] - Devices that are not responsive should be distinctly marked for easy identification.

**Notification:**

- [ ] After the deployment of a snapshot, a notification should be sent to the user.
- [ ] This notification should summarize the overall result of the deployment, including the number of devices successfully running the snapshot and the number of non-responsive devices.

**Comment by Steve-Mcl** [comment]
My take: 

Perhaps the device browser component needs the ability to filter on a group and thus the pipeline stage with Device Group could "link to" the applications devices view with the group filter applied? (as opposed to another new view with 90% same functionality)

**Comment by joepavitt** [comment]
Could this also just show on our "Devices" tab for the Device Group view.

The "Device" and "Instance" in the pipeline stages are clkickable, it'll navigate you to their respective views. Device Groups should be the same.

Then, on the Device Group page, (defaulting to the "Devices" tab as discussed [here](https://github.com/FlowFuse/flowfuse/pull/3192#issuecomment-1853634711)) we include the target/active columns as per the existing Device Browser.

In "Edit" mode for a device group, we hide those columns, and swicth to the two-column layout we'd have now.

**Comment by MarianRaphael** [comment]
![Screenshot 2023-12-22 at 14 24 00](https://github.com/FlowFuse/flowfuse/assets/73583313/3718eaec-e963-456f-ab06-482f94eece47)
@MarianRaphael Reminder

**Comment by joepavitt** [comment]
We do have 1. already, although no async notifications of Pipeline status'
