### ISSUE TITLE
Icons for Device Groups

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#3145]
### Related Issue

https://github.com/FlowFuse/flowfuse/issues/2997

### Description

**Considerations:**
- Image for FlowFuse to symbolise "device groups"
- Usage in pipelines and table rows
  ![image](https://github.com/FlowFuse/flowfuse/assets/44235289/c8df3037-6ec0-403e-b950-a75381ee6fd2)
- Usage in About popovers
   ![image](https://github.com/FlowFuse/flowfuse/assets/44235289/39b1e016-1194-4b1e-aa36-5d6c81a47fb7)

**Inspirations:**
- Inspire me ;) 
- @joepavitt may have some ideas?

**Comment by Yndira-FlowForge** [comment]
Hi @Steve-Mcl 

I know you didn't request for the empty state, but Joe mentioned it and I think you'll need it, it would be [this one](https://drive.google.com/open?id=1Kt2hoEZN-QlTG4kFjB0M8Yq1YVeq3Glx&usp=drive_fs).

For the modal window, [this one](https://drive.google.com/open?id=1KxoQQgqBsTtTW8YBlheOXSBEhXvJBqPc&usp=drive_fs).

An the icon is in the figma file, [here](https://www.figma.com/file/rMB2w5ZZUtTC0nxbwLYKJY?node-id=3636:12502&mode=design#633288811). Let me know if you can grab it from there or if you'd rather me exporting it for you, I'm just not sure if you need it with the background or not.

**Comment by Steve-Mcl** [comment]
closed by https://github.com/FlowFuse/flowfuse/issues/2997
