### ISSUE TITLE
Redesigning the Applications Home Screen

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3152]
## Objective
Redesign the current Applications home screen to enhance user experience and functionality.

## Current Situation
The existing home screen only displays Instances, neglecting Devices and other functionalities offered by Applications.

![Screenshot 2023-12-01 at 16 06 07](https://github.com/FlowFuse/flowfuse/assets/73583313/b971f021-030a-4381-8190-ae08e9fb5a0f)

## Primary Goal:
Create a new Applications home screen that showcases both Instances and Devices prominently, treating them as equals.

## Key Requirements:

- Equal Visibility: Ensure Instances and Devices are equally visible and accessible from the home screen.

- Holistic Overview: The design should provide a comprehensive overview of an Application's functionalities, including but not limited to Instances and Devices.

- User-Friendly Interface: The interface should be intuitive, allowing users to easily navigate and access different functionalities.

**Comment by joepavitt** [comment]
Not a fan of the grey - but I understand (and agree with) the incentive. How does this view look with several hundred devices? That's our bigger challenge here.

Try to think completely from fresh, ignore what we have now - what would you design? How would you layout that information?

**Comment by MarianRaphael** [comment]
> Not a fan of the grey 

Me neither

> we could instead have the concept of "Favourites"

I like the idea of having favorites for each user, but I believe this is a separate issue. This provides a more comprehensive/addtional overview.

**Comment by MarianRaphael** [comment]
What I really like, and think is useful, is this overview:
![Screenshot 2023-12-20 at 14 16 00](https://github.com/FlowFuse/flowfuse/assets/73583313/4693bc43-2865-4ad1-a94e-996283564c6a)

**Comment by joepavitt** [comment]
<img width="1807" alt="Screenshot 2023-12-20 at 14 50 40" src="https://github.com/FlowFuse/flowfuse/assets/99246719/84030b4d-80a2-414c-b9cd-5d678be90d39">

A quick play to try something different

**Comment by MarianRaphael** [comment]
I like the look :) 

I think my questions here are:
1. How would the screen look like without favourites?
1a. Would there be a dropdown with all Instances/Devices?
1b. A normal list of instances, and if there are more than 5? Does it become a dropdown?
3. How to choose favourites?
4. Is "Open Editor" for Devices always visible or only in Dev mode?

**Comment by joepavitt** [comment]
> 1. How would the screen look like without favourites?

We'd pick the most recently created Instances/Devices. I'd probably favour instances for the reason that Editors are available.

> 1a. Would there be a dropdown with all Instances/Devices?

I'd say, no. That's two clicks to an Instance/Device. Each of the tiles here would be a link to the respective tab at the Application level. Two clicks to an Instance/Device this way already, and means we have no worries about pagination if hundreds of devices.

> How to choose favourites?

Haven't thought that far ahead yet - I suspect a "favourite" button in the top-right of each Instance/Device page as a first iteration.

> Is "Open Editor" for Devices always visible or only in Dev mode?

Good point, this was just a quick copy/paste job, so hadn't considered that, but yes, Open Editor only available in Dev Mode.

**Comment by joepavitt** [comment]
Some more variations: 

<img width="1822" alt="Screenshot 2023-12-22 at 14 33 39" src="https://github.com/FlowFuse/flowfuse/assets/99246719/e416b9ae-afff-4d7b-9e3f-da9d56ece0ce">

<img width="1800" alt="Screenshot 2023-12-22 at 14 33 52" src="https://github.com/FlowFuse/flowfuse/assets/99246719/ff6289c7-97b1-41f9-b6f4-530629042e93">

<img width="1797" alt="Screenshot 2023-12-22 at 14 33 46" src="https://github.com/FlowFuse/flowfuse/assets/99246719/23441835-ae82-421e-ae35-606b5a8f408e">

**Comment by MarianRaphael** [comment]
@joepavitt, visually, I like the first option the most.
@Yndira-FlowForge, could you draft a design for 'How to Choose Favorites'?

**Comment by joepavitt** [comment]
> visually, I like the first option the most.

That does need some refinement as the sizing of the three elements (icon, number and label) are off at the moment.

**Comment by Yndira-FlowForge** [comment]
> could you draft a design for 'How to Choose Favorites'?

I'll give it a go

**Comment by GogoVega** [comment]
Nice 😍 

I hesitate between 1 and 3 of this [message](https://github.com/FlowFuse/flowfuse/issues/3152#issuecomment-1867755813) (as the goal of the icon summary is to have the number and to be able to access them more quickly, 2 is too big). I mean when I click on "X Instances" it's like I click on the application then "Instances" tab.

The idea of the favorite is interesting (I really like it)

> How to choose favourites?

When you are in instances or devices - on the left (in front of the NR icon - or on the right) a star icon

<img width="1010" alt="Capture d’écran 2024-01-10 à 15 35 47" src="https://github.com/FlowFuse/flowfuse/assets/92022724/17060775-ecab-46cd-9faa-c2a4cb46612c">

> How would the screen look like without favourites?

max 5, the last ones created
We can add logic - if an instance is in error (or something else requiring attention) it goes to the top of the list (that would be the best 🤓 )
Do we apply this logic with favorites? This would give a list of 5 favorites plus the instances requiring attention.

How many favorites at most? 5 too?

> Is "Open Editor" for Devices always visible or only in Dev mode?

"Open Editor" if dev mode enabled, otherwise "Enable dev mode" option may be more useful than "Open Editor" disabled

> Would there be a dropdown with all Instances/Devices?

A 6th option would be "see all" the equivalent of clicking on the application

One last suggestion: as Steve said, `Pipeline` doesn't speak to everyone, I prefer `Automation`

**Comment by joepavitt** [comment]
Variation of Option 3, with the icons right-aligned:

<img width="1104" alt="Screenshot 2024-01-11 at 14 39 03" src="https://github.com/FlowFuse/flowfuse/assets/99246719/9b0e70be-471b-444d-ae38-1ac813c42969">

**Comment by Yndira-FlowForge** [comment]
Using latest design from Joe, thinking about how this could look when no favorites have been selected, we could implement one of these:
- We list the three most recent instances and devices and display a prompt providing guidance on what is being displayed and how to customise it.
- This separation would only occur in this state, after they pick their favorites, the list will be a mix with all favorite devices and instances.
![Team _ Applications-1](https://github.com/FlowFuse/flowfuse/assets/129537638/8e2feaee-03eb-427a-8827-7dc8caf77746)


- A variation of that one with a gradient on top of the last one, indicating that there are more items in each list, but they're not being displayed. And this will only be present if no favorites have been selected. 
![Team _ Applications](https://github.com/FlowFuse/flowfuse/assets/129537638/0f61efa4-bb3e-44a2-a475-96d2b9ff413f)

**Comment by Yndira-FlowForge** [comment]
And for selecting favorites, it could be like this:

**Instances**
![Application - Instances](https://github.com/FlowFuse/flowfuse/assets/129537638/25461b4e-03a4-491d-bef8-3da23ebc2f1b)

**Devices**
![Application - Devices](https://github.com/FlowFuse/flowfuse/assets/129537638/afc1ebb9-0c95-4db7-8976-2bc629e7afc1)

**Comment by GogoVega** [comment]
I think Joe's alignment is clean, it looks good.

For the selection of Yndira's favorites, perfect, exactly the idea I had.
The gradient makes me want to scroll, maybe that's not the goal wanted.

Do you have any comments on my other suggestions?

**Comment by GogoVega** [comment]
I thought of another suggestion: would it be possible to change the order of apps (reorganize)? Ideally in the same way as GitHub. Do the same for favorites?

**Comment by joepavitt** [comment]
>  Ideally in the same way as GitHub

To check here, this is done by "last modified", right? With Favourites being prioritised?

**Comment by GogoVega** [comment]
I mean an icon (see below) which appears (may not be necessary to hide it) and which allows to move the order of applications.

The icon:
<img width="24" alt="Capture d’écran 2024-01-16 à 12 33 05" src="https://github.com/FlowFuse/flowfuse/assets/92022724/82e46ed8-342a-4b69-99de-0b36d73888c0">

 I would see him on the left of the app icon.
<img width="1018" alt="Capture d’écran 2024-01-16 à 12 38 51" src="https://github.com/FlowFuse/flowfuse/assets/92022724/9c7380ca-a862-44d6-90ba-e563cd3a0282">

The orange square - sorry it's not visible well

> With Favourites being prioritised?

I don't know if a favorite is necessary for apps 🤔

**Comment by joepavitt** [comment]
Closing as work is underway and designs for the home screen had been finalised
