### ISSUE TITLE
Optimizing Instance Startup Time

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3171]
### Description

This epic focuses on identifying and implementing strategies to reduce the startup time of our instances. The current startup duration of approximately 3 minutes, impacting user satisfaction. The objective is to streamline the startup process, implement performance enhancements, and optimize system configurations to significantly reduce this time.

```[tasklist]
### Tasks
- [ ] Remove preassigned npm modules
```

**Comment by knolleary** [comment]
See also https://github.com/FlowFuse/flowfuse/issues/3058 for one area we can improve

**Comment by joepavitt** [comment]
Duplicate of #3529 (where there has been more discussion about this)
