### ISSUE TITLE
Project Stack: Enhancement of CPU Quota for Project Stack

### ISSUE THREAD

**Issue by elenaviter** [FlowFuse/flowfuse#3174]
### Feature request
Enable Multi-Core CPU Support for Node-RED Projects

### Detailed Explanation
Currently, our project stack is limited to a maximum CPU quota of 1 CPU per instance. 
This limitation is reasonable based on fact that Node is single core. 
However, this limitation restricts the potential of integrations, e.g. side applications, particularly for Node-RED projects which are capable of running multiple processes concurrently (as processes can be defined in flows and custom nodes). 
By allowing the allocation of more than one CPU to a project, we can significantly enhance the processing capabilities and overall coverage of hybrid solutions.

### Reasoning:
Node-RED's ability to spawn/exec the processes from both flows and custom nodes presents an opportunity to optimize performance through multi-core processing. 
Removing the current single CPU constraint will enable the pod running a project to fully leverage multicore architectures. This enhancement is not just a boost in processing power; it is a step towards unlimited amount of new integrations, right in the Node-RED flows.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
Hi,

This seams sensible. The limits are enforced in the regex used to validate the values when entered in the stack definition, which are set in the k8s/docker container drivers.

https://github.com/FlowFuse/driver-docker/blob/77ef5ad8b14b06e6ee59fe7e2c3842f8540f0bf3/docker.js#L208
 
https://github.com/FlowFuse/driver-k8s/blob/2e3a51da183c62adbfbdd2882c88751812239206/kubernetes.js#L699

If you want to open a PR to soften this validation we can look at it.

**Comment by elenaviter** [comment]
Hi, @hardillb,

As previously mentioned, the two attached PRs (k8s and docker) introduce an enhanced CPU quota configuration for Projects, now accommodating up to a maximum of 10 cores. 
I have also updated the accompanying information texts to reflect these changes. 
Could you please review them at your earliest convenience? 

Thank you!

**Comment by hardillb** [comment]
Verified on Staging
