### ISSUE TITLE
Creation of Device Groups during Pipeline creation

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3183]
Based on the last week's discussion around Device Groups, this is in imo still the natural UX workflow for a user.

## User Story

As a FlowFuse User,
I want to directly create a Device Group during the pipeline creation process,
So that I do not have to jump back to the application screen while creating a pipeline for my devices.

## Objective

Enhance the user experience and streamline the process of creating DevOps pipelines in FlowFuse by integrating the functionality of creating Device Groups directly within the pipeline (stage) creation workflow.

Users should be able to create a new Device Group without leaving the pipeline creation interface. This feature should be accessible at the point where users are selecting or associating device groups with the pipeline.

## Scope

- [ ] A link to the Device Group creation page, while creating a Pipeline

**Comment by Pezmc** [comment]
![Screenshot 2024-01-11 at 14 19 00](https://github.com/FlowFuse/flowfuse/assets/507155/5fac5a74-7ef2-489e-99e4-f581b4ae09d9)

My quick win for this is as above, the user will still need to go to the group after creation to add devices, but it removes the need to pre-seed groups _before_ creating pipeline stages. Given @MarianRaphael is out, do you have a few moment to give thoughts @joepavitt?

**Comment by joepavitt** [comment]
I agree with @Pezmc on the contradictory nature of the scope vs objective. 

My own personal opinion is that I do not like the idea of being able to create a Device Group in a Pipeline screen, as it's over-configuration within this screen and cross-contaminates creations screens, i.e. you can now create a Device Group in the Pipelines screen, why can't you create Instances and Devices here too? It's unhealthy scope creep.

I do understand the merit of linking to the "Create Device Group" page as listed in Marian's Scope - so I'd say that was a first step (and quickest win) if we are to go down this route.

If we do persist with the idea of being able to create the full group here, then I can only really see a popup window being an option, with a list of all devices. Device Name at the top, then checkbox next to every Device in that dialog to define which groups go into the group?

**Comment by Pezmc** [comment]
> If we do persist with the idea of being able to create the full group here, then I can only really see a popup window being an option, with a list of all devices. Device Name at the top, then checkbox next to every Device in that dialog to define which groups go into the group?

I disagree here, on the Device Groups page, we offer the following, which is why I proposed the quick win above.

![Screenshot 2024-01-11 at 15 15 05](https://github.com/FlowFuse/flowfuse/assets/507155/16822b28-d368-401c-a3db-e6b14994b8b1)

If I understand the objective here, we're removing blockers to scaffolding out a pipeline. Allowing a user to create an empty group does that, they can then assign devices to that group, if they wish, _after_ creation.

**Comment by Steve-Mcl** [comment]
> ![Screenshot 2024-01-11 at 14 19 00](https://private-user-images.githubusercontent.com/507155/295926165-5fac5a74-7ef2-489e-99e4-f581b4ae09d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5ODM0NTIsIm5iZiI6MTcwNDk4MzE1MiwicGF0aCI6Ii81MDcxNTUvMjk1OTI2MTY1LTVmYWM1YTc0LTdlZjItNDg5ZS05OWU0LWY1ODFiNGFlMDlkOS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQxNDI1NTJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iOGQzZjg4ZTI5OWQ1MTM0MWE5ZDY0NjBkMjM3ZTNiNWUxOGI2ZDhlNDY3MmM4OTJmM2NkYzk4NmVhMWM5YzEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.5IVVKFtxrGPWsGntd85ey4_rTJgWlzfgjY40dxZTEM8)
> 
> My quick win for this is as above

I am wondering if the creation of the device group shouldn't just be a [New Group] button adjacent to the dropdown that pops up a dialog that creates the group in place (then refreshes the dropdown to permit choosing it) - using the same logic and same dialog (refactored) from the existing Device Groups page?

**Comment by joepavitt** [comment]
> If I understand the objective here, we're removing blockers to scaffolding out a pipeline. Allowing a user to create an empty group does that, they can then assign devices to that group, if they wish, after creation.

But eh user, either way, has to do the same amount of work. They still need to leave the Pipeline UX to go to the Device Group, then add Devices, then back to Pipeline to run the pipeline.

Their end goal is to push flows to a group of Devices, just enabling the creation of a Device Group (with no devices in it) doesn't help them get to that goal faster.

**Comment by knolleary** [comment]
> Their end goal is to push flows to a group of Devices, just enabling the creation of a Device Group (with no devices in it) doesn't help them get to that goal faster.

It may be the same amount of work, but they don't have to abandon one piece (creating the pipeline) because they discover they have to first go create a device group. Allowing them to create the device group (albeit empty) allows them to complete the current task, save the stage, *then* go populate the newly created device group. I think allowing them to complete the stage creation without having to context switch makes for a smoothing workflow - even if the workload isn't necessarily less.

**Comment by joepavitt** [comment]
But why not just link to the "New Device Group" screen, which offers the same workflow being proposed here, also allows them to add devices, and means we have no duplicated effort in creating device groups

**Comment by Pezmc** [comment]
To me:

Open Pipeline Screen -> Click create stage -> Choose device group -> Click link to device groups page -> Create group -> Open group -> Add devices to group -> Return to pipeline screen -> Click create stage -> Select new group 

is longer and involves more context switching than: 

Open Pipeline Screen -> Click create stage -> Select new device group -> Submit form creating stage & group -> Open group -> Add devices to group

**Comment by knolleary** [comment]
> I guess then, there is no Pipeline created actually. Understand. I don't like it, but I understand.

That's exactly the issue. Plus, if you navigate away from the pipeline stage form, you don't have a way to come straight back to where you were - you have to navigate all the way through the app to get back to the pipeline to restart adding the group.

@Pezmc the use case is to try to streamline the pipeline creation. I think your quick win is a good iteration to move in the right direction and you have my Okay to continue down that path.

**Comment by Steve-Mcl** [comment]
verified on staging

https://github.com/FlowFuse/flowfuse/assets/44235289/3778a1bc-fd6e-4371-a83f-1deac4728c86
