### ISSUE TITLE
Deleteing instance whilst on its logs view results in endless notifications

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#3191]
### Current Behavior

<img width="435" alt="image" src="https://github.com/FlowFuse/flowfuse/assets/51083/d0ada1ef-9d0d-4b01-80fc-2991803d7d53">

There were also a couple notifications with saying `slice is not a function` at the start - but they disappeared before I could screenshot.

### Expected Behavior

No unexpected notifications

### Environment

- FlowForge version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
This is not just a problem for deleted instances.

Once you've viewed the logs of an instance, that instance id is used for ALL subsequent polling of the logs endpoint, no matter if you navigate away to another instance and try and view its logs.

The initial bulk load of the logs is for the correct instance, but the timer always fires with with the first instance id.

**Comment by hardillb** [comment]
I think it is because vue-timer binds `this` to the callback

https://github.com/Kelin2025/vue-timers/blob/62dba038a36ec5ab5102836cff236a153d287d07/mixin.js#L57
