### ISSUE TITLE
Extend Trial Period

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3203]
### Description

Follow-up issue for: https://github.com/FlowFuse/flowfuse/pull/3138

As an Admin,
I want to have the ability to extend the trial period for a team,
so that teams can have additional time to test FlowFuse without the need for migrating to an unmanaged state or enter cc infos.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
Done via https://github.com/FlowFuse/flowfuse/pull/4052
