### ISSUE TITLE
404 toast accessing blueprints in CE mode

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#3220]
### Current Behavior

404 toast when visiting blueprints in CE modes

![chrome_zAASsuv2pU](https://github.com/FlowFuse/flowfuse/assets/44235289/26afa79e-f4fa-45a1-836d-efef6f0ffbf8)

![image](https://github.com/FlowFuse/flowfuse/assets/44235289/08aa87e7-681f-455b-982c-4ac2a8a20822)

### Expected Behavior

Decorate with (feature unavailable) star and Empty State E.g:
![image](https://github.com/FlowFuse/flowfuse/assets/44235289/fb4c954e-ee1d-403d-9978-11ec60e26800)

OR

hide the blueprints entry in CE mode

### Steps To Reproduce

visit admin pages in CE mode

### Environment

- FlowForge version: 1.14.1

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
I believe that was addressed in #3180 that has been merged this morning.

**Comment by Steve-Mcl** [comment]
Verified locally
