### ISSUE TITLE
Pipelines have same pictogram as Snapshots

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#3223]
### Current Behavior

Pipelines have same pictogram as Snapshots

![image](https://github.com/FlowFuse/flowfuse/assets/44235289/e5be7761-61fe-42a9-956e-fc6d293d900f)

@Yndira-FlowForge do you recall if was an image ever requested/created for this? 

### Expected Behavior

I suspect this should have its own unique graphic?

### Environment

- FlowForge version: 1.14.1

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Yndira-FlowForge** [comment]
Hi @Steve-Mcl, yes, we have a pictogram for pipelines, [this one](https://drive.google.com/open?id=12xKvknaNFA0spsY8ntXvNDeKsE4PFCZ4&usp=drive_fs)

**Comment by Pezmc** [comment]
![Screenshot 2023-12-20 at 16 49 44](https://github.com/FlowFuse/flowfuse/assets/507155/e008d333-02a2-4ee7-8601-fbd015460077)

**Comment by Steve-Mcl** [comment]
closing as PR #3250 now merged

**Comment by Steve-Mcl** [comment]
Also, verified on staging
