### ISSUE TITLE
Device Groups: First pipeline stage hides button

### ISSUE THREAD

**Issue by Pezmc** [FlowFuse/flowfuse#3246]
### Description

A device group can't be the first stage in a pipeline, however instead of showing this to the user, we hide the device group button entirely when creating your first stage.

It'd be much clearer if this button was visible but disabled with a tooltip explaining why, similar to the deploy to devices option. /cc @joepavitt 

### First stage

![Screenshot 2023-12-20 at 15 27 05](https://github.com/FlowFuse/flowfuse/assets/507155/ba4fae04-42d1-455a-8f9f-1a9431e88e86)

### Second stage

![Screenshot 2023-12-20 at 15 27 40](https://github.com/FlowFuse/flowfuse/assets/507155/01f30007-c334-42ef-8be0-4ff7916eee59)

### Epic/Story

#3157
https://github.com/FlowFuse/flowfuse/issues/2997

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Agreed
