### ISSUE TITLE
Device Onboarding - device.yml improvements

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#3256]
### Description

When first registering a device in FlowFuse, a major hold up and pain point is being able to get the `device.yml` from FlowFuse onto the physical device. Options generally include:

- `ssh` into the device, and copy the file over. 
- FTP server
- Manually copy over the file contents

All of these contain friction. Instead, I propose that we offer a command from the `flowfuse-device-agent` that allows for single cmd linking to a FlowFuse instance using a three-word passphrase.

In this case, when I first add my device, and see my Device Credentials, I could also be presented with a three word passphrase, for example: `hugging-octopus-raspberry`

Then, on my device, I could run something like `flowfuse-device-agent config link hugging-octopus-raspberry` and it would consequently retrieve the `device.yml`, put it into the correct place on my machine and run the agent.

One complexity would be which FF instance the `flowfuse-device-agent` communicates to in order to retrieve this, a bare minimum manual reqt would likely need to be `flowfuse-device-agent --ff-host https://app.flowfuse.com --config hugging-octopus-raspberry`

Or we could even offer `--ff-host ff-cloud` as shorthand for FlowFuse Cloud

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Tasks
- [x] Add changelog entry to the website to: https://github.com/FlowFuse/website/tree/main/src/changelog/2024
- [ ] Finalise changelog for website branch [3256-quick-connect-device](https://github.com/FlowFuse/website/tree/3256-quick-connect-device) & raise PR (after merge)
```

**Comment by ZJvandeWeg** [comment]
`npx flowfuse-device-agent --auth-code=hugging-octopus-raspberry --host=app.flowfuse.com` should be enough for us to install the agent and onboard it. A one liner we can provide in the UI on FlowFuse

**Comment by ZJvandeWeg** [comment]
The `password` approach is also better than the web ui we provide now for devices with the agent pre-installed.

**Comment by GogoVega** [comment]
Can I suggest the Apple way of a discovery service:

After installing and running the agent on my device, it is not yet configured (FF not linked), I would see the following behavior:

1. The agent will create an mDNS service (like Bonjour)
2. On FF, when click on adding device, a window displays all available devices (unconfigured)
3. The user makes his selection (this allows more than one device to be configured at a time and no need to display codes anymore) and validates
4. Each device receives its config (by http request or something else) and finally deactivates the mDNS service

Problematics:
- Only works with FF self-hosted (same network)
- Identification of the device during pairing (usually a code must be entered to validate the pairing - perhaps used the last four digits of the Mac address or not ask (user validated the device))

The question from the FF team: is it worth it? I don't know but the simpler something is to do, the more pleasant it is to do it - so it makes you want to

**Comment by hardillb** [comment]
mDNS only works if the devices are in the same multicast domain (same subnet mainly). This works for Apple/Home devices because most home networks are single subnets.

FlowFuse devices are mainly aimed at industrial usecases where networks are deliberately separated for security purposes and devices are deployed to remote sites.

Also any FlowFuse other than the localfs install method (not recommended for most production usecases)  is running the FlowFuse app in a container which unless specially configured will not have access to the broadcast packets used by mDNS to discover devices as the app runs on a private internal network and is proxied to the external network.

I'm not sure there would be sufficient demand for this to cover the development investment.

**Comment by GogoVega** [comment]
Thanks for your reply,
I suspected that this suggestion would not find enough requesters because its usefulness is not globalized.

Another suggestion (more reasonable) would be to replace the suggestion of a passphrase and the host with only a link like verification emails:
1. On the "add a new device" window, add a self-generated link which is valid for 10 minutes
2. On the device, enter the following command or use the link in the ui - the agent uses this link to fetch the codes
```bash
npx flowfuse-device-agent --auth-link=[host]-random-uri-generated
```
The link contains the host address

**Comment by joepavitt** [comment]
Curious @GogoVega is there a particular reason you don't like the passphrase approach proposed here?

**Comment by GogoVega** [comment]
No, not particularly, as I said above, the simpler it is, the better it is for the customer.

**Comment by Steve-Mcl** [comment]
@MarianRaphael @joepavitt 

this feature raises a fair few questions for me.

1. Should we be storing the generated config alongside the "Join Phrase"
1. Or perhaps we should generate it on demand (when used)
1. Should there be a TTL applied to the Join Phrase? (Expire after time? Settable/fixed?)
1. Would we continue to show the device config after creation or show something else like 
    [x] Create Join Phrase
    [x] Create Config

**Comment by joepavitt** [comment]
1. Technical implementation is up to you/Nick
2. I'd propose it was a `device.yml` is shown - with a comment/line underneath including an example command top run with a three-word passphrase
3. I would expect a time limit on this, yes.
4. A new three word passphrase would be included with any new device credentials generated
5. I'd say the smaller scope is just extending the existing command line, so `npm install flowfuse-device-agent` and then calling our agent with a passphrase is a first iteration.

**Comment by joepavitt** [comment]
As a first iteration, I was thinking of something like this:

<img width="1041" alt="Screenshot 2024-01-23 at 11 29 49" src="https://github.com/FlowFuse/flowfuse/assets/99246719/05d42053-4755-469d-b3f9-874df8f17fdd">

**Comment by Steve-Mcl** [comment]
Notes from Eng Meeting today:

* RE: Device Join Phrase - new table? New field? 
   * First port of call - look at `AccessTokens` table. Care point around existing device tokens - ensure `scope` is considered (check device tokens invalidation routines etc) 
   * Possible candidate lib: NPM [random-words](https://www.npmjs.com/package/random-words)
* Generate and store the config in DB for retrieval 
   * NO - device config should be regenerated on demand (when Device Join Phrase is used)
   * An API for retrieving Device Join Phrase will return the yaml and immediately invalidate the Device Join Phrase
* Limited lifetime of Join Phrase? (Expire after time? Settable/fixed?)
   * YES (probably) TBD
* Continue to show the device config after creation or show something else like 
   * YES - see @joepavitt design idea above
   * YES - because old device agents wone support the new Join Phrase
* Is the suggestion by ZJ  to support npx init/install in scope?
   * Not at this time

**Comment by Steve-Mcl** [comment]
> As a first iteration, I was thinking of something like this:
> 
> <img alt="Screenshot 2024-01-23 at 11 32 49" width="1189" src="https://private-user-images.githubusercontent.com/99246719/298920358-085a4db6-600f-4999-b9c3-887940c8b286.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYwMjY3ODcsIm5iZiI6MTcwNjAyNjQ4NywicGF0aCI6Ii85OTI0NjcxOS8yOTg5MjAzNTgtMDg1YTRkYjYtNjAwZi00OTk5LWI5YzMtODg3OTQwYzhiMjg2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIzVDE2MTQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI1NzY2MzVlYzI5ZDk3NzgyYWZiMWZlNGZjYTVkMWIyOTJjN2VkMmMxZDQxZDJmNTM1NTU2MWY5OTNlMjFjZmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.KRubzfN6lSaJPBX41N3TlK_egh10APgVabv1A1rmpak">

@joepavitt 

A slight rewording (the initial stab  above felt a little awkward) - hope this is ok? (I stuck with the familiar "connect device to platform")

![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/aec2531d-774c-478b-bc50-29822f32e48b)

_Layout overall still feels a but clunky but i can live with it as a first iteration_

**NOTE: I chose not to overload the `--config` parameter but instead set it as `-otc`**

<br>

Question:

This work makes the `Copy to clipboard` button ambiguous.  Any suggestions please?
Perhaps the button drops down a choice of "Copy Device Configuration" and "Copy One Time Code"?
Or: We have 2 plain old "Copy" buttons one beneath or to the side of the target `pre` elements?

**Comment by Steve-Mcl** [comment]
@knolleary 

The random words lib proposed contains 1952 words if we permit all (min 2, max 14). That means there are approx 7million One Time Code 3 word combinations.

Should we consider the following to improve security:
1. rate limit on the new API that checks in with this one time code
2. include **device hash** in the command e.g. `flowfuse-device-agent --device Qa1T20D ff-host http:// --otc red-testing-baggage` 

Adding the device ID affords us the following:
* permits us to rate limit the API call per device (meaning we can have a fairly low/tight rate limit)
* narrows the scope of the API reducing user mistakes (i.e. they cannot run it against the wrong device)
* effectively increases the possible combinations to ~36 trillion (`1952 ^ (3 words + 1 device id)`) 
* permits us to know which device was attempted to be configured and act accordingly if the OTC provided is incorrect (without device hash, the actor could be throwing out random words in an attempt to hook anything in the tokens table)

Lastly, as there can only ever be 1 One Time Code per device ID, should we:
a) expire the OTC regardless of success
b) permit `n` attempts before expiring the OTC?
c) only expire OTC once the correct conditions (correct OTC + device hash) are provided
_(these opts are possible only if we include the device hash in the shell cmd)_

**Comment by knolleary** [comment]
I can see the appeal of requiring the device ID to be included, but I don't think it is necessary.

Picking 3 words from a list of 1952 (assuming no repeat) gives `7,426,286,400` combinations - 7 billion, not 7m as you say. If we wanted to increase that pool, we could expand it to four words - 14 trillion combinations. For an end user, I think that is preferable to requiring them to correctly type in a device Id that is not a recognisable word.

We should rate limit the route regardless to prevent enumeration - just need to pick a suitable rate.

The OTC should be expired as soon as it has been used.

**Comment by GogoVega** [comment]
> The OTC should be expired as soon as it has been used.

Perhaps you should also handle the case where the device is not associated with FF - avoid allowing a user to do so after x days.

**Comment by Steve-Mcl** [comment]
> `7,426,286,400` combinations - 7 billion, not 7m as you say

👍 

Funny story, I did the calcs - but I seem to be number dyslexic now too 😆 
_(lack of sleep me thinks)_



> We should rate limit the route regardless to prevent enumeration - just need to pick a suitable rate.

Will go with a rate limit of 30 per 30s window as a starting point. Can be tweaked in review.

**Comment by GogoVega** [comment]
Yes, the OTC must be revoked as soon as it has been used and must expire after a certain period of time.
I don't know what default expiry would be best (24-48h) but don't forget to mention it in the UI 😉

**Comment by Steve-Mcl** [comment]
Verified the command in a `deplot:pr` instance and on staging.


Staging
```
flowfuse-device-agent -o swimming-tree-test -u https://forge.flowfuse.dev
[AGENT] 06/02/2024 09:26:54 [info] Entering Device setup...
[AGENT] 06/02/2024 09:26:54 [info] Device setup was successful
[AGENT] 06/02/2024 09:26:54 [info] To start the Device Agent with the new configuration run the following command:
[AGENT] 06/02/2024 09:26:54 [info] flowfuse-device-agent
```

Verified token is one use only by running again

```
flowfuse-device-agent -o swimming-tree-test -u https://forge.flowfuse.dev
[AGENT] 06/02/2024 09:28:58 [info] Entering Device setup...
[AGENT] 06/02/2024 09:28:59 [warn] Problem encountered during provisioning: HTTPError: Response code 401 (Unauthorized)
[AGENT] 06/02/2024 09:28:59 [warn] Device setup was unsuccessful
```
