### ISSUE TITLE
Integrating SSO provider (Okta) role management in FlowFuse

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3264]
## Epic
https://github.com/FlowFuse/flowfuse/issues/2832

## User Story
As a Team Owner
I want to manage flowfuse user roles (such as Owner, Member, Viewer) in my organization via my SSO provider, such as Okta, to ensure consistency and centralized control over access and permissions.

## Requirement
- SAML Assertion Compatibility: FlowFuse must accept role membership information contained within SAML Assertions. 
- SSO Provider Compatibility: The solution should be compatible with [Okta](https://developer.okta.com/)
- Existing FlowFuse roles (Owner, Member, Viewer, Dashboard) for a specific team must be compatible with the roles defined in the SSO provider. There should be a direct mapping of roles from the SSO provider to the corresponding roles in FlowFuse.

## Not in scope 
The current scope does not include implementing granular restrictions or permissions. For information on planned granular restrictions, refer to  https://github.com/FlowFuse/flowfuse/issues/3093

## Expected Outcome
Successful implementation of this user story will enable FlowFuse Team Owner to seamlessly manage user roles through their preferred SSO provider, enhancing security and simplifying administrative workflows.

### Helpful links
- https://support.okta.com/help/s/article/How-to-define-and-configure-a-custom-SAML-attribute-statement?language=en_US
- https://support.okta.com/help/s/article/How-to-pass-a-user-s-group-membership-in-a-SAML-Assertion-from-Okta?language=en_US

## License
Enterprise Tier

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
Notes on my research around SAML Group handling with Okta.

I have created a test Okta account, with three groups:

<img width="744" alt="image" src="https://github.com/FlowFuse/flowfuse/assets/51083/1a2ad6c5-9ab9-4d6d-ae63-9ba0fbfdaead">

My user is a member of two of these groups, but not the third.

I have configured a SAML application to use with my locally hosted FlowFuse instance. In the configuration I've configued a 'group attribute' to include any groups the user belongs to that begin with the word `Test`:

<img width="683" alt="image" src="https://github.com/FlowFuse/flowfuse/assets/51083/1e53401e-539c-4f62-a47b-0670b1f890d7">


When I now login via SSO, the `profile` object we get [here](https://github.com/FlowFuse/flowfuse/blob/9fa974fb5f4f3072a124b3203699b8f70034618d/forge/ee/routes/sso/auth.js#L71) includes:

```
  FFGroups: [ 'TestGroupTwo', 'TestGroupOne' ],
  attributes: { FFGroups: [ 'TestGroupTwo', 'TestGroupOne' ] },
```


This establishes how the group configuration in Okta is passed to FF on login. The next steps are:

1. Given the group info is appearing in two places in the profile object, I want to compare this to another SAML provider (such as Azure AD). Whilst the scope of this task is Okta only, I want to see if there's a common pattern here that'll Just Work with another provider or if this really will have to be Okta specific. For example, Okta lets you set the attribute name to anything you want - `FFGroups` in the example above. Need to see if other provides are as flexible or if this needs to be configurable in the future.
2. Establish a pattern for how group names map to team membership/role
3. Identify what configuration is needed on the FF platform side to manage this.
    There is also a question on how this would be configured on FF Cloud vs a self-hosted instance. As a reminder - SSO configuration is at the platform-wide level, not the individual team level.
    - For self-hosted, there may be a single SSO configuration for all users of the platform, and that all teams on the platform have their membership determined this way.
     - For FF Cloud, we have multiple SSO configurations and if enabled to support team membership management, it must only be allowed to manage selected teams on the platform.
  
    As I understand it, the customer request behind this story is a self-hosted scenario, so will optimise for that. But need to make sure we have a path for FF Cloud Enterprise teams to also benefit, whether as part of initial iteration or a later one.

**Comment by knolleary** [comment]
Some other open questions I'm thinking through:

 - We have rules in place that prevent a team being left without an Owner. If team-membership is now managed externally, it would naively be possible for all members of a team to be removed. What then?
    - Do we refuse to remove the last owner of a team even if they have been removed from the SAML group of team owners? 
    - Or do we allow a team to be orphaned? It could be a temporary transitional state as OwnerA is removed and OwnerB is added - it just happens that OwnerA has logged in first so we've removed them, and OwnerB hasn't logged in yet so hasn't been added.
    - If we allow an orphaned team, should we suspend it's instances? Probably not given the 'owner transition' scenario described above.

**Comment by knolleary** [comment]
MS Entra notes (formerly Azure AD).

By default, it includes the groups a user is in as:
```
  'http://schemas.microsoft.com/ws/2008/06/identity/claims/groups': [
    '2dad4827-f963-405c-9e46-50091050cde6',
    '4a769ca0-39bd-417c-b659-d7fe992b7b45'
  ],
```

I have found an option to customise the attribute name - so we could standardise on `FFGroups` (or similar) as I could do with Okta.

However it is passing the `groupIds`, not the group name. So whilst with okta we could establish a naming schema to identify team/role, that wouldn't be possible here - we'd need to configure a `groupId` to team/role mapping in the SSO configuration.

That said, I can see some options in Entra to pass group name - however that feature isn't available on my trial account... will see if I can upgrade my account without too much hassle to see what will be possible.

If we can get to the point where the group assertion is provided under a name we defined (possible in Okta and Entra), and the groups are provided by name (possible in Okta, TBD with Entra), then we have a solution that will work for both without additional work.

**Comment by knolleary** [comment]
One more note of difference between Entra and Okta.

 - Okta groups are simple boolean status of either a member or not.
 - Entra allows users to have roles in a group and optionally to include the role info in the SAML response

I could imagine Entra users would want to use this group/role capability - but as that isn't a concept available with Okta, we won't accommodate that for this iteration.

**Comment by knolleary** [comment]
Have now confirmed it is possible to get Entra to return the list of group names under a configured assertion name. That means I can focus on Okta in the knowledge it will be reusable for at least one other provider in the future.
