### ISSUE TITLE
Introduce Device audit log

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3268]
## Description

Introduce an Audit Log for Devices

## Scope

- [ ] Add Device as a valid entityType for AuditLog entries
- [ ]  Create endpoint to return entries for a device
- [ ]  Define MVP set of audit events
- [ ]  Identify key events the Device Agent should report back (and how)
- [ ]  Map events to Audit Log entries

## License
(CE - Open Source)
Starter Tier

**Comment by hardillb** [comment]
Device Audit log entries

- Crashed/restarted
- Editor accessed (especially if local access enabled)
- Settings changed

Open to suggestions for more, need to check what we already log at the Team Level.

**Comment by hardillb** [comment]
How should a device report Audit log events? As an MQTT message (with HTTP fall back?)

**Comment by Steve-Mcl** [comment]
Verified from local device to staging



![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/ff2996b8-6a5c-4753-8253-e209fdee5656)

**Comment by joepavitt** [comment]
Closing as completed per above linked PRs
