### ISSUE TITLE
Streamlined device assignment to applications during device creation

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3295]
## Description

The current process of assigning a Device to an Application in FlowFuse requires an additional step, potentially leading to confusion or oversight by users. To enhance user experience and efficiency, it is proposed that during the device creation workflow, users should be directly prompted to assign the Device to an Application. This step would be optional, maintaining the flexibility for users who may not be ready to assign the device immediately. However, the option would be clearly presented, making it more accessible and intuitive.

![Screenshot 2024-01-05 at 13 47 15](https://github.com/FlowFuse/flowfuse/assets/73583313/6662a038-1068-4498-bc21-1e3dfe263ab9)

![Screenshot 2024-01-05 at 13 49 28](https://github.com/FlowFuse/flowfuse/assets/73583313/2d6d4a47-9727-4c4d-83ba-4be42a5c3abe)

## Scope

Integrate a clear and optional dropdown menu in the device creation process where the user can assign the device to an application. 

## License
CE / Starter

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Requirement
- [ ] https://github.com/FlowFuse/flowfuse/issues/3248
```

**Comment by MarianRaphael** [comment]
Blocked: Currently this would not be possible because FlowFuse needs to know the Device Agent Version first:
"The device version could not be determined. Please ensure you have refreshed the browser and the device has connected to the platform before assigning it to an application."

**Comment by knolleary** [comment]
I raised https://github.com/FlowFuse/flowfuse/issues/3248 for the blocking issue here.

**Comment by Steve-Mcl** [comment]
> Blocked: Currently this would not be possible because FlowFuse needs to know the Device Agent Version first:

Unblocked https://github.com/FlowFuse/flowfuse/issues/3248 merged today.

**Comment by Steve-Mcl** [comment]
Hi @MarianRaphael 

Firstly, is there a UX design for this? (I have scanned related storys/tasks - but didnt see anything specific to this - my apologies if i missed it)


> The current process of assigning a Device to an Application in FlowFuse requires an additional step

If the user adds the device from the Applications -> Devices page, the device is automatically assigned to the application

Therefore, I assume this task is for users creating a device from the Team->Devices page?

If so, can i clarify the blow please? 

1. The OP shows a separate popup modal dialog permitting choice of "Application"  and the scope states "Integrate a clear and optional dropdown menu in the device creation process where the user can assign the device to an application." Are we only offering application only OR instance as well?
1. If offering both, should we not combine the 2 dialogs to permit choice of App or Instance

**Comment by MarianRaphael** [comment]
> Therefore, I assume this task is for users creating a device from the Team->Devices page?

Yes

> The OP shows a separate popup modal dialog permitting choice of "Application" and the scope states "Integrate a clear and optional dropdown menu in the device creation process where the user can assign the device to an application." Are we only offering application only OR instance as well?

Only applications, for instance, leave the current workflow unchanged. While still allowing for the legacy path, we suggest adopting the new path via applications.

> is there a UX design for this?

No, it's really just an additional dropdown menu. If you think a design here is necessary and helpful, we can create one beforehand.

**Comment by Steve-Mcl** [comment]
Verified on staging.

* [x] Create unassigned device from teams->devices
* [x] Create app assigned device from teams->devices
   * [x] device gets correctly associated
* [x] App selection is NOT shown when editing a device or when adding a device from Application->Devices
