### ISSUE TITLE
UI glitch in invites table when empty

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#3314]
UI glitch (misaligned table columns) in `account/teams/invitations`

![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/1dea023c-5765-4bac-8b0b-654d110a5dc5)

_Originally posted by @Steve-Mcl in https://github.com/FlowFuse/flowfuse/issues/3039#issuecomment-1883234458_

**Comment by hardillb** [comment]
Verified on local and staging
