### ISSUE TITLE
start FlowFuse on Windows in the background

### ISSUE THREAD

**Issue by tichribra** [FlowFuse/flowfuse#3328]
Hello,
I have installed FlowFuse on Windows as it is described in the docs. When I start FlowFuse with the command >>c:\flowforge\bin\flowforge.bat<< the windows shell appears with logs of the starting FlowFuse (see picture below). When I close the shell-window FlowFuse also stops. Is it possible to start FlowFuse on Windows in the background without the appearing shell-window?

![image](https://github.com/FlowFuse/flowfuse/assets/135816321/fdce72c4-a534-4ced-bc93-05d6e7c9c416)

**Comment by hardillb** [comment]
We don't have specific instructions for the FlowFuse app at the moment, but these instructions for the device-agent should apply to the FlowFuse app it's self as well

https://flowfuse.com/blog/2023/12/device-agent-as-a-windows-service/

**Comment by tichribra** [comment]
Thanks for your reply!
Together with this little tutorial (https://www.youtube.com/watch?v=bDtmskJloQk) I installed a FlowFuse-Service.
Now FlowFuse starts automatically at startup without the shell window.
