### ISSUE TITLE
Scalability: Device Log streaming

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#3332]
Part of #2782 

To get live logs from a device we currently do the following:

1. The frontend opens a websocket connect to the device logs endpoint.
2. We publish an mqtt command to the device to request it start sending its logs
3. The device starts publishing its logs via mqtt
4. When the platform receives a log message, it streams back over any frontend websockets connected for this device

At step 4, if the platform spots there are no active websockets listening for device logs, it sends a command to the device to stop sending the logs.

We need to revise this model to work with a horizontally scaled application. This is a similar problem to the Device Editor (#2514) however we are now working with MQTT from the device and websocket to the frontend.

If we use a shared-subscription for the logs topic, then each log line will go to a different app instance so only a subset will get forwarded over the websocket to the front end.

If we use a regular subscription, every instance will receive every log line. That is wasteful, but at least it would ensure every log line gets forwarded over the websocket from whichever instance holds the connection. However, we would need a solution for the behaviour described in step 4 - all of the instances that don't hold a websocket connection for the device logs will tell the device to stop sending them, unaware that another instance *was* consuming them.

**Comment by hardillb** [comment]
If we keep state of which forge instances have a client connection in a central store, we could track if the device needs to keep logging.

Problems will be race conditions when updating the central store with the "count" of clients attached to each instance.

Could we take the forge app out of the picture and allow the web page to subscribe to the direct MQTT topic from the device. Then use LWT and an disconnect message to keep track of how many connected log consumers there are?

**Comment by hardillb** [comment]
Complications of the above idea would be authentication for the browser. 

It would need the ability to generate a token and ACL access based on the users team membership and level.

**Comment by joepavitt** [comment]
Can this be closed now?
