### ISSUE TITLE
Unable to create Devices in Application

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#3333]
### Current Behavior

https://github.com/FlowFuse/flowfuse/assets/99246719/149551c2-6bab-400f-baff-d70954688057

### Expected Behavior

I should be able to add a Device here, any warnings about device agent versioning are irrelevant until I've tried to connect it to an agent.

### Steps To Reproduce

- Go to any Application
- Go to the "Devices" tab
- Click "Add Device"

### Environment

- FlowFuse version: `main`
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
Related:
 - #3248 
 - #3295

**Comment by joepavitt** [comment]
The key check that fails is the device agent version, which is impossible to know at that point because we haven't used our `device.yml` to run the `agent.

**Comment by hardillb** [comment]
It does create the device (as can be seen under the team device list), it fails when trying to assign it to the application

**Comment by Steve-Mcl** [comment]
@joepavitt https://github.com/FlowFuse/flowfuse/pull/3334 - would appreciate feedback on the (very slight) UI change to indicate a version issue (screenshots in PR)

> It does create the device (as can be seen under the team device list), it fails when trying to assign it to the application

@hardillb @joepavitt this is also handled in https://github.com/FlowFuse/flowfuse/pull/3334 - it now both creates the device AND assigns it.

**Comment by Steve-Mcl** [comment]
closed by #3334
