### ISSUE TITLE
Implementation - Automated Snapshot creation on Flow Deployment for Instances

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3355]
## Description

This feature introduces an automated snapshot creation system triggered by the generation of an "Flow Deployed" audit log entry. Each snapshot will be automatically named with the prefix [auto], followed by the current date and time. This feature includes configurability for the number of auto snapshots retained; older snapshots beyond this limit will be automatically deleted, provided they are not currently in use as target snapshots.

## User Story

https://github.com/FlowFuse/flowfuse/issues/2423

## Scope

- Trigger Condition: Snapshot creation occurs upon the generation of an "Flow Deployed" audit log entry.

- Naming Convention: Snapshots will be named following the format [auto]Date+Time, incorporating the date and time of creation.

- The maximum number of auto snapshots retained is 10.

- Snapshot Retention: Snapshots currently designated as target snapshots will be exempt from automatic deletion.

- For Instances only

## Which customers would this be available to

Licensed Edition (EE)
Teams Tier

**Comment by robmarcer** [comment]
This was requested by this potential customer - https://app-eu1.hubspot.com/contacts/26586079/record/0-1/3221501

**Comment by joepavitt** [comment]
Am I right in saying this is the Instance version of https://github.com/FlowFuse/flowfuse/pull/3481?

**Comment by Steve-Mcl** [comment]
> Naming Convention: Snapshots will be named following the format [auto]Date+Time, incorporating the date and time of creation.

The format of the name should match the [format agreed](https://github.com/FlowFuse/flowfuse/issues/3358#issuecomment-1935793784)  format for devices/pipelines?

<br>

Similar to the unanswered question asked on Device Auto snapshot [here](https://github.com/FlowFuse/flowfuse/issues/3358#issuecomment-1935790720) - it is likely time to add a database change and include a flag for the reason/source of snapshot. This should be an indexed field to minimise DB scans and for inevitable future capabilities like distinguishing not only what kind of snapshot it is but how it was initiated - `where snapshotReason === 'flows.set:full'`,  `snapshotReason === 'manual', `snapshotReason === 'plugin' that would help with things like UI filtering, logging and clean up management.

If yes, then would the retro of device auto snapshots be in scope or a separate task?


<br>

Question:  
Will this require the option to turn on / off like Devices?

If yes, where would this option be placed?  Instances do NOT have the "Developer Mode" tab so it would be in a different place (that then begs the question should we retro the enable/disable option we added in #3358 to match)?

If No, will we still want/need the feature and team type flags to be implemented?

2cents: The reason for permitting snapshots to be disabled on devices was driven by the [potential internet usage & bandwidth](https://github.com/FlowFuse/flowfuse/issues/3358#issuecomment-1935799486). This may not be relevant for instances. However users may still wish to turn off auto snapshot for commercial / personal / dev reasons!?!

##### For reference: device implementation
![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/feb40143-dc84-4dda-a2cb-ee6a6debe31e)



<br>

Question:
What, if any audit log entries should be made?
This was not implemented / not answered in Device Auto Snapshot: https://github.com/FlowFuse/flowfuse/pull/3481#discussion_r1489776664

**Comment by MarianRaphael** [comment]
> The format of the name should match the https://github.com/FlowFuse/flowfuse/issues/3358#issuecomment-1935793784 format for devices/pipelines?

Yes

> If yes, then would the retro of device auto snapshots be in scope or a separate task?

Separate issue

> Will this require the option to turn on / off like Devices?

No, for Instances I see no reason to turn it off

> If No, will we still want/need the feature and team type flags to be implemented?

Right -> Licensed Edition (EE) Teams + Enterprise Tier

> What, if any audit log entries should be made?

No extra Audit log, the existing Audit log entry is "Flows deployed"
