### ISSUE TITLE
User Identification in FlowFuse via HubSpot Integration

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3392]
### Description

Enhance user identification in all user-facing (HubSpot) aspects of FlowFuse, such as support chats, and other interactive services, through integration with HubSpot's Tracking Code API. This integration aims to provide a more personalized and efficient user experience.

### HubSpot Documentation

https://developers.hubspot.com/docs/api/events/tracking-code#identify-a-visitor

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
Cc @Yndira-FlowForge

**Comment by knolleary** [comment]
We deployed https://github.com/FlowFuse/flowfuse/pull/3411 at the start of this week. Can someone verify if hubspot is picking up the additional details now?

**Comment by joepavitt** [comment]
Closed by #3411
