### ISSUE TITLE
New Home Screen Implementation

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3398]
### Description

The existing home screen only displays Instances, neglecting Devices and other functionalities offered by Applications. Create a new Applications home screen that showcases both Instances and Devices prominently, treating them as equals.

## Design 
https://github.com/FlowFuse/flowfuse/issues/3152

## Scope 
The first iteration of this implementation will focus solely on the redesign of the Home Screen, adhering to the design concepts presented in [Issue #3152](https://github.com/FlowFuse/flowfuse/issues/3152). It's important to note that this phase will not include the "Favorite selection feature" as discussed in [Issue #3384](https://github.com/FlowFuse/flowfuse/issues/3384). During this iteration, the home screen will default to displaying the last three Instances/Devices with the newest Audit log entries, maintaining this behavior until a Favorite selection feature is integrated in subsequent updates.

## Epic
https://github.com/FlowFuse/flowfuse/issues/3366

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Pezmc** [comment]
@MarianRaphael A device can be associated with an application via several different routes, are we expecting all of them to show in this list (and later favourite selection)? Or only ones directly associated with an application?

Device -> Application
Device -> Instance -> Application
Device -> Device Group -> Application

**Comment by MarianRaphael** [comment]
Devices that belong to an application:

Device -> Application
Device -> Application -> Device Group (Device Groups are part of an application, but the devices themselves must be assigned to the application first)

Not for:
Device -> Instance -> *

**Comment by Pezmc** [comment]
Current status:
 - The /team/applications API has been updated:
    - to include devices
    - optionally limit devices and instances to a number (three on the homepage), but still return the total count
    - At @MarianRaphael's request; include most recent activity log message for instances and devices when in summary mode (and use this to select which instances/devices to show)
  - The UI now has:
     - The latest activity log message for instances and teams
     - Displays devices as well as teams
     - Shows devices as in device mode when set as such
     - The total number of instances and devices in the application
     
To add:
 - Working open editor button for devices (will be disabled unless in developer mode)
 - Test coverage of the devices rows
  
How it looks:
  
![Screenshot 2024-02-01 at 08 56 24](https://github.com/FlowFuse/flowfuse/assets/507155/5cff570e-71e3-412c-a8c4-95fb1689e4bd)

**Comment by MarianRaphael** [comment]
Looks good 👍  What catches my eye is the missing visualization for Pipelines, Snapshots, etc., as small icons.

**Comment by MarianRaphael** [comment]
Works for me as an iteration to get it faster to prod
