### ISSUE TITLE
Add the ability to restart a Device Agent Instance

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#3455]
### Description

**As a:** Developer
**I want to:** be able to restart the Node-RED instance running on a device
**So that:** I can upgrade installed nodes while using the device editor feature. 

https://community.flowfuse.com/t/update-pallete-requires-restart-nodered/540

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by robmarcer** [comment]
This is this customer - https://app-eu1.hubspot.com/contacts/26586079/record/0-2/8342532829

**Comment by joepavitt** [comment]
Is this tied to #3292?

**Comment by MarianRaphael** [comment]
Duplicate https://github.com/FlowFuse/flowfuse/issues/3292
