### ISSUE TITLE
Private proxy registry for offline FlowFuse usage

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3461]
### Description

Currently, if a customer wants to install Device Agents, npm Node-RED nodes, etc., some form of internet connection is necessary. However, in the target scenario where no internet connection is possible, it is essential that the most important artifacts be distributed through a private proxy registry like Verdaccio.

## Necessary Artifacts for:
- Node-RED
- Device Agent
- Certified Nodes
- FlowFuse

## Requirements
- Docker (target infrastructure)
- Management of npmrc files at the device level

### Which customers would this be available to

Other (See comments)
Self-Hosted Enterprise customers only

**Comment by MarianRaphael** [comment]
FYI as discussed - @knolleary @hardillb

**Comment by hardillb** [comment]
Initial design will require 2 instances of the npm registry 

1. inside the air gapped network
2. outside with access to npmjs.org

Will start with adding the internal version to the docker-compose file (commented out)

Then create a script to run the external version and populate the cache

**Comment by joepavitt** [comment]
Doesn't have to go out in 2.1, can be released async

**Comment by hardillb** [comment]
@MarianRaphael What do we want to do with this?

It needs somebody other than me to read the docs and see if they can be followed and then fix any missing bits.

But we also probably need to talk to the potential client if this will meet their needs.

**Comment by MarianRaphael** [comment]
Target Environment: 

- Windows 2022 VM 
- CPU: 8
- RAM: 24GB
- pre install Docker Desktop

**Comment by hardillb** [comment]
Updates for windows support for npm cache in FlowFuse/docker-compose#126

**Comment by hardillb** [comment]
Completed in https://github.com/FlowFuse/docker-compose/pull/121 and https://github.com/FlowFuse/docker-compose/pull/126
