### ISSUE TITLE
z-index issue with description and source icon in snapshots table

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#3466]
### Current Behavior

![image](https://github.com/FlowFuse/flowfuse/assets/44235289/b20760d8-58e8-40e4-9639-c368657ef4f5)

### Expected Behavior

popout should cover other items

### Steps To Reproduce

expand the description

### Environment

- FlowFuse version: 2.1
- Node.js version:
- npm version:
- Platform/OS:
- Browser: Chrome latest

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
Verified on Staging
