### ISSUE TITLE
Add conversion code snippet on app. 

### ISSUE THREAD

**Issue by Hasmin-AC** [FlowFuse/flowfuse#3474]
### Description

Please add the following code snippet to the page right after someone signs up so that we can track google ad conversions.

<script>
  gtag('event', 'conversion', {
      'send_to': 'AW-16456599728/ehkDCMDNypAZELCRj6c9',
      'value': 1.0,
      'currency': 'CAD'
  });
</script>

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Thanks @Hasmin-AC - have changed the repo as this code needs to live in product. @Pezmc @hardillb not sure how we handle this for both product _and_ open source use cases?

Also, the `currency` option seems to be in Canadian Dollars?

**Comment by Pezmc** [comment]
As far as I'm aware we don't have google analytics integrated at any point.

So to add generic support for that, and then to add a conversion event, we'd need to add Google Analytics to our telemetry options https://flowfuse.com/docs/install/configuration/#telemetry-configuration, and then add various manually created events if google analytics is enabled.

**Comment by hardillb** [comment]
yeah, we would have to add it as a configurable option and include it the same way we add posthog inserts. We are also missing what google script header we would also need to include to make that snippet work.

**Comment by hardillb** [comment]
What is the google analytics script tag we need to add to enable the snippet mentioned?

**Comment by hardillb** [comment]
Suggested configuration:

```
telemetry:
  elabled: false
  frontend: 
    google:
      tag: test
      events:
        conversion:
          send_to: test/foo
          value: 1.0
          currence: 'CAD'
```

This would need to be added to the `flowforge.yml` and we can have multiple `events` defined under named keys.

The keys would need to be added to the UI by the engineering team to attach them at the right points.

Outstanding information required:

1. The exact format of what needs to be included in the page header to enable the `gtag` function. I think it's the same as this (https://github.com/FlowFuse/website/pull/1647/files) website update but I need that confirming
2. The ID value to be configured.

I also need to know if we can use the same ids in staging to test this before it gets applied to production.

**Comment by joepavitt** [comment]
Apart from `s/currence/currency` - works for me

**Comment by ZJvandeWeg** [comment]
@hardillb Wouldn't it be more effective if we just inject HTML? Now you're forming a YAML to a certain provider that might change when they feel like it?

**Comment by hardillb** [comment]
We have to do this in a way that is off by default for the CE release
