### ISSUE TITLE
Error: Instance Start Failed

### ISSUE THREAD

**Issue by blanpa** [FlowFuse/flowfuse#3480]
### Current Behavior

{ "error": { "code": "unexpected_error", "message": "Failed to start project 8ed57521-31b0-4c6d-a57e-7192a9cc2f7a: Error: (HTTP code 404) no such container - No such image: flowforge/node-red:latest " } }

### Expected Behavior

running Instance 

### Steps To Reproduce

setup with docker compose

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
Please complete the full template when opening issues.

What versions.

Also did you follow the install instructions here:

https://flowfuse.com/docs/install/docker/#running-flowfuse

It includes instructions to run `docker pull flowforge/node-red` before starting.

**Comment by hardillb** [comment]
@blanpa Any update?
