### ISSUE TITLE
Instance Protection Mode

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3488]
## User Story

As a FlowFuse Team Owner,
I want the ability to restrict modifications to production instances exclusively to Owners,
so that changes to any protected/productive instance require authorization from an Owner, ensuring controlled and secure updates.

## Scope

Introduce a Protected Mode setting within Instance Settings to safeguard production instances.

- Implement a button/switch within Instance Settings to activate or deactivate Protected Mode.

**Functionality in Protected Mode:**

- Editor Restrictions: The instance editor can only be accessed in viewer mode as an owner to prevent unauthorized modifications. Member and viewer team members still get viewer access.
- DevOps Pipeline Execution Control: Only Owners can initiate and execute pipelines targeting a protected instance, ensuring that critical environments are modified under strict supervision.

### Which customers would this be available to

Team + Enterprise Tiers (EE)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate
```[tasklist]
### Follow-up
- [ ] https://github.com/FlowFuse/flowfuse/issues/3139
```

**Comment by MarianRaphael** [comment]
Customer request: https://github.com/FlowFuse/flowfuse/issues/3093#issuecomment-1830293431

**Comment by hardillb** [comment]
I think this needs to be broken into 2 separate items

- viewer only editor access for owner, all others blocked
- Dev Pipeline work

**Comment by hardillb** [comment]
@MarianRaphael I need an answer to the ^ question or I'll be blocked today.

Thanks.

**Comment by MarianRaphael** [comment]
member and viewer team members still get viewer access

**Comment by robmarcer** [comment]
This is for https://app-eu1.hubspot.com/contacts/26586079/record/0-1/3228251

**Comment by Steve-Mcl** [comment]
Checked NR editor access is restricted. 
Checked session token is revoked when protection is toggled.
Checked owner can still operate pipeline

Last thing to check is non owner cannot operate pipeline 
Member Invite sent to Ben for "Steve on Staging" team, application `funny-crested-lark-6873`

**Comment by Steve-Mcl** [comment]
> Last thing to check is non owner cannot operate pipeline
> Member Invite sent to Ben for "Steve on Staging" team, application funny-crested-lark-6873

@hardillb verified
