### ISSUE TITLE
Setting a URL path for the editor (/editor) breaks Dashboard 2

### ISSUE THREAD

**Issue by SynoUser-NL** [FlowFuse/flowfuse#3513]
### Current Behavior

When setting the Editor URL Path option in a NodeRED instance under Settings \ Editor, this works fine for accessing the NR editor. 
However, opening the Dashboard 2 site will no longer work, but instead will display an in-browser error:

```
TypeError: Cannot read properties of undefined (reading 'ffSession')
    at /usr/src/flowforge-nr-launcher/node_modules/@flowfuse/nr-launcher/lib/auth/httpAuthMiddleware.js:12:33
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:328:13)
    at /usr/src/node-red/node_modules/express/lib/router/index.js:286:9
    at Function.process_params (/usr/src/node-red/node_modules/express/lib/router/index.js:346:12)
    at next (/usr/src/node-red/node_modules/express/lib/router/index.js:280:10)
    at initialize (/usr/src/flowforge-nr-launcher/node_modules/passport/lib/middleware/initialize.js:98:5)
    at Layer.handle [as handle_request] (/usr/src/node-red/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/usr/src/node-red/node_modules/express/lib/router/index.js:328:13)
    at /usr/src/node-red/node_modules/express/lib/router/index.js:286:9
```

This is observed in multiple instances.

### Expected Behavior

Setting the Editor URL Path will not have impact on Dashboard 2 access \ behaviour.

### Steps To Reproduce

- In a FlowFuse NodeRED instance, under Settings \ Editor, change the Editor URL Path to /editor
- Restart (or Suspend\Start) the instance
- Access the Editor, it will now open onder the {URL}/editor
- Open the Dashboard 2 site ({URL/dashboard or from within the Editor}, the error is shown in the browser window

### Environment

- FlowFuse version: v2.0.1
- Node.js version: 18.19.0
- npm version: ?
- Platform/OS: FlowFuse: Linux. Instances: running on same host as FlowFuse
- Browser: Tested with Edge & Firefox, OS: Windows 11

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by knolleary** [comment]
@SynoUser-NL what version of dashboard2 are you using? 

I believe this was fixed in the 1.2.0 release that was published yesterday - https://github.com/FlowFuse/node-red-dashboard/releases/tag/v1.2.0

**Comment by SynoUser-NL** [comment]
DB2 version: 1.2.0
Just tested again: same problem.

Also just updated DB2 on another instance from 1.1.0 to 1.2.0: no improvement..
Tried with Restart and with Suspend\Start.

Sorry..

**Comment by hardillb** [comment]
Just double checking

You moved the editor to `/edtior` and are still accessing the Dashboard on `/dashboard`

**Comment by hardillb** [comment]
I can reproduce this locally

**Comment by SynoUser-NL** [comment]
> Just double checking
> 
> You moved the editor to `/edtior` and are still accessing the Dashboard on `/dashboard`

yes.. moved editor to /editor and accessing DB2 on /dashboard.
I haven't tried changing the Dashboard URL path (which is set to the old dashboard /ui, and that is also the reason I haven't tried it..)

**Comment by SynoUser-NL** [comment]
I mentioned it as perhaps an option I should have tried, but didn't because it appears to be for DB1 only (which does run on /ui).
Not being able to change the BD2 path is perfectly OK. However I would like to be able to change the editor path and retain DB2 access.

**Comment by hardillb** [comment]
This is not just the Dashboad, it breaks all httpNode endpoints

**Comment by hardillb** [comment]
This will fix will require a stack container upgrade  after the next release

**Comment by SynoUser-NL** [comment]
Thanks! We'll test the fix as soon as possible.. :)

**Comment by hardillb** [comment]
We release containers for 2.1.1 yesterday, @SynoUser-NL you should be able to build new stack containers based on this image to pick up the fix
