### ISSUE TITLE
Docs: Device Setup Instructions outdated

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#3526]
### Description

https://flowfuse.com/docs/device-agent/quickstart/ includes nothing about the "Quick Connect"/three word approach that we have now running in production.

Instead, the instructions are nested away in https://flowfuse.com/docs/device-agent/register/#setup-command-method 

These need to be updated.

**Comment by Steve-Mcl** [comment]
verified present and correct
