### ISSUE TITLE
Update TeamType configuration to allow combined instance/device limit

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#3534]
Part of #3477 

**Objective**: Enhance flexibility in license allocation by allowing for a combined total runtime limit.
**New Feature**: Introduce the ability to set an overall limit for the total number of Node-RED Runtimes, in addition to the existing individual limits for Instances and Devices. For example, if a total runtime limit of 2 is set, a user could configure one hosted instance and one device under the same license.

**Comment by Steve-Mcl** [comment]
verified on staging (1 follow up, but passes all operational checks)



![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/92a120ab-e4ff-435d-86d8-18e111513419)

![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/18670b92-0513-4d9a-89bc-49012c5e5675)





![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/67d9727e-f457-4275-be68-c3b43e8942d2)

UX Issue - add device should be disabled: 

![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/6364acd4-6e8d-47c9-8842-1fc317785557)
