### ISSUE TITLE
Create AWS CloudFormation template for FlowFuse-on-AWS infrastructure 

### ISSUE THREAD

**Issue by ppawlowski** [FlowFuse/flowfuse#3539]
### Description

Currently, we give our customers some basic information on [how to deploy the EKS cluster in AWS](https://flowfuse.com/docs/install/kubernetes/aws/). In some places, we refer to external resources (Route53 domain configuration, creating TLS certificate), in others, we give partial instructions on what additional settings are needed (SNS) or link to the shell script which will create some RDS database instance. This makes the overall process tedious and error-prone.
This task aims to create a AWS CloudFormation template which will replace the above approach, and make it more user-friendly and resilient to user errors. Furthermore, the time to run the self-hosted FlowFuse platform on AWS EKS will become shorter - the customer will have to create a file with input data and run the script once. 
Additionally, we will be able to reuse this template in AWS Marketplace.

### Which customers would this be available to

All of those who wish to quickly deploy FlowFuse on AWS cloud with the Kubernetes approach

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by joepavitt** [comment]
Whilst this is beneficial for us, as we host on AWS, in the case of FF Dedicated Instances, is there a platform-agnostic alliterative that means it's just as easy to deploy to GCP, Azure, etc.

**Comment by ppawlowski** [comment]
There are two (or three, depends on the needs) major players here: [terraform](https://www.terraform.io)/[opentofu](https://opentofu.org) and [pulumi](https://www.pulumi.com).

**Comment by hardillb** [comment]
@joepavitt the reason for wanting to  use CloudFormation is that it can also be used in the AWS Marketplace alongside the Docker version to offer Customers 1 click K8s installs.

**Comment by ppawlowski** [comment]
I agree with @hardillb about using CloudFormation. 
However, it looks like GCP does not have a dedicated solution for IaaC and strongly [suggests using Terraform](https://cloud.google.com/docs/iac).
In such scenario we could end up with the following:
* CloudFormation (AWS), Bicep (Azure) and Terraform (GCP)
or
* CloudFormation for AWS Marketplace, maybe internally and Terraform (AWS, Azure, GCP) for customers
IMO, it is better to maintain two sets of "scripts" instead of three.

**Comment by joepavitt** [comment]
Yeah, if we can offer Terraform on Azure, I think that's more sensible to have CloudFormation and Terraform (2) than it is to put Bicep in there too?

Terraform seems an obvious first step at least after Cloud Formation, to ensure overage across GCP _and_ Azure.

**Comment by joepavitt** [comment]
Are we sure that terraform doesn't permit one-click installs on AWS marketplace? Given how popular it is, that surprises me? The interwebs is just full of "don't use CloudFormation, use TF instead" type articles

**Comment by hardillb** [comment]
AWS MarketPlace EKS installs need CloudFormation

**Comment by ppawlowski** [comment]
> * CloudFormation for AWS Marketplace, maybe internally and Terraform (AWS, Azure, GCP) for customers

Since I already put my hands on AWS CloudFormation, I definitely would prefer to follow this approach.

**Comment by joepavitt** [comment]
What would be the general steps required by a FF customers in the Terraform approach vs. the one-click install offered by AWS Marketplace?

**Comment by ppawlowski** [comment]
As [agreed](https://flowforgeworkspace.slack.com/archives/C032Q63FGG1/p1711116674216229?thread_ts=1711115661.049859&cid=C032Q63FGG1), we are not going to use AWS CloudFormation for setting up AWS infrastructure. Closing.
