### ISSUE TITLE
Allow HTTP max payload size to be configured

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#3577]
### Description

**As a** FlowFuse Admin 
**I would like to** be able to change the default 5mb HTTP payload size
**So that** I can support larger data uploads

Currently Instances have the default 5mb max payload size.

### Which customers would this be available to

Team/Enterprise Tier (EE)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

Requested by: https://app-eu1.hubspot.com/contacts/26586079/record/0-3/10928370628/

**Comment by zackwasli** [comment]
Requested by: https://app-eu1.hubspot.com/contacts/26586079/record/0-3/10928370628/

**Comment by MarianRaphael** [comment]
Updated the Tier

**Comment by Steve-Mcl** [comment]
verify criteria:

### Using a known flow size (e.g. 5000 bytes)

- [ ] Set limit `apiMaxLength` to 6kb, save, restart instance
- [ ] deploy a simple change - should succeed

<br>

- [ ] Set limit `apiMaxLength` to 4kb, save, restart instance
- [ ] deploy a simple change - should fail

### Using an inject with a string of 500 characters connected to a debug

```
[{"id":"0cdd246f428efea3","type":"inject","z":"3642c7ee286f9c17","name":"512 chars","props":[{"p":"payload"},{"p":"topic","vt":"str"}],"repeat":"","crontab":"","once":false,"onceDelay":0.1,"topic":"","payload":"FlowFuse stands out as a remarkable orchestration platform tailored specifically for Node-RED. Its intuitive interface coupled with robust features empowers users to seamlessly automate workflows, streamline processes, and enhance productivity. With FlowFuse, managing Node-RED flows becomes a breeze, offering unparalleled flexibility and scalability. Whether orchestrating complex sequences or simplifying routine tasks, FlowFuse proves indispensable for harnessing the full potential of Node-RED. (512 chars)","payloadType":"str","x":250,"y":1060,"wires":[["e633a8ebd6c3b5ab"]]},{"id":"e633a8ebd6c3b5ab","type":"debug","z":"3642c7ee286f9c17","name":"debug 5","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","statusVal":"","statusType":"auto","x":430,"y":1060,"wires":[]}]
```

- [ ] Set limit `debugMaxLenth` to 400, save, restart instance
- [ ] inject should limit debug output

<br>

- [ ] Set limit `debugMaxLenth` to 600, save, restart instance
- [ ] inject should not limit debug output

**Comment by Steve-Mcl** [comment]
All tested on staging

Setting 4kb
![image](https://github.com/FlowFuse/flowfuse/assets/44235289/a73a2ed0-4f5c-4e58-bb14-c315ae3cd439)

Setting 6kb
![image](https://github.com/FlowFuse/flowfuse/assets/44235289/eb883870-55c6-47fe-9b27-b3d2a7ea8bf9)

Debug limits
![image](https://github.com/FlowFuse/flowfuse/assets/44235289/84a03b72-4a30-4cd9-8154-1d58a8f03448)

![image](https://github.com/FlowFuse/flowfuse/assets/44235289/c2dc2e77-2cd2-4454-ae34-16c8a3733d49)
