### ISSUE TITLE
Allow Instance Health Check interval to be configured

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#3578]
### Description

As a FlowFuse admin
I would like to be able to set the timeout on the healthcheck
So that I can run large blocking workloads without nr-launcher killing the process.

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

Requested by: https://app-eu1.hubspot.com/contacts/26586079/record/0-3/10928370628/

- [x] https://github.com/FlowFuse/nr-launcher/issues/227
- [x] ~~Update drivers~~
   - [x] ~~https://github.com/FlowFuse/driver-localfs/issues/123~~
   - [x] ~~https://github.com/FlowFuse/driver-docker/issues/91~~
   - [x] ~~https://github.com/FlowFuse/driver-k8s/issues/149~~
- [x] #3713
- [x] #3715

**Comment by zackwasli** [comment]
Requested by: https://app-eu1.hubspot.com/contacts/26586079/record/0-3/10928370628/

**Comment by Steve-Mcl** [comment]
Questions

1. As an MVP, would it be suitable/desirable to support this via ENV Vars initially? 
2. There are multiple constants that define the hang detection. Would we expose all or just `HEALTH_POLL_INTERVAL`?
    * `HEALTH_POLL_INTERVAL`: Interval between status polls of Node-RED used to detect a hung runtime (default 7.5sec)
    * `HEALTH_POLL_MAX_STARTUP_ERROR_COUNT`:  The number of consecutive timeouts during startup phase before considering a NR hang (default 10)
    * `HEALTH_POLL_MAX_ERROR_COUNT`: The number of consecutive timeouts before considering a NR hang (default 3)
    * `HEALTH_POLL_TIMEOUT`: Timeout to apply to health polling requests (defaults to 500 less than `HEALTH_POLL_INTERVAL`)

**Comment by knolleary** [comment]
@Steve-Mcl I think env var approach would be a good quick iteration in terms of implementation. A second iteration that adds options in the settings for this could then just cause those env vars to be set under the covers.

If we don't do the UI piece, it will be critical to have clear, discoverable documentation about the setting. I don't think adding the UI piece is a huge overhead here, so I'd suggest see if you can timebox that piece to a couple hours at most once the base env var parts are done.

In terms of what settings, `HEALTH_POLL_INTERVAL` is the main one we care about here and I think is sufficient.

**Comment by knolleary** [comment]
@Steve-Mcl I've taken a second look at this and I don't see any need to update all the drivers. We can centralise it in the `/settings` api endpoint in the forge app - https://github.com/FlowFuse/flowfuse/blob/main/forge/routes/api/project.js#L798 - which takes the settings from the driver and adds in a bunch of standard settings (which this would be one).

The driver settings are intended to be the driver-specific things that need setting differently depending on the needs of the driver.

**Comment by Steve-Mcl** [comment]
> @Steve-Mcl I've taken a second look at this and I don't see any need to update all the drivers. We can centralise it in the `/settings` api endpoint in the forge app - https://github.com/FlowFuse/flowfuse/blob/main/forge/routes/api/project.js#L798 - which takes the settings from the driver and adds in a bunch of standard settings (which this would be one).

Hmmm, good point. i think since this work started out as a Env Vars I got trapped in that route.

Will pull everything tomorrow and revisit.

**Comment by joepavitt** [comment]
@Steve-Mcl status report please? Is #3715 the only outstanding item here?

**Comment by Steve-Mcl** [comment]
> @Steve-Mcl status report please? Is #3715 the only outstanding item here?

 #3715 (PR https://github.com/FlowFuse/flowfuse/pull/3716) is the only item to be merged. There was some re-work as requested and carried out on the drivers. 

Ready for final review/merge at any time.
