### ISSUE TITLE
Allow "debugMaxLength" to be configured

### ISSUE THREAD

**Issue by freefos** [FlowFuse/flowfuse#3581]
### Description

As a FlowFuse admin/developer
I would like to be able to set the value on the "debugMaxLength"
This is really easy when working with larger datasets.

### Scope 

- Add debugMaxLength to Instance and Device settings

### Which customers would this be available to

Team/Enterprise Tier (EE)

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by MarianRaphael** [comment]
Updated the Tier
