### ISSUE TITLE
Node Catalogues & NPM configuration file for Devices

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3588]
### Epic

https://github.com/FlowFuse/flowfuse/issues/3172

### Description

As a FlowFuse user who works with devices,

I want to be able to configure the .npmrc file and Node Catalogues within FlowFuse,

So that I have the flexibility to include my own external npm modules and integrate the Auth Dashboard plugin seamlessly into my development environment.

### Which customers would this be availble to

Team + Enterprise Tiers (EE)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
npmrc files and catalogue.json are already included in the settings pushed to a device that is bound to an Instance.

So does this only apply to Application bound instances?
If so then should this also include the other things we need to be able to configure for an Application bound device e.g.

- Node-RED Version

**Comment by hardillb** [comment]
Correction, .npmrc file and catalogue.json are added if they are contained in a snapshot.

The only way to get them into a snapshot is currently if the snapshot comes from an Instance where they have been configured.

**Comment by hardillb** [comment]
We need to decide what should take priority here. Should a device be allowed to set it's own .npmrc file that overrides the one in the snapshot?

**Comment by MarianRaphael** [comment]
> So does this only apply to Application bound instances?

Yes

> Should a device be allowed to set it's own .npmrc file that overrides the one in the snapshot?

Yes in Dev Mode

**Comment by MarianRaphael** [comment]
> If so then should this also include the other things we need to be able to configure for an Application bound device e.g.
> 
> Node-RED Version

See https://github.com/FlowFuse/flowfuse/issues/2802 a potential follow-up item

**Comment by hardillb** [comment]
>    > Should a device be allowed to set it's own .npmrc file that overrides the one in the snapshot?

> Yes in Dev Mode

That will prove very dificult

**Comment by MarianRaphael** [comment]
> Devices would need to be restarted for this to take effect.

Which isn't a big deal since https://github.com/FlowFuse/flowfuse/issues/3292 right? It should be now more or less like for an hosted instance
