### ISSUE TITLE
Signup page allows submission with whitespace padded email but api rejects it

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#3591]
### Current Behavior

Noticed in our application logs, a user was trying to sign up and failed multiple times as there was whitespace padding around their email.

The sign-up form allowed this to be submitted, but it failed email validation.

Example response:

```
{ "error": { "code": "unexpected_error", "message": "Validation isEmail on email failed" }, "user": { "id": null, "name": "Luke Skywalker ", "username": "luke", "email": "luke@example.com " } }
```

### Expected Behavior

I think the API is doing the right thing. I think the sign-up form should trim whitespace on all fields before submitting.

### Steps To Reproduce

Sign-up with a white-space padded email: `"foo@example.com "`

### Environment

- FlowFuse version: 2.2

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
> I think the sign-up form should trim whitespace on all fields before submitting

* Username/Email, yes.
* Passwords, no.

i believe spaces in a password should be treat like any other character

**Comment by Steve-Mcl** [comment]
name is already verified in the frontend using regex

![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/0b86c55a-690d-4096-8c53-79a3dc10f049)

As far as I can see, only the name and email address should trimmed start and end (the APIs `isEmail` validation will take care of valid email format)

**Comment by hardillb** [comment]
Verified locally
