### ISSUE TITLE
`type` parameter is not marked as required for `/api/v1/teams/` endpoint

### ISSUE THREAD

**Issue by ppawlowski** [FlowFuse/flowfuse#3596]
### Description

To create a team using API, two keys are required to complete this task: `name` and `type`.
At this moment [documentation shows](https://app.flowfuse.com/api/static/index.html#/Teams/post_api_v1_teams_), that only `name` is required. An attempt to create a team without the `type` field fails with an HTTP 500 error.
The goal of this task is to update documentation and mark the `type` key as required.

**Comment by Jayanth-Parthsarathy** [comment]
Hey there @hardillb @ppawlowski . I would like to work on this. Please assign this to me.
