### ISSUE TITLE
Enhanced Blueprint Accessibility in Library Tab

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3598]
## Background
Currently, Blueprints are accessible exclusively during the instance creation process. the Library tab only displays the Teams Library, which narrows the scope of accessible resources.

## Describtion
The introduction of a Blueprint Library alongside the existing Teams Library within the Library tab. This enhancement would enable users to easily toggle or select between the two libraries, thus broadening the accessibility and visibility of Blueprints.

## First Iteration Functionality
Clicking on a specific Blueprint within the Blueprint Library should redirect the user to the instance creation page.
The selected Blueprint should be pre-loaded or pre-selected in the instance creation workflow, streamlining the process of using a Blueprint for a new instance.

## Objective
A design that aims to improve the user experience by making Blueprints more accessible and easier to browse outside of the instance creation context.

**Comment by Yndira-E** [comment]
Hi @MarianRaphael is something like this what you had in mind?

![Image](https://github.com/FlowFuse/flowfuse/assets/129537638/75d350b1-c5c0-48a3-b664-7314a1436ebd)

**Comment by MarianRaphael** [comment]
I like it!
