### ISSUE TITLE
Implementing Trial Limitations

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3610]
### Epic

https://github.com/FlowFuse/flowfuse/issues/3609

### Description

As a FlowFuse Admin,
I want to configure specific trial limitations (number of Instances) within a Tier,
So that trial users can experience the advanced features of the (Teams) Tier with certain usage bounds to ensure resource efficiency and prevent system abuse during the trial period.

### Which customers would this be available to

CE (All Tiers)

### Acceptance Criteria

- [ ] The trial phase successfully offers the Teams Tier features to new users.
- [ ] The auto-creation of instances operates smoothly
- [ ] Trial limitations are effectively enforced

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
As this was closed before we had `deploy:pr` fully up and running, want to make sure this has been fully verified before closing - @knolleary can you do the honours please?

**Comment by knolleary** [comment]
Will double check today
