### ISSUE TITLE
Direct Access to Node-RED Dashboard from FlowFuse UI

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3611]
### Description

As a: FlowFuse User

I want to: Directly access my Node-RED Dashboard from the FlowFuse UI

So that: I can bypass the need to navigate through the Editor to select the Dashboard, streamlining my workflow and improving my user experience by providing immediate access to my dashboard 

### Which customers would this be availble to

Everyone - CE/Starter/Team/Enterprise

### Acceptance Criteria

- [ ] A new button titled "Dashboard" should be placed adjacent to the existing "Open Editor" button within the FlowFuse UI, ensuring it is easily visible and accessible to the user.
- [ ] The button should be only displayed if the npm module "Dashboard 2" is installed

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
@MarianRaphael To clarify, this feature is for cloud instances only?

**Comment by Steve-Mcl** [comment]
@joepavitt is there a base URL in dashboard 2 that will always take the user to the "main" (base) dashboard page?

**Comment by joepavitt** [comment]
> is there a specific (static/always present) base URL in dashboard 2 that will always take the user to the "main" (base) dashboard page?

No, but I assumed we would be parsing the relevant `flow.json` in order to determine if this button is even required? With that, the `ui-base.json` will have the base path under it's `path` property.

**Comment by Steve-Mcl** [comment]
> No, but I assumed we would be parsing the relevant `flow.json`


As it stands, parsing the flow JSON may be the _only_ way however I _really dont really like this approach_ (feels dirty and suboptimal)

What if dashboard 2 had a static URL that forwarded the user to the first dashboard base -> first page.  Is this something we might consider @joepavitt? It would be future proof if/when multiple bases are permitted (would redirect to the default base)?  



<br>

> in order to determine if this button is even required

thats what the check in the acceptance criteria is for though  ↓

> The button should be only displayed if the npm module "Dashboard 2" is installed

**Comment by joepavitt** [comment]
> What if dashboard 2 had a static URL that forwarded the user to the first dashboard base -> first page. Is this something we might consider @joepavitt? It would be future proof if/when multiple bases are permitted (would redirect to the default base)?

Not a fan of this, means that we'll _always_ have an entry point to Dashboard, that the user can never block off.

**Comment by Steve-Mcl** [comment]
> Not a fan of this, means that we'll _always_ have an entry point to Dashboard, that the user can never block off.

That is no different to having an enabled ui-base? And it would provide a familiar landing URL to all users 🤷 

> First pass of this is to navigate to /dashboard given that we currently enforce that, but hope to improve in the future

Of course i will do what is requested. Just exploring better solutions

**Comment by joepavitt** [comment]
> That is no different to having an enabled ui-base? And it would provide a familiar landing URL to all users

I should have been clearer, I meant a URL, independent of configuration, that the user cannot change. Whilst this is _currently_ the case for the `ui-base` with `/dashboard`, we don't want this long term.

**Comment by Steve-Mcl** [comment]
@joepavitt @MarianRaphael 


1) Should we be following suit with current design and be placing the hyperlink under the editor link?
![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/9cf26ed2-c0a6-46cd-824e-4b08ce715f0a)

<br>

2) Not explicitly stated in the issue, but again, to follow current design, should we also be putting the link to dashboard button adjacent to the "Open Editor" button on the application view?
![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/61d98735-7694-4857-8511-913c19cb925d)

**Comment by MarianRaphael** [comment]
IMO only the buttons in 1 and 2 but not an additional hyperlink

**Comment by joepavitt** [comment]
Agree with Marian - buttons: yes, hyperlink: no

**Comment by MarianRaphael** [comment]
@Steve-Mcl for this issue, a changelog entry would be great! Thank you!

**Comment by hardillb** [comment]
I don't like that the button is enabled even if the dashboard nodes are not used, but verified on staging
