### ISSUE TITLE
Improved feedback of Node-RED editor status with integrates editor

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#3655]
**As a** Node-RED Developer, working through FlowFuse
**I want to** have clear feedback on the status of the editor/instance
**So that** I have a clear understanding on why I may not be able to edit on my instance directly

Conditions we need to consider for the [Immersive Node-RED Experience](https://github.com/FlowFuse/flowfuse/issues/2246) include when an instance is in one of the following states:

- Suspended
- Error
- Crashed
- Starting
- Installing

These are currently covered by our status pill, and traditionally just disable the "Open Editor" button. Now though, the Editor will be available directly within FlowFuse, meaning that, if in one of these states, we need to consider some form of improved feedback as a lot of screen real estate will be "dead", where the editor will go once available.

**Design Task:** https://github.com/FlowFuse/flowfuse/issues/3659
```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/3659
```

**Comment by joepavitt** [comment]
Essentially, we need to fill out this red space:

<img width="1311" alt="Screenshot 2024-03-28 at 13 39 26" src="https://github.com/FlowFuse/flowfuse/assets/99246719/5cd89f18-2e58-4498-a3d4-e6b104fcbcbf">

**Comment by joepavitt** [comment]
@Yndira-E is there any plan in your schedule for this at all? Would like to have something in over the next couple of weeks

**Comment by Yndira-E** [comment]
Hi @joepavitt yes, I have it planned for this week, but I'll probably won't be able to finish it until next week.

**Comment by joepavitt** [comment]
> Hi @joepavitt yes, I have it planned for this week, but I'll probably won't be able to finish it until next week.

That's great Yndira - thanks, just helps with the planning of the dev work

**Comment by cstns** [comment]
@joepavitt , should I close this task and handle future animations in another task?

**Comment by joepavitt** [comment]
Yep, good point - closing
