### ISSUE TITLE
Customize pre-staging environments

### ISSUE THREAD

**Issue by ppawlowski** [FlowFuse/flowfuse#3668]
### Description

As a developer, I would like to have a pre-staging environment pre-configured with:
* teams
* pre-generated devices
* pre-generated instances
* blueprints

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Having two teams:

- Empty
- Populated with _stuff_

Would be a great starting point here

**Comment by joepavitt** [comment]
@Steve-Mcl to list out schema he'd like, other opinions are also very welcome, let's focus on the 90% of cases and iterate after if needs be - lightweight is important

@ppawlowski to then implement accordingly, this should be live by end of this week

**Comment by Steve-Mcl** [comment]
Eng follow-up: A starter environment for quicker PR testing...

### Preamble/Notes 

* During feature development we often need to take screenshots for documentation. To get consistent and _real world_ looking screenshots, teams, instances, devices etc should be named in a way that makes them consistent and follows an overall theme. 
* Instances should be setup but **not** all of them should be auto started. I propose all pre-configured instances should be suspended. This will make the env light weight but ready for most testing eventualities.
   * We might want to have 1 instance auto start?
* As many features are behind feature flags or CE/EE based, I strongly recommend we have a minimum of 3 users setup so for ensuring RBACs function correctly / component visibility etc (so we dont miss these checks)


### MVP setup
* 3 teams ("Plant Starter", "Plant Team", "Plant Enterprise") that mimic the setup of our cloud offering, including matching up the feature flags
* Each team to have:
   * 1 application & 2 instances, 4 devices
   * App Name "Acme Plant"
   * Instance1 Name "Plant Live"
   * Instance2 Name "Plant Develop"
   * Device1 Name: "OP 1", Type: "RPI HMI"
   * Device2 Name: "OP 2", Type: "RPI HMI"
   * Device3 Name: "Machine 1", Type: "V1"
   * Device4 Name: "Machine 2", Type: "V2"
* 3 users 
   * owner/admin: existing
   * member: TBD
   * viewer: TBD

@joepavitt thoughts please. Any better suggestions for naming etc.
