### ISSUE TITLE
Add targetSnapshot info to Device Group page

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#3672]
Task generated from the checklist in **Improve Snapshot lifecycle handling** [#3622](https://github.com/FlowFuse/flowfuse/issues/3622)

**Comment by Steve-Mcl** [comment]
@knolleary 

Q1: Is it the expectation that this be a column in the Device Groups list page or in the individual Device Group (or both)?


_Mock up applied to device groups list page_
![image](https://github.com/FlowFuse/flowfuse/assets/44235289/965be4a2-bf3f-4a1a-9a91-bb349610c73c)

_Mock up applied to device group page_
![image](https://github.com/FlowFuse/flowfuse/assets/44235289/138bdfc0-070b-4c89-a25b-2d138dadb55a)


Q2: would this iteration expect the ability to remove the snapshot from the group (as part of the overall Snapshot lifecycle improvements) or perhaps add that as a task to #3622?

**Comment by Steve-Mcl** [comment]
@joepavitt I should probably have tagged yourself in case you have some UI/UX preferences here?

e.g. perhaps an overview page (like devices and instances have) is a better 1st iteration?

**Comment by Steve-Mcl** [comment]
@joepavitt only target snapshot? Only in the "Device Group" or "Device Groups" page (or both)? 

Regarding whitespace: there is a LOT in the tables too.

_Device Groups_
![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/509e0e3d-e7bd-4ced-a62c-b327187d477a)


_Device Group_
![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/e9e83131-ea5a-4ce2-a279-2590df94ff2f)

For reference, devices show the "Active Snapshot" in the Instance->Devices table.

**Comment by joepavitt** [comment]
**Device Groups:** 
- Show target snapshot table for _each_ device group

**Device Group:**
- Show target in top-right
- Show active snapshot for each device in the table

**Comment by Steve-Mcl** [comment]
### Current task: 
* Busy writing tests

### Current state/progress:

#### Device Groups


![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/44009899-6527-48bd-aec5-b9ab6dc8fb3d)

#### Device Group with target set


![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/a54761c6-416b-4e45-8a99-509e1aa3752f)



#### Device Group without target set


![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/acf49359-bc91-47cb-87f0-c07a9ed2bef2)

**Comment by Steve-Mcl** [comment]
verified on staging
