### ISSUE TITLE
Active link lingers when swithching instance tabs

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#3688]
### Current Behavior

The latest active tab remains marked as active even though it was navigated away from it.

### Expected Behavior

Only the current active tab should be marked as active.

### Steps To Reproduce

Open instance details page and navigate between tabs. After switching between a fair number of tabs hit the back button multiple times to retrace your tab navigation. You'll notice the last tab that was marked as active is still marked as active.

### Environment

- FlowFuse version: latest
- Node.js version: n/a
- npm version: n/a
- Platform/OS: n/a
- Browser: n/a

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
@cstns wasnt this fixed in a recent Pr by you?

**Comment by cstns** [comment]
Yes, it was handled in https://github.com/FlowFuse/flowfuse/issues/4022, nice catch!
