### ISSUE TITLE
Enhancing Blueprint Accessibility (First Iteration)

### ISSUE THREAD

**Issue by MarianRaphael** [FlowFuse/flowfuse#3729]
### Epic

https://github.com/FlowFuse/flowfuse/issues/3728

### Description

As a: New FlowFuse User

I want to: Easily locate where the Blueprints are within FlowFuse

So that: I can quickly create new Node RED instances using Blueprint templates.

### Which customers would this be availble to

Other (See comments)

- Teams and Enterprise for Self Hosted version (ee)
- All FF Cloud Users

### Acceptance Criteria

- [ ] Clicking on a specific Blueprint within the Blueprint Library should redirect the user to the instance creation page.
The selected Blueprint should be pre-loaded or pre-selected in the instance creation workflow, streamlining the process of using a Blueprint for a new instance.
- [ ] Design: https://github.com/FlowFuse/flowfuse/issues/3598#issuecomment-2040046219

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by cstns** [comment]
This area would love some TLC
![image](https://github.com/FlowFuse/flowfuse/assets/20094749/f83f813a-9f5b-4980-9673-c2521be72c93)

**Comment by cstns** [comment]
Would also rename the "Library" menu item and "Team Library" page title to "Shared Library" (open for discussion).

The library nomenclature doesn't quite fit now after splitting the page into multiple tabs.

Any thoughts @joepavitt @MarianRaphael ?

**Comment by knolleary** [comment]
'Team Library' is what it is labelled in the import/export dialog within Node-RED, but that comes from the settings file generated by the launcher so could be modified: https://github.com/FlowFuse/nr-launcher/blob/279538dd6fb406028d7c7566856626a8a446ce3b/lib/runtimeSettings.js#L186

<img width="324" alt="image" src="https://github.com/FlowFuse/flowfuse/assets/51083/b9522012-3ffe-4896-ab5f-052abe223ba3">

However, I think Team Library is the right label for within Node-RED.

I'd suggest we just update the top header of the page - call it Library to be consistent with the sidebar, with the Team Library and Blueprints as subtabs as per the screenshot. The description would need updating to match

<img width="214" alt="image" src="https://github.com/FlowFuse/flowfuse/assets/51083/95b9386c-9c59-4d35-8df8-357f383c5f75">

**Comment by joepavitt** [comment]
> I'd suggest we just update the top header of the page - call it Library to be consistent with the sidebar, with the Team Library and Blueprints as subtabs as per the screenshot. The description would need updating to match

Agreed
