### ISSUE TITLE
Webpack globally accessible ff-color variables across Vue components 

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#3731]
### Description

The ff-colors scss variables containing the color gradients should be globally accessible across Vue components without explicit imports

### Which customers would this be availble to

None

### Acceptance Criteria

- [ ] webpack build should not fail and UI changes should be applied when using any color vars in Vue components

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Closed by #3732
