### ISSUE TITLE
Getting a weak warning on the CreateAdminUser page

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#3739]
### Current Behavior

A weak warning is present in the browser's console when accessing the CreateAdminUser page regarding an invalid prop type

![image](https://github.com/FlowFuse/flowfuse/assets/20094749/df60ccfe-896a-47d9-bacf-0aaa45a4154b)

### Expected Behavior

No warnings should be thrown

### Steps To Reproduce

boot up a fresh ff app or force the application in the setup mode and start setup

### Environment

- FlowFuse version: 2.3.0
- Node.js version: n/a
- npm version: n/a
- Platform/OS: n/a
- Browser: n/a

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
@cstns I cannot recreate this. 

![Image](https://github.com/FlowFuse/flowfuse/assets/44235289/6941d4ab-889f-4502-a120-7a6314cef0e9)


Running from latest source, localfs + sqlite, with no database on file system, `httpClient.get('/setup/status')).data` returns the object:

```
{
    "adminUser": false,
    "license": true,
    "email": false
}
```

and the message you are showing is not displayed when the setup page is accessed. 

Perhaps this is OS or browser or docker or node related? can you provide a repro including version numbers, browser type, forge yaml settings (localfs?docker?k8s?) etc

**Comment by cstns** [comment]
I'm unable to replicate the problem either.

**Comment by Steve-Mcl** [comment]
transient?

Probably not worth leaving open.

Lets close it for now.
