### ISSUE TITLE
Exporting Team Library flows breaks the UI interface when users don't manually fill in the .json extension

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#3744]
### Current Behavior

Users are able to export a team library flow without appending the .json extension in the NR editor which then breaks the FF Team Library UI when displaying said export.

### Expected Behavior

The FF UI should be able to load and render said export even if the .json extension is missing

### Steps To Reproduce

- select a couple of nodes from the NR editor
- export nodes to team library and set a name that does not include the .json extension
- navigate to the FF Library page and click on the newly created export
- notice that the page is not displayed correctly

### Environment

- FlowFuse version: "2.3.0"
- Node.js version: n/a
- npm version: n/a
- Platform/OS: n/a
- Browser: n/a

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by sherbastian** [comment]
When exporting the flow from the NR editor, the placeholder name contains the .json placeholder. If we're going to solve this under the hood and make it transparent/seamless to the end user, this should also be addressed
