### ISSUE TITLE
Immersive view is missing the Link to Dashboard

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#3759]
### Current Behavior

As per title

![image](https://github.com/FlowFuse/flowfuse/assets/44235289/170c1cb4-6738-48ce-9f32-f110c8220c41)

### Expected Behavior

should have dashboard button same as regular view e.g:
![image](https://github.com/FlowFuse/flowfuse/assets/44235289/03bf31af-e326-4591-96cc-090c054020fc)

### Environment

- FlowFuse version: latest/git
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Thanks for opening, yeah, this was missed as the design for immersive was done at the same time the button was added, so the design was never updated.

**Comment by joepavitt** [comment]
Can I just get clarity on what this is fixed by @cstns - you've linked to another issue which is a duplicate of it, rather than linking to a PR? Is there a PR that contains the fix for this issue?

**Comment by cstns** [comment]
No PR yet, just the issue part of the epic describing the immersive editor so I won't lose track of it. I thought that due to it being more of an omission it should be treated as a story not a bug

**Comment by joepavitt** [comment]
Ah, understood. 

In the future, feel free to just modify the labels on the existing issue from `bug` to `story`, even if you didn't open the issue in the first place, rather than closing and opening a new one
