### ISSUE TITLE
How to install @flowfuse/node-red-dashboard-2-user-addon on self-hosted

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/flowfuse#3781]
### Description

Users are confused why it's not included by default, and need help and a guide what's needed. On the sales enablement side, there's probably the need to provide users with more assets when they install a license.

TODO:
- [ ] Step by step guide in the docs on how to install the plugin for self-hosted installations
- [ ] Update https://flowfuse.com/docs/upgrade/open-source-to-premium/
   - [ ] The URL (premium doesn't exist anymore)
   - [ ] The steps should link to installing the plugin
- [ ] Make assets available to sales on how to support trial customers

**Comment by ZJvandeWeg** [comment]
@MarianRaphael Did you have an issue for this already? II suspect it's duplicate but couldn't find anything

**Comment by hardillb** [comment]
Steps:

1. Customer requests a npm access token from FlowFuse
2. FlowFuse creates dedicated token for customer, for trial licenses the key should expire at the same time as the license
3. Add `https://catalog.flowfuse.com/catalogue.json` to list of catalogues either in the Instance setting or the shared template
4. Add `//registry.npmjs.org/:_authToken=` + the access token to the `NPM Configuration file` in either the Instance settings or the template
5. restart the instance
6. Install the `@flowfuse/node-red-dashboard-2-user-addon` via the palette manager in the Instance

Will write this up with screenshots for the docs.

**Comment by hardillb** [comment]
I'm 85% sure I created a new issue template on one of the private repos to request a new npm access token. Looking for it

**Comment by hardillb** [comment]
Found it, I put it on the project for the auth plugin

https://github.com/FlowFuse/node-red-dashboard-ff-auth/issues/new/choose
