### ISSUE TITLE
Flow Viewer: Snapshots

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#3798]
Implement the https://github.com/FlowFuse/flow-renderer in the FF product, by adding the option to visualise any Snapshots.

Design for the modal viewer for the flows themselves available here: https://github.com/FlowFuse/flowfuse/issues/3768 although need to add the specifics of accessing/opening this from the "Snapshots" view.

- [x] #3828
    - [x] #3835 (dependant on the above)
    - [x] Add change log entry for Viewing snapshots flows
    - [ ] Update docs-user-snapshot to include a description of the view snapshot feature

**Comment by joepavitt** [comment]
Switching to #3803 as first iteration as the APIs for Snapshots are a little more complicated than we need. The only way of getting the `flow.json` equiavelent would be using `/export` API end point, which is excessive for what we need here. As such, a new `/flow` endpoint (or something similar) should be built to better enable this viewer for snapshots

**Comment by ZJvandeWeg** [comment]
Interesting comment, I was going to ask what the design is for showing env vars, NR version, etc etc. :) Team library might indeed be a quicker win

**Comment by joepavitt** [comment]
> I was going to ask what the design is for showing env vars, NR version, etc etc

Iteration, iteration, iteration :)

**Comment by Steve-Mcl** [comment]
> Design for the modal viewer for the flows themselves available here: [#3768](https://github.com/FlowFuse/flowfuse/issues/3768) although need to add the specifics of accessing/opening this from the "Snapshots" view.

In a first iteration, there are 2 relatively basic approaches:
1. The snapshot table kebab menu gets a new option "view snapshot"
   1. NOTE: not all snapshot tables have the kebab menu so would need to be added
1. The tables get a new slim column with only a button <kbd>👁️</kbd>

What is not explicitly mentioned is who can view it but since the "Download Snapshot" #3627 feature is scoped to "Member", that would be a starting point.

**Comment by Steve-Mcl** [comment]
re-open for 2 follow on issues in the task list

**Comment by joepavitt** [comment]
Keeping this in the "Review" column to make sure we don't lose track of it

**Comment by joepavitt** [comment]
Changelog entry added: https://flowfuse.com/changelog/2024/05/snapshot-improvements/
