### ISSUE TITLE
DB Migration error 2.0.1 -> 2.3.0

### ISSUE THREAD

**Issue by mlschuh** [FlowFuse/flowfuse#3811]
### Current Behavior

Using a self hosted, localFS, sqlite install. When attempting to update from 2.0.1 -> 2.3.0, the service does not start and throws the following error in syslog:

```
{"level":"INFO","time":"2024-05-01T14:25:25.333Z","msg":" - 20240325-01-add-teamTypeScope-to-FlowTemplates.js"}
{"level":"ERROR","time":"2024-05-01T14:25:25.337Z","msg":"Failed to start: SequelizeDatabaseError: SQLITE_ERROR: no such table: FlowTemplates"}
{"level":"ERROR","time":"2024-05-01T14:25:25.337Z","msg":"Error\n    at Database.<anonymous> (/opt/flowforge/app/node_modules/sequelize/lib/dialects/sqlite/query.js:185:27)\n    at /opt/flowforge/app/node_modules/sequelize/lib/dialects/sqlite/query.js:183:50\n    at new Promise (<anonymous>)\n    at Query.run (/opt/flowforge/app/node_modules/sequelize/lib/dialects/sqlite/query.js:183:12)\n    at /opt/flowforge/app/node_modules/sequelize/lib/sequelize.js:315:28\n    at async SQLiteQueryInterface.addColumn (/opt/flowforge/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:184:12)\n    at async Object.up (/opt/flowforge/app/node_modules/@flowfuse/flowfuse/forge/db/migrations/20240325-01-add-teamTypeScope-to-FlowTemplates.js:14:9)\n    at async applyMigration (/opt/flowforge/app/node_modules/@flowfuse/flowfuse/forge/db/migrations/index.js:89:5)\n    at async Object.applyPendingMigrations (/opt/flowforge/app/node_modules/@flowfuse/flowfuse/forge/db/migrations/index.js:113:21)\n    at async module.exports.fp.name (/opt/flowforge/app/node_modules/@flowfuse/flowfuse/forge/db/index.js:80:5)"}
Error
    at Database.<anonymous> (/opt/flowforge/app/node_modules/sequelize/lib/dialects/sqlite/query.js:185:27)
    at /opt/flowforge/app/node_modules/sequelize/lib/dialects/sqlite/query.js:183:50
    at new Promise (<anonymous>)
    at Query.run (/opt/flowforge/app/node_modules/sequelize/lib/dialects/sqlite/query.js:183:12)
    at /opt/flowforge/app/node_modules/sequelize/lib/sequelize.js:315:28
    at async SQLiteQueryInterface.addColumn (/opt/flowforge/app/node_modules/sequelize/lib/dialects/abstract/query-interface.js:184:12)
    at async Object.up (/opt/flowforge/app/node_modules/@flowfuse/flowfuse/forge/db/migrations/20240325-01-add-teamTypeScope-to-FlowTemplates.js:14:9)
    at async applyMigration (/opt/flowforge/app/node_modules/@flowfuse/flowfuse/forge/db/migrations/index.js:89:5)
    at async Object.applyPendingMigrations (/opt/flowforge/app/node_modules/@flowfuse/flowfuse/forge/db/migrations/index.js:113:21)
    at async module.exports.fp.name (/opt/flowforge/app/node_modules/@flowfuse/flowfuse/forge/db/index.js:80:5) {
  name: 'SequelizeDatabaseError',
  parent: [Error: SQLITE_ERROR: no such table: FlowTemplates] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'ALTER TABLE `FlowTemplates` ADD `teamTypeScope` TEXT DEFAULT NULL;'
  },
  original: [Error: SQLITE_ERROR: no such table: FlowTemplates] {
    errno: 1,
    code: 'SQLITE_ERROR',
    sql: 'ALTER TABLE `FlowTemplates` ADD `teamTypeScope` TEXT DEFAULT NULL;'
  },
  sql: 'ALTER TABLE `FlowTemplates` ADD `teamTypeScope` TEXT DEFAULT NULL;',
  parameters: {}
}

```

### Expected Behavior

The migration should finish and FlowFuse should start.

### Steps To Reproduce

Follow the steps at https://flowfuse.com/docs/install/local/#upgrade in our environment. I can provide our database if desired and can confirm that the table `FlowTemplates` does not exist. 

Looking at the database table `MetaVersions`, it looks like the migration `20231006-01-create-flow-template-table.js` was run on initial install. I have no idea how the table could have been dropped since then.

### Environment

- FlowFuse version: 2.0.1 -> 2.3.0
- Node.js version: 18.19.0
- npm version: 10.2.3
- Platform/OS: Ubuntu 22.04.3 LTS
- Browser: N/A

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by mlschuh** [comment]
I expect the resolution to this would be some kind of data export/import but nothing was jumping out at me as to how I can do this.

**Comment by knolleary** [comment]
Hi @mlschuh 

I don't think the table has been dropped - I think it never got created in the first place. Do you know what version of FF you originally installed?

I'm fairly sure I understand how you've hit this. I'll have a fix for you soon.

**Comment by mlschuh** [comment]
Hi @knolleary,

Original install was 2.0.1. I have no problem running SQL against the database if it's an easy one-off resolution that way. 

As an aside, huge fan of the work you've done and I'm happy to see FF growing and giving you the resources to push NodeRED further.

**Comment by mlschuh** [comment]
Brilliant, the PR makes perfect sense to me. I have a maint window coming up in a few days that should let me apply it and I'm glad it looks to cover for more than my environment. 

Thanks for the quick turnaround. I'll either let the PR close this issue or close it myself once I have confirmation on my install.
