### ISSUE TITLE
Review Node-RED customisations in default FlowForge

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#382]
### Description

We need to review the Node-RED appearance inside a FlowForge project instance to identify:

1. standard customisations that NR already supports (title bar text, icon etc)
2. more 'involved' customisations (menu items, user menu etc)

I will update this issue with a FigJam link where we can sketch proposals.

**Comment by knolleary** [comment]
Link to FigJam to gather input of what customisations we want to make to the Node-RED editor in FF Cloud.

Anyone with this link can view the file. Anyone @FlowForge should be able to comment/edit - LMK if you have any issues.

https://www.figma.com/file/iEETlVUagOe9Lc2LseeMZH/FlowForge-Node-RED-Customisations

**Comment by sammachin** [comment]
@knolleary is this just editor or is there scope to add additional API's to Node-RED too?

**Comment by knolleary** [comment]
It is focused on the editor - the appearance aspects. Some of those things can be done today with the settings we provide. Some may need additional APIs in the editor to support the desired customisation.

The goal here is to identify those things so we know what we can do today and what requirements we need to push upstream to Node-RED first.

It isn't, at this stage, a deep dive into backlog features (version control, shared team library etc).

**Comment by knolleary** [comment]
Next step is to raise some issues for the specific items captured in the figma. Once they are raised, I will reference them here, but this task can then be closed as the review has been carried out.

**Comment by joepavitt** [comment]
Think we can close this off, as we do now have FF-themed Editor
