### ISSUE TITLE
nr-file-nodes not loading in instance

### ISSUE THREAD

**Issue by kaushalkumarjoshi** [FlowFuse/flowfuse#3836]
### Current Behavior

Under Templates, I have included the setting to exclude core file nodes as:

![image](https://github.com/FlowFuse/flowfuse/assets/11587185/6792010d-9d99-48bf-aeeb-89095cb423a3)

After this, I created an instance using this template but in manage palette I am getting error as:

![image](https://github.com/FlowFuse/flowfuse/assets/11587185/22809ec9-f24c-4f8f-95f3-8dfadeac88b2)

### Expected Behavior

As per documentation, the nr-file-nodes should work after disabling the 10-file.js

[https://flowfuse.com/docs/install/file-storage/#enabling-the-flowfuse-file-nodes](url)

### Steps To Reproduce

Followed the documentation in this link: [https://flowfuse.com/docs/install/file-storage/#enabling-the-flowfuse-file-nodes](url)

### Environment

- FlowFuse version: v2.3.0
- Node.js version: v20.12.2
- npm version: 10.5.0
- Platform/OS: Ubuntu 20.04 LTS
- Browser: Firefox 100.0.2(64-bit)

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by hardillb** [comment]
Do you have an enterprise license?

**Comment by kaushalkumarjoshi** [comment]
> Do you have an enterprise license?

Not yet.

**Comment by hardillb** [comment]
Then you can't use the FileStore, this is working as intended

**Comment by kaushalkumarjoshi** [comment]
Thank you for explaining. The log is not explaining this clearly.

Will be great if it gives message similar to nr-project-nodes

![image](https://github.com/FlowFuse/flowfuse/assets/11587185/3d48f998-54b4-4a3f-80ec-2997666bcfa6)

Regards

**Comment by hardillb** [comment]
And if you are using the localfs build you can just use the normal file nodes

**Comment by kaushalkumarjoshi** [comment]
> And if you are using the localfs build you can just use the normal file nodes

Yes. I remove 10-file.js from excluded nodes.
