### ISSUE TITLE
Default tab in the team library isn't the library

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/flowfuse#3871]
### Current Behavior

When a user clicks on library they see:

![Screenshot 2024-05-16 at 14 12 40](https://github.com/FlowFuse/flowfuse/assets/2529595/e8278779-ccf2-48e1-bfdb-231b2ae271e4)

Where I believe they should be seeing: 
![Screenshot 2024-05-16 at 14 13 08](https://github.com/FlowFuse/flowfuse/assets/2529595/b0345370-c1d7-49fe-89f0-6b305bedf39e)

With the slight exception that the library should be the first tab from the left too.

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by ZJvandeWeg** [comment]
cc @joepavitt @cstns

**Comment by cstns** [comment]
I followed the design in https://github.com/FlowFuse/flowfuse/issues/3598#issuecomment-2040046219 when implementing https://github.com/FlowFuse/flowfuse/issues/3729 which led me to believe that since the blueprints are the first option, they should be opened by default

**Comment by joepavitt** [comment]
Yep - entirely on me to have it the wrong way round in the design. I agree here that there is merit in switching the tabs and having the Team Library tab be the default

**Comment by friyad** [comment]
Hello @ZJvandeWeg,
I want to work on this issue. Could you please assign this issue to me?

Though I have already completed the task.

![Screenshot of work](https://github.com/FlowFuse/flowfuse/assets/86700138/418d5ddb-5c20-4fe4-9ae3-a49b56493141)

**Comment by joepavitt** [comment]
Thanks for working on this @friyad - feel free to open a PR when it's ready

**Comment by friyad** [comment]
Hell @ZJvandeWeg & @joepavitt,
I opened a PR. It would be appreciated if you could check it. PR id: #3897
