### ISSUE TITLE
Chore: Update Flow Renderer dependency to latest version 0.3.1

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#3875]
### Description

Flow Renderer was recently updated to fix scroll bar sizing. 

Once it is published to NPM, we should bump version in package at next opportunity. 

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by cstns** [comment]
handled in https://github.com/FlowFuse/flowfuse/pull/3863
