### ISSUE TITLE
Better name selection/definition when creating instances

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#3894]
Extracted from https://github.com/FlowFuse/flowfuse/issues/3884#issue-2302817877

## Better name selection

GitHub for example has better UX when typing what this thing does and is, it keeps the repository name empty at first and lets the user type:

![Screenshot 2024-05-17 at 15 42 49](https://github.com/FlowFuse/flowfuse/assets/2529595/2761a2a6-f655-4842-856e-776d1cc9f17f)

Suggestions it does make, but like so:

![Screenshot 2024-05-17 at 15 46 29](https://github.com/FlowFuse/flowfuse/assets/2529595/b5c0adb9-2df8-49bb-9abb-9436b0e5665d)

**Comment by joepavitt** [comment]
Just to provide an FF-flavoured version for this:

<img width="1255" alt="Screenshot 2024-05-23 at 11 33 24" src="https://github.com/FlowFuse/flowfuse/assets/99246719/60687f17-2c02-42b9-ae7f-5faa98ac2fd8">

**Comment by joepavitt** [comment]
Not sure I follow why having this check breaks the whole form?

**Comment by cstns** [comment]
I wouldn't use the word break, more like intertwined. Either way we choose to approach this would need some alterations. I just don't want to have to do it twice

**Comment by joepavitt** [comment]
Still not sure I follow - we have a single "Create Instance" form component - we add the logic/updates into there and it's done?

**Comment by cstns** [comment]
Yest, but when we click to select another blueprint than the default, the whole form is hidden and replaced with blueprint options, including the instance name input.

**Comment by cstns** [comment]
Will implement the new name feature without altering it's position in the instance form to avoid additional overhead

**Comment by cstns** [comment]
I left the refresh name button in place in order for users to re-generate names
