### ISSUE TITLE
Hide unavailable Instance types in "Create Instance" form

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#3896]
Extracted from https://github.com/FlowFuse/flowfuse/issues/3884#issue-2302817877

## Hide unavailable sizes

Come to think of it, maybe an instance size should just be bound to the tier. Either way; for the time being we should hide "Small" here:

![Screenshot 2024-05-17 at 15 47 36](https://github.com/FlowFuse/flowfuse/assets/2529595/8369f7c7-f04c-4b37-8a22-678009a869d4)

**Comment by cstns** [comment]
I'm not sure what binding an instance to a tier implies.

I filtered out disabled instance types in the meantime

**Comment by joepavitt** [comment]
> I'm not sure what binding an instance to a tier implies.

The idea from @ZJvandeWeg was that a team tier is constrained to just a single instance size, which would negate this selection.

I don't think we're going ahead with that for now, so as you've done it is the right approach
