### ISSUE TITLE
Relabelling "Stack" to "Node-RED Version"

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#3914]
Our own use case of "Stacks" has been entirely bound to a Node-RED Version. As a new user coming in "Stack" is unlikely to be clear as a term - are we not better off just calling it "Node-RED Version"?

**Comment by cstns** [comment]
Is this meant to be a platform wide renaming or just on the instance creation form pages?

**Comment by joepavitt** [comment]
Good question - as a start, I vote the "Create Instance" page, and any user-facing pages, e.g. the Instance overview too.

I think for now, keep the admin-facing options/language the same, and we can update that later.
