### ISSUE TITLE
Show "Preview Blueprint" button in the Create Instance form

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#3918]
A blueprint is pre-selected in the "Create Instance" form currently, but to see the content of that blueprint, the user must select "Choose another blueprint", and then they're presented with a preview button for the existing blueprint amongst others.

Design: https://github.com/FlowFuse/flowfuse/issues/3884#issuecomment-2126780210

As @knolleary has also pointed out, the tile itself in the "Create Instance" form looks interactive, so we could also try that itself being the "Preview" button?

**Comment by cstns** [comment]
I made the blueprint small tile clickable, which opens the flow previewer dialog. This would serve the purpose of previewing the blueprint flows when there's only a single blueprint available as the preview button will be hidden in that case alongside the 'Choose a different Blueprint' button

**Comment by cstns** [comment]
We could make the small blueprint tile click action more explicit by adding elements mentioned in https://github.com/FlowFuse/flowfuse/issues/3768#issuecomment-2076731668 to the tile itself.

**Comment by joepavitt** [comment]
> We could make the small blueprint tile click action more explicit by adding elements mentioned in https://github.com/FlowFuse/flowfuse/issues/3768#issuecomment-2076731668 to the tile itself.

I had considered this, having a "Preview" and "Switch" type buttons instead?
