### ISSUE TITLE
Pipeline deploy is overwriting instance editor title

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#3920]
### Current Behavior

The title displayed in the editor is customizable via the Settings of the instance. We default it to the name of the instance, so that when a user has the editor open it is easy to identify.

As this value is stored in the instance settings object, it gets captured in a snapshot.

When a pipeline is used to deploy a snapshot between instances, the target instance gets the editor title set to the title of the source instance. This is not desirable behaviour.

### Expected Behavior

Whilst snapshots should be a complete capture of the instance settings, I think there is greater value in preserving the editor title between snapshot deploys.

I propose we handle the editor title settings as a special case that the snapshot doesn't overwrite when deployed across instances via a pipeline.

### Steps To Reproduce

 - Create pipeline between instances
 - Deploy the pipeline
 - Observe the updated title of the target instance

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

### Requested By

1. https://app-eu1.hubspot.com/contacts/26586079/record/0-1/7283622371

**Comment by knolleary** [comment]
Spent a bit of time thinking about this one. Part of the problem is the `settings` object in a snapshot contains a bit of a mix of things that arguably shouldn't get applied when applying a snapshot via a pipeline, but that *should* be applied when rolling back a snapshot.

We can already distinguish between the two because the various functions have a `mergeEnvVar` flag already.

At a high level:

1. `controllers/ProjectTemplate/mergeSettings`  should gain a `updateEditorSettings` flag alongside `mergeEnvVar` that defaults to true.
2. If set to false, then it should be more selective over which editor-related settings are copied over. What that list is will take a bit more thought, but things like page title etc should be on that list.
3. `forge/services/snapshots/createSnapshot` includes a call to `importProjectSnapshot` with `mergeEnvVar` being set. This should also set `updateEditorSettings` - and follow the call through to make sure that value gets all the way into `mergeSettings`

I think that's the cleanest approach here.

**Comment by hardillb** [comment]
Which settings do we think should not be overridden?

My suggested list are:

- disableEditor
- header_title


maybe theme as well so that you can be sure which instance you are on by the colours?

@knolleary

**Comment by knolleary** [comment]
Looking at that list, I'm wondering if we should overwrite *any* of them. `palette_modules` is probably the one that should overwrite as it will ensure the right modules are preinstalled. All of the others kinda feel like things you want to have distinct configs for 'production'.

**Comment by hardillb** [comment]
That's a pretty big change of behaviour...

**Comment by knolleary** [comment]
Stick with `disableEditor`, `page_title` and `header_title` for first iteration.
