### ISSUE TITLE
Alter the Application Instance creation page feel more like a standalone page

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#3933]
The Application's team instance creation page should follow a similar pattern to other instance creation pages. see https://github.com/FlowFuse/flowfuse/issues/3929

Current:
![image](https://github.com/FlowFuse/flowfuse/assets/20094749/0249d993-dd0e-4e9d-bf9e-608199f4eee3)

Proposed:
![image](https://github.com/FlowFuse/flowfuse/assets/20094749/29506e1f-7764-4341-96e9-cc7af6fed1d9)

to note:
- breadcrumbs pointing to application link & static create instance page
- hiding contextual tabs
- general styling similar to what was done in #3929

**Comment by joepavitt** [comment]
Yep - agree with the approach entirely

**Comment by cstns** [comment]
https://github.com/FlowFuse/flowfuse/issues/3934 is a prerequisite to this task
