### ISSUE TITLE
Refreshing the page while creating an application instance does not load the team correctly

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#3934]
### Current Behavior

The team is not loaded after accessing the application > app > create instance page and reloading which prevents users from selecting instance types and instance stacks.

### Expected Behavior

Team data should be present after a page refresh.

### Steps To Reproduce

see current behaviour

### Environment

- FlowFuse version: 2.4.0
- Node.js version: N/A
- npm version: N/A
- Platform/OS: N/A
- Browser: N/A

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Closed by #3945
