### ISSUE TITLE
FlowFuse UI for configuring Environment Variables in NodeRED instances truncates / corrupts large multi-line values

### ISSUE THREAD

**Issue by steve-d-mottram** [FlowFuse/flowfuse#3972]
### Current Behavior

When trying to set environment variables containing secrets consisting of multi-line base 64 encoded data, both the UI options of pasting into an edit field or importing a .env file result in corruption of the value being imported. The edit field removes newlines and truncates the value. The import of a .env file containing enough multiline data results in multiple truncated environment variables being created. (e.g a file containing 1723 bytes in my test was split into two variables, the second with a random name).

### Expected Behavior

At least one of the FlowFuse UI options for setting environment variables should allow multi-line values of over 1k to be set without modification of the imported data, to support providing secrets that are large cryptographic keys.

### Steps To Reproduce

1. Create a file containing multi-line base-64 encoded data - preferably of over 1.7k in size (I haven't tested with smaller files, having encountered this problem using PEM format RSA keys)
2. In FlowFuse, select an Application and NodeRED instance, then navigate to Settings>Environment
3. Create a new environment variable using the UI and paste the contents of the test file into the "Value box.
4. Click "Save Settings"
5. Inspect the value of the environment variable, which is seen to to have no newline characters, and to be trucated
6. Modify the test file to create a multi-line .env file, and import it using the "Import .env" button.
7. In the Environment Variable UI verify that multiple trucated environment variables have been created (this may depend on the specific character sequence in the file)

### Environment

- FlowFuse version: 2.4.0 Docker Compose installation
- Node.js version: Default for Docker Compose (don't know how to find this info)
- npm version: Default for Docker Compose (don't know how to find this info)
- Platform/OS: Oracle Linux 9 VM
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by knolleary** [comment]
I believe the root cause here is the fact we're using `<input>` elements that will strip newlines from values inserted into them - the overall size isn't a factor.

Secondly, need to check how the env import logic holds up with well formatted newlines in values.
