### ISSUE TITLE
Users with accounts should be able to try out existing blueprints by using a configured URL

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#3973]
Authenticated users should be able to access a url that contains the blueprint id and be taken to an instance creation form.

The url format:
`<FlowFuse.domain>/deploy/blueprint?blueprintId=<xxx>`

At this moment in time the user's default team will be used and the user will have the option to select the application where the new instance will be created

The landing page is implemented as a distinct page which allows for greater flexibility in the sense that we could integrate gtag tags when reaching this stage.

**Comment by cstns** [comment]
Incidentally, this implementation would also work for unauthenticated users that attempt to access the url because they would get automatically redirected to the landing page.

**Comment by cstns** [comment]
Should users that belong to teams that don't have the Library feature enabled be allowed to 'deploy' instances via URL?

At the moment we're using the user's default team or the first team available if a user doesn't have a default team configured, but this team might not have the Team Library feature enabled. 

A couple of ways of moving forward would be to:
- have a dialog prompt on the Blueprint landing page that would allow users to select from a list of teams that do support the Team Library feature (if the user is part of any)
- If no such teams are available, display a notice that a team upgrade might be required or similar
- let the user deploy the blueprint (would actually bypass the Team Library feature)

@hardillb @knolleary thoughts?

**Comment by cstns** [comment]
I thought I might have configured local poorly because as a user belonging to a team that doesn't have the Team Library enabled he's just prompted with an upgrade banner when accessing the Library page.

In that case, another option would be to enable blueprints for everyone bu that would be a business decision, if the above config is correct.

**Comment by knolleary** [comment]
> In that case, another option would be to enable blueprints for everyone but that would be a business decision, if the above config is correct.

I thought they were already enabled for everyone. I'm trying to work out if I'm misremembering that, or if something has changed that should not have changed.

**Comment by knolleary** [comment]
Okay - got to the bottom of it. I was looking at the wrong thing.

1. Blueprints are available to all Team Types
2. The Team Library feature is a separate feature
3. When we added the blueprint tab to the TEam Library page, it should *not* be blocking access based on the Team Library feature flag - only the Team Library tab should be doing that.

**Comment by cstns** [comment]
I found the [PR change](https://github.com/FlowFuse/flowfuse/pull/3752/files#diff-1ccf8556c7b0512b8817a150f579e8c34196e7054e90819f048c405f02048166) that added that feature, it was my doing, I might have mirrored the library feature _too much_.

I'll create another PR to address it.

**Comment by knolleary** [comment]
@cstns https://github.com/FlowFuse/flowfuse/issues/4004 ;)
