### ISSUE TITLE
Update k8s driver to attach storage to instances

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#4003]
```[tasklist]
### Tasks
- [x] Define configuration options for persistent storage (ff.yml)
- [ ] Update k8s driver to attach persistent storage to instances
```

**Comment by hardillb** [comment]
First thoughts on required configuration.

This should live under the driver -> options section in the flowforge.yml file.

- `enabled` set to true to 
- `storageClass` name to use for PVC

That should work up to 120 access points (Instances) per EFS filesystem.

We will need a seperate EFS filesystem per 120

(https://github.com/kubernetes-sigs/aws-efs-csi-driver#createvolume-parameters)

**Comment by hardillb** [comment]
Assuming we get quotas to work, where should be configure the size?

Should it be at the driver level or the team type?

**Comment by joepavitt** [comment]
@hardillb any idea on a rough timeframe for when this would be ready?

**Comment by hardillb** [comment]
Aiming for end of the week

**Comment by hardillb** [comment]
OK, code is done for this, but I can't test it until I've finished writing the tool that will create new EFS filesystems to test along side it.

Plan is to deploy all this to the scaling cluster tomorrow and test it all before putting it up for Review.
