### ISSUE TITLE
"Compact" Applications view

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4015]
With many applications, instances and devices, the vertical space taken up in the applications view is considerable, and makes it very difficult to quickly scan and navigate to the relevant resources.

We should look at compressing the vertical spacing used up by several elements, and consider using a grid-3 column approach for the instances/devices lists where possible.

**Comment by joepavitt** [comment]
![mod-borders+inline-rev2](https://github.com/FlowFuse/flowfuse/assets/99246719/fc6ee2d9-01ce-4139-bd0e-f8976eed97a5)

Iteration sent by the client

**Comment by joepavitt** [comment]
<img width="736" alt="Screenshot 2024-06-11 at 17 56 16" src="https://github.com/FlowFuse/flowfuse/assets/99246719/a9eb3a9a-dd87-42a4-ad87-9a281384882c">

Note the client example doesn't include a "Dashboard" link as available for any Dashboard 2.0 instances, and the "Actions" shortcut to restart instances, etc.

**Comment by joepavitt** [comment]
In a "worst case" from a spacing perspective, we need all three options, we could look at a design like:

### Compact 1

<img width="1473" alt="Screenshot 2024-06-11 at 18 00 57" src="https://github.com/FlowFuse/flowfuse/assets/99246719/3603e497-bb74-4e8e-86ec-aebea6f7cdea">

### Compact 2

Or, remove the "Instance" icon entirely for each entry, and use that space for a compact "Status" icon instead?

<img width="1301" alt="Screenshot 2024-06-11 at 18 02 21" src="https://github.com/FlowFuse/flowfuse/assets/99246719/1fef02a9-c52a-459d-b37d-8ca2541073e6">

**Comment by Steve-Mcl** [comment]
If we make the text element of buttons responsive we could have the best of both worlds.

**Comment by cstns** [comment]
> I prefer the symmetry of version 2 but the lack of icons makes it harder to distinguish devices from instances due to the barely visible group text.

I agree with @Steve-Mcl on the symmetry and lack of icons. One thing to note is that if we're going for more of a compact look, we don't really need the full status pill. At a first glance using the color code of the status pill as an element of the instance tile (background, side border or bottom border) would be suggestive enough.

> We should look at compressing the vertical spacing used up by several elements, and consider using a grid-3 column approach for the instances/devices lists where possible.

In my opinion, we should not set a fix grid but more of a fluid/responsive layout. Tiles should have a max and min width (that would fit max 3/4 tiles on a row depending on viewport width) and wrap when needed

A lot of problems will be solved by adding the search option when dealing with a lot of instances and applications. The search function should dynamically filter out applications alongside instances when using it.

**Comment by joepavitt** [comment]
> If we make the text element of buttons responsive we could have the best of both worlds.

Not sure I follow what you mean here @Steve-Mcl?

**Comment by joepavitt** [comment]
> In my opinion, we should not set a fix grid but more of a fluid/responsive layout. Tiles should have a max and min width (that would fit max 3/4 tiles on a row depending on viewport width) and wrap when needed

Very much agree, just using three here as an example, this would fit as appropriate, single column for smaller screen widths, etc.

**Comment by joepavitt** [comment]
<img width="1518" alt="Screenshot 2024-06-12 at 08 54 41" src="https://github.com/FlowFuse/flowfuse/assets/99246719/3c34f241-8969-4903-b36f-f327690c1964">

@Steve-Mcl thoughts on adding the icon to the group header, and making the text line a little more prominant?

**Comment by Steve-Mcl** [comment]
> > If we make the text element of buttons responsive we could have the best of both worlds.
> 
> Not sure I follow what you mean here @Steve-Mcl?

I mean put visibility breakpoints on the text portion so that larger views see icon and text, smaller views see icon only. Just weary of the huge amounts of whitespace we have in out tables and views currently.

**Comment by joepavitt** [comment]
<img width="2006" alt="Screenshot 2024-06-12 at 11 16 04" src="https://github.com/FlowFuse/flowfuse/assets/99246719/ff2c2ce6-c3d2-44a5-b77f-99f979b0c386">

Another variant, avoid the "3 more instances, etc" not under each row, and instead add an extra button far-right to go tot he full instances/devices list

**Comment by cstns** [comment]
It definitely tidies up the place! Would clicking the more tile extend the section and show all tiles or a redirect to a new page?

**Comment by joepavitt** [comment]
> Would clicking the more tile extend the section and show all tiles or a redirect to a new page?

I'd vote it goes to the "Instances"/"Devices" tab for that application

**Comment by cstns** [comment]
What I think gets lost is the _bird's eye view_ of that page, which I find myself to use more than the instances or devices page just because of that.

**Comment by joepavitt** [comment]
> What I think gets lost is the bird's eye view of that page, which I find myself to use more than the instances or devices page just because of that.

We have all of the same information as previous? Even now, we only list a max of 3 instances/devices per application...

**Comment by cstns** [comment]
Did not notice that!

**Comment by joepavitt** [comment]
Just to demo what it could look like on more compressed screens:

![Image](https://github.com/FlowFuse/flowfuse/assets/99246719/f900e465-3457-4e75-b390-7571d1a84728)
