### ISSUE TITLE
Docker Compose Version has been Deprecated

### ISSUE THREAD

**Issue by gdziuba** [FlowFuse/flowfuse#4018]
### Current Behavior

The current version of docker-compose is version 3.3, which has been deprecated.  

This is building my own version of FlowFuse on an Ubuntu server with running the latest version of FlowFuse v 2.5

Warning:
```
admin@ubuntu:~/FF_App/docker-compose-2.5.0$ sudo docker compose -p flowforge up -d
WARN[0000] /home/admin/FF_App/docker-compose-2.5.0/docker-compose.yml: `version` is **obsolete**
[+] Running 5/6
 ⠴ Network flowforge_flowforge             Created                                                                      16.5s
 ✔ Container flowforge-nginx-1             Started                                                                      11.6s
 ✔ Container flowforge-flowforge-broker-1  Started                                                                      11.0s
 ✔ Container flowforge-postgres-1          Started                                                                      11.1s
 ✔ Container flowforge-forge-1             Started                                                                       9.7s
 ✔ Container flowforge-file-server-1       Started  
```

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by frerepu** [comment]
It's the use of the version defenition in docker compose that became obsolete not the version itself. Just remove first line of the yml
So docker compose files should begin with service/volumes/network... not with version: 2.xx
