### ISSUE TITLE
Improve onboarding e-mail formatting

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4039]
### Description

Part of #3839 

As part of the first steps of user-experience with FlowFuse, users are presented with plain text e-mails. Whilst functional, they do not look professional.

We use HubSpot in some cases to send nicely formatted e-mails, but should seek to provide nicer formatting/styling on these e-mails generated by the product.

### Which customers would this be available to

All of them

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Considerations: https://flowfuse.com/handbook/design/branding/

**Comment by joepavitt** [comment]
We should improve the format of the Team Invite e-mails whilst we're here too

**Comment by cstns** [comment]
First iteration: 

![image](https://github.com/FlowFuse/flowfuse/assets/20094749/30a6e5c2-93e2-4e5c-90fe-bb6c3607f0df)

**Comment by cstns** [comment]
removed social buttons and preferences management while leaving the address in the footer.

One thing that I'd need to do is point the url & banner src towards a static endpoint, preferably one of ours that has the logo and banner, at the moment they're pointing to HS.

**Comment by joepavitt** [comment]
@Yndira-E do we have this logo hosted on the website anywhere you could think of?

**Comment by Yndira-E** [comment]
Hey @joepavitt yes, here: https://github.com/FlowFuse/website/blob/main/src/handbook/images/logos/ff-logo--wordmark--dark.png

**Comment by cstns** [comment]
Is it ok to link directly to the GH blob?

**Comment by joepavitt** [comment]
no, but we can link to the hosted website version: https://flowfuse.com/handbook/images/logos/ff-logo--wordmark--dark.png

**Comment by cstns** [comment]
I'd need the 600x70-HS-newsletter-header.png available as well and can't seem to find it in the website repo.

![unnamed(2)](https://github.com/FlowFuse/flowfuse/assets/20094749/4af73301-6611-45fb-a64d-a5002ed6af83)

**Comment by joepavitt** [comment]
Open a PR to add it to the general `/images` folder on the website :)

**Comment by cstns** [comment]
> We should improve the format of the Team Invite e-mails whilst we're here too

I added this layout to all outbound emails sent by the FF platform. Content remains unchanged for all emails, just the surrounding wrapper with the new styling is new.

I can restrict the layout's use to a specific set of outbound emails, but I assumed that it was a global 'layout'

**Comment by cstns** [comment]
I altered the email templates in the sense that I've prevented the full url from being blurted in the link.

Here are a couple of examples (except EmailChanged, PasswordChanged & Safemode templates which I couldn't get to trigger easily):
- password-reset
![password-reset](https://github.com/FlowFuse/flowfuse/assets/20094749/4c00b3a8-25f7-4002-8fd8-f78837647eb9)
- pending-email-changed
![pending-email-changed](https://github.com/FlowFuse/flowfuse/assets/20094749/9e271529-5833-469a-9388-2537ceb91830)
- sign-up-screenshot
![sign-up-screenshot](https://github.com/FlowFuse/flowfuse/assets/20094749/8a83a49b-592d-4b77-9543-ce2d3f6ed93e)
- team-invitation
![team-invitation](https://github.com/FlowFuse/flowfuse/assets/20094749/971b1200-5780-4124-909f-4e9fc25a62c9)
- unknown-user-invitation
![unknown-user-invitation](https://github.com/FlowFuse/flowfuse/assets/20094749/c72e7faa-c6a7-4fcc-a1c9-ddbfc1bea9f9)
- username-changed
![username-changed](https://github.com/FlowFuse/flowfuse/assets/20094749/d27349e6-253c-4c5a-b2f8-895a9e3d5b60)
- user-suspended
![user-suspended](https://github.com/FlowFuse/flowfuse/assets/20094749/cc899d5f-533e-4cef-b21e-cfefaf85ad44)
- verify-email
![verify-email](https://github.com/FlowFuse/flowfuse/assets/20094749/0dae9671-9113-4f1d-a231-3d10a8c9a1da)

The templates behave ok on tablet and mobile layouts as well

**Comment by cstns** [comment]
One thing remaining to sort out is the fact that our HS email template included some UTM query params for the FF logo url. Should I take them into consideration or ignore them?
