### ISSUE TITLE
Unhandled Object.hasOwn is not a function

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#4047]
### Current Behavior

We are receiving the following fatal error via sentry

https://flowfuse.sentry.io/issues/5504281339/?alert_rule_id=14699916&alert_timestamp=1718734343931&alert_type=email&environment=production&notification_uuid=5538bc2a-a6d3-4ebe-82ab-36c6bd1a9d4c&project=4505958486441984&referrer=alert_email

### Expected Behavior

The error should not occur

### Steps To Reproduce

the message might not have the object prototype available

frontend/src/mixins/Dialog.js

### Environment

- FlowFuse version: 2.5.0
- Node.js version: n/a
- npm version: n/a
- Platform/OS: n/a
- Browser: n/a

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
Looking at the sentry report, the user is on Chrome 90 - which is three years old and doesn't support Object.hasOwn.

We either polyfill or remove use of hasOwn across the whole frontend codebase.

**Comment by cstns** [comment]
I found 11 occurrences in the FE codebase for .hasOwn
