### ISSUE TITLE
Allow user registeration on first sign-in via SSO

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#4051]
### Description

Our SSO support requires the user to already exist on the platform before they can use SSO to login. This is not the smoothest on-boarding experience for SSO customers.

We should allow the ability for an SSO user to be dynamically created when they first login via SSO.

The main question is how to obtain the profile information (full name etc) - whether that can be done from the information provided by the SSO provider, or if we should do a one-time prompt for a user to fill-out their details.

Marking as a customer request as this has been asked about a number of times.

 - https://app-eu1.hubspot.com/contacts/26586079/record/0-2/7226061033

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
Should this be a global setting or on a per SSO config? Would we turn this on globally for FF Cloud (if at all)?

A SMAL response should be able to provide more information about the use as part of the response.

Things to think about:

- what username should we create for the user (they are not going to use it but we need one). The SSO response will have one, but it may clash with other SSO provided usernames or existing usernames (see first question about global-vs-per-sso). We can't reuse the email as we limit username to `/^[a-z0-9-_]+$/i`
- do we assume email is pre-verified if it comes from SSO?
- The display name should be the only value we would need to ask for
- Add a random password (not used)

**Comment by hardillb** [comment]
OK, so the default SAML response (at least from Keycloak) doesn't include any profile data (name, username) only the email address and roles.

So we will probably have to ask for information, which makes things tricky as we will have an SSO authenticated session, but no user object to bind it to. This will be more complicated than I hoped.

**Comment by hardillb** [comment]
LDAP allows for the user filter to match on the username, which for a new user we won't have.

So even if the user tries to sign in with a email address the authentication step could still fail as it wouldn't have a username.

**Comment by knolleary** [comment]
We support ldap lookup via both username and email; it can be a documented restriction for auto-provisioning users via LDAP that the lookup has to be email based.

**Comment by SynoUser-NL** [comment]
> OK, so the default SAML response (at least from Keycloak) doesn't include any profile data (name, username) only the email address and roles.

If I understood my AD admin correctly a SAML response via EntraID would allow sending other properties to be sent within the response. This would have to be configured by the EntraID admin, who would need to map AD properties to the SAML properties to be sent. It would also allow some formatting of the response properties, as well as basic logic (if no value is present, send this instead).
https://learn.microsoft.com/en-us/entra/identity-platform/saml-claims-customization
But let me check with my colleague and get back to you on that, just to be sure.

**Comment by hardillb** [comment]
@SynoUser-NL yes, it is possible to add some more data to the SAML response, but we have to make sure we cover the minimal case as well.

e.g. We will pull the Full Name information if it's present (which it is from the test system we have EntraID) , but we can't just accept a username as we have to be confident it can't clash with any other users on the same system (who may be using different SSO providers) in a multi-tenant situation.

**Comment by hardillb** [comment]
Should this work usersign up is disabled?

I think it should, but want to check
