### ISSUE TITLE
Instance name is copied over when deploying DevOps Pipelines

### ISSUE THREAD

**Issue by DesiDera414** [FlowFuse/flowfuse#4058]
### Current Behavior

In DevOps Pipelines the first instance (name ending in 2741) is the source instance and the one ending in 4231 is the destination one. When deploying, the flows are deployed correctly but the name of the destination instance is now the same as the other one, which is confusing

![image](https://github.com/FlowFuse/flowfuse/assets/173454947/b83d1041-c8ed-439f-802c-54963ab7f10a)

### Expected Behavior

The name of the destination instance should be the same as before (the one ending in 4231)

### Steps To Reproduce

Create both instances, link them in DevOps Pipelines, and deploy from 2741 to 4231

### Environment

- FlowFuse version: Launcher version: 2.5.2-5843274-202406170826.0
- Node.js version: 20.14.0
- npm version:
- Platform/OS: cloud
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by hardillb** [comment]
Hello, a fix for this should have been published last week (https://github.com/FlowFuse/flowfuse/pull/4016)

Can you confirm if you change the title in the second instance settings back to what you want it to be it is still being overwritten when you run the pipeline

**Comment by DesiDera414** [comment]
It is still overwritten in that case

**Comment by hardillb** [comment]
Thanks for letting us know, I will investigate why the fix isn't working
