### ISSUE TITLE
Template has flows to pre-deploy

### ISSUE THREAD

**Issue by sammachin** [FlowFuse/flowfuse#406]
### Epic

#141

### Description

**As a:** user 

**I want to:** templates contain a set of pre-defined flows

**So that:** I can start a new project with an existing flow.

### Acceptance Criteria

- [ ] flow.json can be attached to a template

**Comment by sammachin** [comment]
Consider credentials too

**Comment by knolleary** [comment]
The Template model currently puts everything under a 'settings' json blob.

Whenever a project loads its settings we have to retrieve that blob and then overlay the project settings. So we need to be mindful of how big that settings blob gets.

Flows will have to work slightly differently to other Template settings:

1. When a Project is created from a Template that includes flows, we *copy* the Template flows into the `StorageFlow` (and `StorageCredentials`) tables. At which point, they are owned by the Project.

This means a Template does not provide a policy option around overwriting flows. 

If that is a requirement, we will have to iterate on it as it has complication with the Node-RED adminAuth setup in terms of what permissions a user has in the editor.

To store the flows/creds in a Template:

1. Create a new `ProjectTemplateFlows` database model (don't forget the migrations...)
3. Associate it one-to-one with `ProjectTemplate` (again - migrations!)
4. Add instance-level functions on `ProjectTemplate` to retrieve its associated flows.
5. The `ProjectTemplate` finders (eg `byId`) should *not* include the flows. That allows for light-weight lookup.
6. Wherever we return a ProjectTemplate over the API, it should not include the flows - but should include a flag to indicate if the Template includes flows.
7. New api `/api/v1/templates/:id/flow` (or should it be `flows`...) provided to GET/PUT/DELETE the flow/creds for the template.
8. For convenience, `POST /api/v1/templates` (create new template) should accept a `flow` parameter so the flow/creds can be provided in the initial create request.

The edit screens for Template should include a new section for 'Flows' - with large text input boxes to paste in flow json (and a second for credential json). The Vue handler for that section should only try to get the flow/creds from the API (see 6 above) when the user accesses the section.

**Comment by joepavitt** [comment]
This has been implemented with "Blueprints", albeit they're only available to be created by the platform administrator. For team members/owners, they have the option to use the Team Library in this case as a first iteration
