### ISSUE TITLE
Logged in users that manipulate the url and remove everything after the application domain land on a blank page.

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#4078]
### Current Behavior

Logged in users that manipulate the url and remove everything after the application domain land on a blank page.

### Expected Behavior

Users should be taken to their default team applications page

### Steps To Reproduce

Log in the platform, remove everything after the application domain and press enter.

### Environment

- FlowFuse version: 2.5.0
- Node.js version: N/A
- npm version: N/A
- Platform/OS: N/A
- Browser: Firefox

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
I cannot reproduce this myself. When logged in, if I open a new tab to `app.flowfuse.com`, or edit the url in an existing tab to that, then I end up on my default team's page as expected.

**Comment by cstns** [comment]
Apparently It's only happening on Firefox. Did not notice it until now

**Comment by cstns** [comment]
I updated the description

**Comment by knolleary** [comment]
Hmm, working for me with Firefox as well.

**Comment by cstns** [comment]
That's weird.. Here's how I reproduce it consistently

https://github.com/FlowFuse/flowfuse/assets/20094749/5adaa480-26f5-4aa9-ab64-7e7965fc7065

I cannot replicate it on chrome though.

**Comment by ZJvandeWeg** [comment]
@cstns I ran into it with Chrome today

**Comment by knolleary** [comment]
Can anyone who reproduces this check the browser console for any errors?

**Comment by cstns** [comment]
https://github.com/FlowFuse/flowfuse/assets/20094749/5f628d35-4cbe-4c97-bef0-46122f8530a0

This ignoreSurvey.js seems to be interacting with localStorage. Might be clashing with the recent vuex persistence in localStorage ?

**Comment by cstns** [comment]
The redirectUrlAfterLogin url is not cleared after the redirect occurred and that causes side effects in other locations in the app. This is now a problem because we're storing the redirectUrlAfterLogin in localStorage and it doesn't get cleared on page refresh.

The fix contains a 3 part fix:
- clear the `redirectUrlAfterLogin` after a route was accessed
- attempt to redirect to the `redirectUrlAfterLogin` if it's present when accessing the HomePage
- fix logo not doing anything when clicked after reaching this state
