### ISSUE TITLE
Create the possibility to define FlowFuse Admins by AD group.

### ISSUE THREAD

**Issue by SynoUser-NL** [FlowFuse/flowfuse#4085]
### Description

When SSO and Group Assertions is enabled, please  create the possibility to define which accounts are FlowFuse Admins by AD group.

### Which customers would this be available to

Enterprise Tier Only (EE)

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by knolleary** [comment]
My primary concern, and reason I descoped it from the original work, was that it opens up paths that can lead you to not having *any* admins on the platform. So a misconfiguration in this area could lead all of your admins marked as non-admin, and no longer able to edit the SSO configuration to fix anything. The only fix would be database surgery - which is not ideal.

I will look at how this is handled by other platforms; maybe I'm being overly cautious or maybe there's an approach that can help mitigate the risk.

**Comment by SynoUser-NL** [comment]
Don't think you're being overly cautious at all.. that may indeed be a risk if the SSO connection fails for some reason and authentication by SAML is not possible. Although if that happens there are usually other\bigger issues which need to be addressed first. And if those are solved, application access is usually restored as well.

I think it is a good idea to have non-SSO admin account(s) in an application exactly for that reason, with (very) strong passwords. I've seen software that, in the event authentication is not working for some reason, generates access information in the application logs. So only system admins (or collegues of..) who can access those are able to get to the information to access the application to restore\change settings.
Possibly enable SSO admins only if at least one non-SSO admin account exists. And have the application log access info as a last resort.

But that might be a nightmare to develop.. and there may very well be better and smarter ways to do this.

**Comment by robmarcer** [comment]
@knolleary you marked this as a customer request, do you know who requested it and if so can you post a HS link so we can let them know?

**Comment by knolleary** [comment]
@robmarcer they raised the issue themselves - so @SynoUser-NL will have been notified indirectly.

**Comment by SynoUser-NL** [comment]
Hi, yes I saw the issue was closed. And also that the documentation has been updated.
But I guess now I need to wait for the coming FF release to be able to use this feature. When this is released and we've updated our installation we'll gladly test and use it! :)

Thank you for implementing this feature!

**Comment by robmarcer** [comment]
Hi Den

It's on my 'to do' list today to let you know about this.

Please let me know how you get on and if you need any help.

Thank you
