### ISSUE TITLE
Template settings include Dashboard URL path that only applies to node-red-dashboard

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#4091]
We added the Dashboard URL path option to the instance settings template before DB2 was a thing.

With node-red-dashboard deprecated and focus on DB2, this setting is misleading as it has no affect on DB2 path.

<img width="394" alt="image" src="https://github.com/FlowFuse/flowfuse/assets/51083/21c35ba3-5c31-4110-b0f1-0f7b81b664c6">

We need to decide how to handle this.

Options:

1. Remove the option
2. Clarify text that this only applies to node-red-dashboard - that *is* what it currently says, but relies on user knowing the subtle different
3. Update DB2 to allow the root path to be customised and then apply this setting - could cause issues if user has both old and new dashboards installed as they will both try to use the same path
4. Something else...

**Comment by Steve-Mcl** [comment]
My vote: 
Option 2 (Clarify this is for Dashboard 1) + add 2nd row for Dashboard 2. NOTE however, this would be fixed/readonly with the value `/dashboard` in the first iteration until support for applying custom path is ready/possible

Mock up:

![Image](https://github.com/user-attachments/assets/fa580a52-1629-42ba-887b-182a6c0389a1)

@joepavitt thoughts?

**Comment by joepavitt** [comment]
Agreed, with a link on the note of "legacy Dashboard" to the forum deprecation notice

And a link to https://dashboard.flowfuse.com in the note for FF Dashboard
