### ISSUE TITLE
Update Test docs after adding the SMTP server for e2e tests

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#4099]
### Description

After the addition of https://github.com/FlowFuse/flowfuse/issues/3999, the e2e test dependencies were changed and are not reflected in the docs.

The docs should mention the fact that docker is now required to be installed locally in order to run the e2e test suites

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
I didn't know docker was now a hard requirement. Is there anyway to bypass those tests if you don't have docker installed?

**Comment by cstns** [comment]
There is a way to parametrize the the tests in order to avoid having docker installed (using it in CI) but there will be some tests that depend on it which will fail. I haven't updated the scripts to run without the smtp server but it can easily be done
