### ISSUE TITLE
Fix the support chat in the immersive editor

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#4111]
### Current Behavior

in google chrome the chat help icon is prevented from loading in the immersive editor

### Expected Behavior

the chat help icon/image should behave as in the rest of the application or none at all.

### Steps To Reproduce

open the immersive editor in production using chrome

![image](https://github.com/FlowFuse/flowfuse/assets/20094749/7a7e3519-205c-4d0a-9167-40d705628c66)

### Environment

- FlowFuse version: 2.6.0
- Node.js version: N/A
- npm version: N/A
- Platform/OS: N/A
- Browser: N/A

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
This morning, the chat icon is working fine. I *think* this was just a local chrome glitch as my laptop was having a bad time. If no-one else recreates it today, suggest we can close off.

**Comment by knolleary** [comment]
Closing as I haven't seen this happen since the original occurence.
