### ISSUE TITLE
Eng. Design: Notifications Schema

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4113]
We should establish an agreed upon schema for the `Notifications` objects to be stored in the database, and used around the application.

Some considerations:

- Short Title
- Long form description/detail
- Actions: probably a link to somewhere in the application (or external to docs/change logs?)
- Source:
    - Device - events linked to unexpected device state changes
    - Instance - events linked to unexpected Instance state changes
    - User? - Team invites may be linked to the sending user?
    - Team - Team invites may be linked to a team?
    - Platform/FlowFuse Team - Notifications manually triggered by us, detailing scheduled downtime, or new features that users may want to see?
- Timestamp
- State
    - Unread
    - Read
    - ???

**Comment by knolleary** [comment]
Having doing some research on how this type of feature is implemented elsewhere, I've come to the following high-level design points. tl;dr: a similar model to our audit log can be used

1. We will have a well-defined (in code) list of notification types.
2. The notification table (exact schema to follow) will store, `user`, `type`, `content` (json blob), `created_at` (sequelize default column), `unread` (boolean)
3. Each notification type will have a Vue component that renders the notification according to a template using the `content` property.

The `content` property, as a json blob, will contain any notification-specific meta data - for example, in the case an a team invite, it can contain team id/name, inviter name, role. The Vue component will have the template for how what title/description should be shown to the user for the notification - no need to store that in the database.

**Comment by knolleary** [comment]
## External API

 - `GET /api/v1/user/notifications` - returns notifications, most recent first. Uses pagination as per standard design
 - `PUT /api/v1/user/notifications` - bulk mark notifications read. Will mark *all* read by default
     - body params:
         - `id` - csv list of notifications to mark as read (optional)
         - `unread` - `true`/`false` (optional)
 - `PUT /api/v1/user/notifications/:id` - mark notifications read - defaults to marking all read for the user
     - body params:
         - `unread` - `true`/`false`
 - `DELETE /api/v1/user/notifications/:id` - delete a notification
 - `DELETE /api/v1/user/notifications` - bulk delete
     - body params:
         - `id` - csv list of notifications to delete (required)

**Comment by knolleary** [comment]
As the primary task is complete, closing this off - and moving on to #4158 to do implementation
