### ISSUE TITLE
Clearer UX Path for Updating NR Version

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4153]
### Description

See: https://eu.posthog.com/project/2209/replay/01909b5a-3398-7d2e-ad13-4df51078012c

User clicks the "Update" button, but then has to know to scroll down to then see _two_ options about updating/changing Node-RED version? Not sure why we show two options here? "Update" should be the priority?

Maybe a single row for "Change Node-RED Version" - with a primary button for "Change" and a secondary button for "Update" (if available)

The link from "Update" on the overview page should both change to the settings page _and_ then scroll down to the relevant action.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by cstns** [comment]
Having the cta buttons on a single line would break the alignment with the other options on the page. What I ended up doing is compressing the text and having the cta buttons on top of each other

![image](https://github.com/user-attachments/assets/2724b040-751a-4f09-b576-937437d801a8)
