### ISSUE TITLE
Carry on the search criteria when searching in the applications view when clicking on the x more tile and navigating to other pages

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#4167]

**Comment by Steve-Mcl** [comment]
As discussed here: https://github.com/FlowFuse/flowfuse/pull/4159#issuecomment-2223325030

**Comment by cstns** [comment]
Hit an inconsistency that would require me to take a small detour. We have search enabled and working for application devices but the same does not apply for application instances

**Comment by cstns** [comment]
Should I disable the ability to carry on search params to the application instances page or follow up with adding the functionality to search on the applications page?

@Steve-Mcl  @joepavitt please weigh in

**Comment by Steve-Mcl** [comment]
> Should I disable the ability to carry on search params to the application instances page or follow up with adding the functionality to search on the applications page?
> 
> @Steve-Mcl @joepavitt please weigh in

If it were up to me, I would add the search to the application->instances table first (a new/separate task) It has real benefit and provides a unified/consistent approach/UI (also, the table component search is already proven and pretty easy to add)

**Comment by joepavitt** [comment]
>  follow up with adding the functionality to search on the applications page?

Add it in please
