### ISSUE TITLE
Remove friction from signup flow

### ISSUE THREAD

**Issue by gstout52** [FlowFuse/flowfuse#4168]
The new user signup flow has a couple of unnecessary steps. They should be removed to decrease time-to-value for new users. This FigJam shows the friction points, marked with X: https://www.figma.com/board/mkOzyvy2b5Iu86xBpFaBZA/User-SignUp-Flows?node-id=501-104&t=X0CDt7s9pIeGcxJY-4 

1. Change the verification email link to authenticate the user without the user needing to return to the app and click 'Verify Email'.
2. Bypass the user re-entering their credentials from the signup page. (Backup if this is not possible: pre-populate the user's username as entered on the signup form).
```[tasklist]
### Tasks
- [ ] https://github.com/FlowFuse/flowfuse/issues/4174
- [ ] https://github.com/FlowFuse/flowfuse/issues/4199
```

**Comment by joepavitt** [comment]
@gstout52 can you move the FigJam into the "FlowFuse" team and then everyone will be able to see it

**Comment by gstout52** [comment]
> @gstout52 can you move the FigJam into the "FlowFuse" team and then everyone will be able to see it

@joepavitt I believe it is in the FlowFuse team - https://www.figma.com/files/project/97851883

**Comment by joepavitt** [comment]
Yep - my fault entirely, seems as though I have two Figma accounts for FlowFuse somehow 🤷 Browser was logging me into the wrong one

**Comment by joepavitt** [comment]
Closing as child tasks are completed
