### ISSUE TITLE
Improve verification email

### ISSUE THREAD

**Issue by gstout52** [FlowFuse/flowfuse#4169]
Upon signup, users are sent a verification email. That email can land in spam, likely because it is very brief, has no art or branding, and contains a url. See this screenshot of the email: https://www.figma.com/board/mkOzyvy2b5Iu86xBpFaBZA/User-SignUp-Flows?node-id=501-104&t=X0CDt7s9pIeGcxJY-4

This task is to add a FlowFuse email template with the goal of 'professionalizing' the email to hopefully avoid spam filters.

**Comment by joepavitt** [comment]
This _should_ have been update last week by @cstns in: https://github.com/FlowFuse/flowfuse/pull/4110

**Comment by gstout52** [comment]
> This _should_ have been update last week by @cstns in: #4110

**Comment by gstout52** [comment]
Closing this issue as a duplicate.
