### ISSUE TITLE
Require users to insert confirmation code on signup

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4174]
Draft workflow in Figma: https://www.figma.com/board/mkOzyvy2b5Iu86xBpFaBZA/User-SignUp-Flows?node-id=526-263&t=dGhMaHUwpM9tfZvL-4

This keeps users in the same browser session, and enables better tracking for us to ensure users are onboarding correctly.

It also prevents the need for user to click (what may appear to be) dodgy URLs in their onboarding e-mails to verify.

**Comment by joepavitt** [comment]
Not sure we could get this to log the user straight in though, may still need to step the path into the username/password page.

**Comment by knolleary** [comment]
1. User fills in signup page and submits. That creates the user with the `email_verified` flag set false. We also create a login session for that user.
2. When attempting to access the app in this state (`email_verified=false`) we force them to the 'enter a code' page.
3. Once the code is entered, `email_verified` is set to true. At which point the *existing* login session has full access. No need to reprompt for login details.

What I don't yet have is the specific detail of how we generate the login code, where we store it awaiting the user to confirm, and what new failure paths we have to handle. But all in, I'd said this a 1-2 days work.

**Comment by knolleary** [comment]
Verified on production
