### ISSUE TITLE
Add device type to the application devices response and include it in the search action

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#4176]
Follow up for https://github.com/FlowFuse/flowfuse/pull/4171

**Comment by hardillb** [comment]
@cstns just checking, this is for the `/api/v1/applications/:id/devices` route?

**Comment by cstns** [comment]
The api calls tha aggregate device info for the applications page are getTeamApplications (on the `/api/v1/teams/${teamId}/applications` endpoint) and getTeamApplicationsAssociationsStatuses (on the `/api/v1/teams/${teamId}/applications/status` endpoint) called from `frontend/src/pages/team/Applications/index.vue:231` and `frontend/src/pages/team/Applications/index.vue:273` respectively.

the device status should be included in the former. Once the data is available, a new rule should be added in `frontend/src/pages/team/Applications/index.vue:182`

While checking i noticed some calls being made to the endpoint you mentioned (triggered in frontend/src/pages/team/Applications/components/compact/DevicesWrapper.vue:135) but they don't seem to be used.

I should schedule a closer inspection and cleanup of the applications page to get rid of any redundant calls

**Comment by hardillb** [comment]
@cstns have a look at https://github.com/FlowFuse/flowfuse/pull/4904 and let me know if that covers everything please
