### ISSUE TITLE
Surface 'Invite Member' button

### ISSUE THREAD

**Issue by gstout52** [FlowFuse/flowfuse#4181]
### Description

**As a: new user**

**I want to: quickly and easily add other members to my FlowFuse team**

**So that: I can more quickly collaborate with my team and find value within FlowFuse**

Having clear 'invite teammate' button available in the UI without having to click into something else first is an effective way to encourage users to add new users. This UI change reduces friction for team creators seeking to build their FF team.

The 'Invite Member' button could be placed in the header between the Team dropdown menu and the user dropdown menu.

Estimate of effort: XS. 
The invite functionality already exists, this is just about placing a new button for that purpose.

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise

### Acceptance Criteria

- [ ] 'Invite Member' button appears in the header in the app.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Something like?

<img width="1281" alt="Screenshot 2024-07-16 at 09 26 16" src="https://github.com/user-attachments/assets/7ea14311-07e0-4c6e-9552-92d580d83389">

**Comment by joepavitt** [comment]
or, in the original position requested:

<img width="1278" alt="Screenshot 2024-07-16 at 09 27 51" src="https://github.com/user-attachments/assets/73141428-f372-4a5b-9b91-a25eaaa8bc93">

**Comment by gstout52** [comment]
@joepavitt Let's put it between the Team and user dropdowns - I think it better communicates that the 'invite members' button is for people to join the team listed in the dropdown.

**Comment by joepavitt** [comment]
Sounds like a plan - have added it to the dev board

**Comment by joepavitt** [comment]
PR #4186 is opened fyi @gstout52
