### ISSUE TITLE
Memory usage keeps increasing until the NodeRed instance crashes and restarts.

### ISSUE THREAD

**Issue by stytlus1234** [FlowFuse/flowfuse#4191]
### Current Behavior

I have only one instance running and starts at 200mb usage, memory is set to 512mb. The memory usage keeps increasing until the instance crashes which error rc=134 every 4h. I basically only use MQTT to read some values and the dashboard 2.0 to display them.

### Expected Behavior

The NodeJS V8 Garbage Collector was supposed to keap the memory usage in check but dosent seam to be working, even when the is almost nothing running the memory usage increases.

### Environment

- FlowFuse version: v2.6.0
- Node.js version: v20.15.1
- npm version: 
- Platform/OS: Windows 11
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
We will require an example flow that demonstrates this to be able to investigate.

Are you making use of the context to store data?

What range of data are you displaying, is it in a chart and how much history are you keeping?

What is the input data rate?

**Comment by stytlus1234** [comment]
I finaly found the origin of the problem today, and was the link call nodes Timeout that were always running, i had set the time on all of them to 9999s because of the timout error massages. To solve the problem i set them all to 30s and added return nodes on the other side, so the timeouts reset and release the memory. The timeout shoud be and option, the link in, and link out nodes shoud have the option to set the target dynamically.

I'am going to close the issue.
