### ISSUE TITLE
Instance templates settings get overwritten when deploying different instance using pipelines

### ISSUE THREAD

**Issue by michelebrami** [FlowFuse/flowfuse#4198]
### Current Behavior

Locked instance template settings are overwritten when deploying flows using a pipeline from a different instance.

Template:
![2024-07-17_16-49-50](https://github.com/user-attachments/assets/b6b9fcd9-a143-44a4-9f1d-e99f4561cc22)

Deployed Instance:
![2024-07-17_17-00-05](https://github.com/user-attachments/assets/7599f543-88bf-4360-9b10-7f231d9d951c)

### Expected Behavior

I expected the locked settings to be maintained even in case of a deployment from another instance template. I observed that the settings are still marked as "locked" (with a tiny lock icon), but the saved value is reverted to the value that is set in the source instance.

### Steps To Reproduce

I set up an instance template where I disabled the editor and other settings, then I locked the settings and saved.
I created a "PRD" instance using that template and a pipeline that deploys node-red flows to that instance.
I created a "DEV" instance with a different template (with no locked settings) with all settings enabled.
I ran the pipeline to deploy from DEV to PRD

### Environment

- FlowFuse version: 2.5.0
- Node.js version: 16.20.2
- npm version: 10.7.0
- Platform/OS: Openshift/Alpine Linux V3.20
- Browser: Windows/Edge 126.0.2592.102

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
Hi @michelebrami 

I believe this was fixed in our 2.6.0 release via - https://github.com/FlowFuse/flowfuse/pull/4059

**Comment by knolleary** [comment]
That said, the fix we did in 2.6.0 was limited in scope to a subset of all template settings; the ones that didn't make sense to copy via pipeline: `disableEditor`, `page_title` and `header_title` . That doesn't address the full extent of your issue.

We didn't take into account the locked settings - where you may have different templates with different policies. In FFCloud we only have one template - so not a scenario we'd considered.

**Comment by joepavitt** [comment]
This can be closed, right?
