### ISSUE TITLE
Inconsistent behaviour of "Invite Members" toolbar button

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#4200]
### Current Behavior

![chrome_UCJacseJyx](https://github.com/user-attachments/assets/c14a5245-2e0d-4acc-931c-77b500ad722b)

* button only works on overview pages
* button does not work on the invites page (not too problematic as there is a duplicate in the table search bar that does work)

### Expected Behavior

Not sure, but as it is it only works on certain pages.

### Steps To Reproduce

visit any instance, application or device - button does not work

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Thanks for flagging Steve - re: the same page button, I was aware of that, we could put in a quick fix, but didn't think it too important. 

RE: the overview page, that's an odd one, I'll dive in now and investigate.
