### ISSUE TITLE
Deleting instance when on team overview page does not refresh the list

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#4203]
### Current Behavior

Deleting an instance via its drop-down on the Applications view works, and you get the toast notification that the delete succeeded, however the instance remains in the view until you refresh the page.

<img width="751" alt="image" src="https://github.com/user-attachments/assets/dede4a61-300e-42ef-988f-e9774b91aaef">

### Expected Behavior

Instance to disappear from the view once deleted

### Steps To Reproduce

- Delete an instance via the dropdown menu on the Application view

### Environment

- FlowFuse version: 2.6
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by cstns** [comment]
fixed in https://github.com/FlowFuse/flowfuse/pull/4322
