### ISSUE TITLE
Be able to set HTTPNodeAuth settings for a device agent

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#4204]
### Description

Either set these in the `device.yml` or push them down from the forge app.

If in the device.yml then the following needs to be taken into account https://github.com/FlowFuse/flowfuse/issues/4185

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Closing as duplicated byhttps://github.com/FlowFuse/device-agent/issues/317
