### ISSUE TITLE
Don't show NR editor product update to new users

### ISSUE THREAD

**Issue by gstout52** [FlowFuse/flowfuse#4212]
### Epic

#3839

### Description

**As a user visiting the Node-RED editor for the first time**

**I want to explore the features of Node-RED as I find them**

**So that I am able to quickly become adept at using the editor.**

By default, new users are shown the most recent product update when they land in the Node-RED editor for the first time. This is not an ideal experience, as for the new user, the most recent product update is equivalent to the current product. 

The ideal experience is:
- New user receives a welcome, not the previous product update notification. (The new user welcome is being worked on separately.)
- All users receive product updates that went live only after the time that the user signed up.

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise

### Acceptance Criteria

- [ ] New users receive no product update message the first time they land in the NR editor.
- [ ] Users receive all in-app product updates that are pushed live after the user signs up.

Initial effort estimate: S
This change will require changing the conditions under which users receive a product update, so I expect this is not a XS effort, but not much more than one.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
The Welcome Tour is a built-in feature of Node-RED. We *do* expose the option to disable it in the Instance Settings, but it is all or nothing.

We don't have the ability to selectively turn it on/off depending on who is accessing the editor - nor if this is a 'first time' accessing the editor ever, vs first time accessing since upgrading (when arguably we would want to let them know what's new).

If we want to turn if off for everyone, then it's a tick of this box in the default template:

<img width="412" alt="image" src="https://github.com/user-attachments/assets/cb843306-1308-49bf-964b-fa33e0986885">

If we want some more dynamic logic around it, we need to figure out the desired rules of when to show it, and then figure out how to make that happen.

**Comment by gstout52** [comment]
> The Welcome Tour is a built-in feature of Node-RED. We _do_ expose the option to disable it in the Instance Settings, but it is all or nothing.
> 
> We don't have the ability to selectively turn it on/off depending on who is accessing the editor - nor if this is a 'first time' accessing the editor ever, vs first time accessing since upgrading (when arguably we would want to let them know what's new).
> 
> If we want to turn if off for everyone, then it's a tick of this box in the default template:
> 
> <img alt="image" width="412" src="https://private-user-images.githubusercontent.com/51083/350324082-cb843306-1308-49bf-964b-fa33e0986885.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MDM5NDUsIm5iZiI6MTcyMTQwMzY0NSwicGF0aCI6Ii81MTA4My8zNTAzMjQwODItY2I4NDMzMDYtMTMwOC00OWJmLTk2NGItZmEzM2UwOTg2ODg1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDE1NDA0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNjMGQxODJmNTA4YmFhNmI5MzQ2MmE3Nzk5OTdiYmQ1OGU2ZDhhOGFlYjE1MzMwOGJhYjk4ZDJmYTEyMTg5MmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.w7P5eHyjwvkvoika7-YozkDCRlYIfAbcLX8hswRujaI">
> If we want some more dynamic logic around it, we need to figure out the desired rules of when to show it, and then figure out how to make that happen.

Okay, let's leave this as-is for now. I don't want to disable it by default without an alternative welcome in place, because then users are faced with an empty state. We can switch it to off by default once there is a new welcome ready to ship.
