### ISSUE TITLE
External invites stripping '.' from email addresses

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#4222]
### Current Behavior

In staging/production (but *not* when testing locally), if I invite a user with the email `nick.oleary+testing@example.com`, the invitation in the database is saved as `nickoleary+testing@example.com` - the `.` has been dropped.

I cannot currently explain why this is staging/prod only - and cannot be recreated locally.

### Expected Behavior

Invite should be saved with the email as-provided

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Does this mean that the e-mail isn't then sent to the correct e-mail address either? i.e. everyone that's been invited to FF with a `.` in their e-mail address wouldn't have received it?

**Comment by knolleary** [comment]
Some email providers ignore the `.` - such as gmail - so an email sent to `foo.bar@example.com` will end up in the same place as `foobar@example.com`. This isn't universal however.

I'll have a dig into the SES logs to see if we have any data on bounced emails; at a glance I can say we have had no bounces in the last two weeks (as that's as much I as I can see in the SES dashboard without digging deeper).

**Comment by knolleary** [comment]
> Have identified the bug - and it's solely related to gmail domains.

To be super clear, the stripping of `.` only happened with gmail addresses as part of our logic to deduplicate the list of invites. Gmail accepts emails with the `.` - so no invalid emails would have been sent.

This is fixed via #4232
