### ISSUE TITLE
Change error message for users without access

### ISSUE THREAD

**Issue by gstout52** [FlowFuse/flowfuse#4241]
### Description

A Viewer user who does not have instance editing privileges can still make changes, but upon attempting to deploy them receives the error message "You must be logged in to make changes." This is confusing because the user is logged in, but they lack the privileges to make changes. Ideally, this user would be (1) unable to move and change/add nodes or their properties, or (2) receive an error message like "You need a Member or Owner role to edit Instances. Contact your Admin to change your role."

Estimate of effort: XS if this is just a copy change, S-M if more work is required to prevent Viewer users from seeming to make changes.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
This particular error message is one generated by Node-RED when a user with read-only access tries to make a change. It isn't a message we can easily customise in the FlowFuse context.

That said, with Node-RED 4.0, we did make some UX improvements around this scenario; the Deploy button now remains disabled and shows a lock icon - so they cannot hit deploy. See https://nodered.org/blog/2024/06/20/version-4-0-released#better-feedback-for-read-only-users for details.

**Comment by gstout52** [comment]
Okay, that sounds good for now!
