### ISSUE TITLE
Devices actions kebab menu in application view do nothing

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#4246]
### Current Behavior

clicking any of the actions on the kebab of a device does not do anything

![chrome_AiTnkLgJIj](https://github.com/user-attachments/assets/79a74a58-41f6-4fb9-92ca-15b9460cce7c)

### Expected Behavior

Should perform the action described

### Steps To Reproduce

open application view, select the kebab menu for a device

### Environment

- FlowFuse version: 2.6.x (Prod)
- Node.js version:
- npm version:
- Platform/OS:
- Browser: chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
I fixed this locally - found the compact view passes `devices` to the mixin as an array but there were some left over `.set` and .delete` `map` methods causing exceptions (that are _helpfully_ swallowed by vue)

So I fixed up the 3 places where `this.devices` were still calling `map` methods to use `array` methods.  that fixed it up nicely - however - the Applications->Device vue is now broken. 

Seems the I am still getting a `map` object from other views

**Comment by joepavitt** [comment]
Just confirming, this is _not_ fixed by #4252 - this is a different problem

**Comment by Steve-Mcl** [comment]
> Just confirming, this is _not_ fixed by #4252 - this is a different problem

Yeah, it is a separate issue. It is resolved locally by handling both Maps and Arrays. This is the approach I took for quickest, least disruptive approach - BUT - I am including E2E tests to ensure the correct dialog IS actually shown. This way, once once the MAP vs ARRAY thing is resolved we will have e2e tests already in place to ensure it continues to work as expected.
