### ISSUE TITLE
Device Kebab Menu missing "Remove from..." menu item

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#4249]
### Current Behavior

The "Remove From ..." kebab menu item is missing from the Device Tile (used in compact applications view) even though it is present in src.

* Device Tile: https://github.com/FlowFuse/flowfuse/blob/ff458764cd76e8471e82e4fce1a7edad024626ba/frontend/src/pages/team/Applications/components/compact/DeviceTile.vue#L24-L35
![image](https://github.com/user-attachments/assets/718a4878-c8db-4ba0-93fa-fc614db49dcd)

* Device Browser:  https://github.com/FlowFuse/flowfuse/blob/ff458764cd76e8471e82e4fce1a7edad024626ba/frontend/src/components/DevicesBrowser.vue#L84-L101
![image](https://github.com/user-attachments/assets/d511012e-91d5-4a4d-a087-3764d8ad7510)

### Expected Behavior

Menu items should be present as coded

### Steps To Reproduce

visit applications view with devices and open the kebab menu

### Environment

- FlowFuse version: 2.6.x Live (PROD)
- Node.js version:
- npm version:
- Platform/OS:
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
Once this is resolved, it will be necessary to update the E2E tests as discussed here: https://github.com/FlowFuse/flowfuse/pull/4253#discussion_r1691194702

**Comment by cstns** [comment]
Did a little digging yesterday and I think I managed to find the problem. The devices in the applications view do not have the ownerType present. 

I'll try to expose the key
