### ISSUE TITLE
Team applications page not loading in Brave browser

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#4291]
### Current Behavior

After logging in using the Brave browser, the team/applications page shows the 404 page.

Customer reporting with version 1.168.128 of Brave  (on OSx ARM64)

![image](https://github.com/user-attachments/assets/68449940-6e16-4761-b77d-0f264a567eb7)

No obvious errors in the console, but the network tab does not show the loading of the page (the forge app logs do show it)

### Expected Behavior

Team page should load and show applications

### Steps To Reproduce

Try and log into the FF Cloud using Brave browser.

### Environment

- FlowFuse version: v2.6.2-4f52ff4-202407301232.0
- Node.js version: 18.x
- npm version: 9.x
- Platform/OS: K8s/Linux
- Browser: Brave

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
The outcome of this issue very similar to issue customer found recently where they were being invited in as a Dashboard-only viewer into a team. The Team PI was barfing as they didn't have permissions to read the relevant dat - and so the Team Selection (and teams) never loaded.

Note there, no Team Selection in the top-right, so it's that API call failing (or returning some dat the front-end doesn't like) that'll be causing this.

**Comment by joepavitt** [comment]
Similar issue in terms of the UX presented to the user: https://github.com/FlowFuse/flowfuse/issues/4214

Almost certainly a different cause though given that this user reports they were signing up for a new account

**Comment by hardillb** [comment]
The network tag in the console didn't show anything other than 200 status and it works with Chrome

**Comment by joepavitt** [comment]
Reproducible (in any browser) with this workflow: https://node-red.slack.com/archives/C02V3BN77GU/p1722435078496179?thread_ts=1722424753.194309&cid=C02V3BN77GU

**Comment by hardillb** [comment]
This feels very like the problem I fixed yesterday, e.g. the posthog api calls not being wrapped in try/catch blocks

**Comment by hardillb** [comment]
I've tested this with Brave and I can see all the Posthog requests getting blocked, so I am 99.9% sure this is the same as the locked down network problem fixed by #4508 

I will move to done for now, we can reopen if needed
