### ISSUE TITLE
Delete Account with Team Deletion

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4292]
### Description

When deleting an account, users need to delete their team first. Whilst prompted, the settings for this are in a different place and not intuitive path to go between these locations.

If I am the only member of a team, that team has no instances, and I choose to delete my account - it should deleted both my account _and_ my team in one hit.

### Which customers would this be available to

None

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by cstns** [comment]
@joepavitt, if the user trying to delete the team is the only owner but the team has other members, should we proceed with the team deletion?

**Comment by joepavitt** [comment]
Good question - @knolleary - thoughts? I'd probably go with "no", as they're the kind of teams we want reaching out to us so that we can understand _why_ they're churned

**Comment by knolleary** [comment]
I'd stick with only deleting if they are the last person in the team.

**Comment by cstns** [comment]
OK, sound's good!

Should I also check for device presence?

**Comment by joepavitt** [comment]
@cstns two options:

- We do a sanity check first to see _which_ teams can be deleted, _then_ delete if they all can
- As you've said, delete what we can, don't delete the full account, and then flag the remaining teams need to be dealt with.

The first option is the "proper" way imo

**Comment by knolleary** [comment]
I'm reverting the PR that fixes this as it introduced a bug that left teams orphaned with active stripe subscriptions. I'm out of time to fix today, so reverting to prevent it happening further over the weekend. Will rework the original PR on Monday.

**Comment by knolleary** [comment]
The original fix has been reapplied with the additional fixes - https://github.com/FlowFuse/flowfuse/pull/4531
