### ISSUE TITLE
Incorrect validation feedback when creating instance

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#4299]
### Current Behavior

Name set (autogenerated) but I forgot to select **Application** - validation error is incorrectly shown beneath **Instance Name**!

![image](https://github.com/user-attachments/assets/dc330887-5731-4141-861e-c2c49d652720)

### Expected Behavior

Validation error should be shown on the **Application** not the **instance name**

### Steps To Reproduce

1. Navigate to "Instances"
2. click "Create Instance"
3. set everything except Application and click "Create Instance"

### Environment

- FlowFuse version: 2.6.x (Prod)
- Node.js version:
- npm version:
- Platform/OS: FFC
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
Hit this one too many times this week; for the sake of 10 minutes work the fix is in #4462
