### ISSUE TITLE
Visual Timeline of Version History

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4304]
Provide a visual representation of the work and data collected in #4305 

The view should:
- Make it clear when flows are deployed
- Who deployed them
- Allow for inspection of changes
- Rollback to a particular snapshot in time

**Comment by Steve-Mcl** [comment]
hmmmm. I feel like I would want to see interleaved snapshots so I have context within the timeline (of which one to chose).

**Comment by hardillb** [comment]
Is Activity what was Audit logs?

Having markers for snapshots would let you know where you could roll back to

**Comment by cstns** [comment]
I like the toggle view!

I'm with @Steve-Mcl on this one, I'd like to know when the snapshot was taken to know what was captured in between steps

**Comment by joepavitt** [comment]
Yep, you've both made the same point - so I'll see if I can capture this somehow. I don't think, hierarchy-wise, it belongs in the same prominence as these events, I'll have a play - thanks all

**Comment by joepavitt** [comment]
<img width="890" alt="Screenshot 2024-10-01 at 15 27 12" src="https://github.com/user-attachments/assets/9cfa3e3f-153c-4ce9-bf72-01576f60e5e5">

Something like this? Where this is a busy example with auto snapshots enabled

**Comment by Steve-Mcl** [comment]
Looking good Joe.

Would you conder a way of getting the snapshot desc in there somehow? Perhaps a popover? The description can be vital in determining the viability of the snapshot.

Additional Q: Do you expect the kebab menu to offer the ability to "view" the snapshot?

**Comment by joepavitt** [comment]
> Would you consider including a means of getting the snapshot desc in there somehow? Perhaps a popover? The description can be vital in determining the viability of the snapshot.

I will try

> Additional Q: Do you expect the kebab menu to offer the ability to "view" the snapshot?

Whether it's kebab or not, haven't yet decided, but a "view" snapshot, restore, etc. would all make sense
