### ISSUE TITLE
Password reset email not sent

### ISSUE THREAD

**Issue by gstout52** [FlowFuse/flowfuse#4325]
### Current Behavior

If a user fails to enter their login credentials, they have the option to follow the Forgot Password path from app.flowfuse.com. I am experiencing a failure of the system in sending the reset email to me.

1. I enter my email address at https://app.flowfuse.com/account/forgot-password 
2. I click Send Reset Link
3. The email does not come through.

### Expected Behavior

1. I enter my email address at https://app.flowfuse.com/account/forgot-password 
2. I click Send Reset Link
3. I receive an email with either (a) a way to recover my password or (b) a way to create a new password.

### Steps To Reproduce

1. I enter my email address at https://app.flowfuse.com/account/forgot-password 
2. I click Send Reset Link
3. The email does not come through.

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS: Sonoma 14.5
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by hardillb** [comment]
Is this your work email or a personal address?

If personal what domain  (can post to slack if you don't want it in public), just the bit after the `@`

Have you looked in your spam folder?

**Comment by gstout52** [comment]
@hardillb Personal email ending in @outlook.com. I've checked all folders.

**Comment by hardillb** [comment]
The email address for password resets needs to be an exact match to the one entered when creating the account

foo+bar@example.com will not match foo@example.com

Also the email address given when creating the FlowFuse account doesn't need to match the one given to Stripe (to allow invoices to be sent to billing department...)
