### ISSUE TITLE
Set default team based on team invitations if present

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4333]
### Description

If a new user is invited to FlowFuse to an existing team, we still create their default/personal team as part of our onboarding workflow, however, we want the _default_ team to be that of the one they're invited to.

This has caused [confusion](https://github.com/FlowFuse/customer/issues/231) when onboarding Enterprise teams as each user has been presented with the billing page (due to the personal teams being created)

Each user has a "Default Team" option, we should ensure this is set based on the team invitations, rather than the personal team created.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
If people are being invited to a team, should we be creating a personal team (and a initial instance)?

I would suspect that most of these will end up just spinning out the trial period untouched. (This is just gut feel, as until the suggested change is made we don't have any data)

**Comment by joepavitt** [comment]
@hardillb It's definitely an option, and I'm happy for that to be the better play here - @knolleary @gstout52 any thoughts?

**Comment by knolleary** [comment]
It is certainly a valid choice to not create their personal team. That will, however, mean they don't get any free trial. That is probably okay as they are being explicitly invited to a team so the buying decision has already been made elsewhere.

I wonder if we can look to see, for any existing users who joined as a result of an invite, whether they go on to make use of their personal team - or if their activity was only in the team they were invited to. Not 100% sure if we have the data to look at that purely in the platform - may need some correlation with PH/HS.

**Comment by gstout52** [comment]
I favor Ben's idea!

The goal is just to make it possible for Sales to set up a free Enterprise trial and let the point of contact invite more users. I don't see it as a problem to have have a free Starter team created for them along with joining their Enterprise team.

**Comment by joepavitt** [comment]
Let's move forward with Ben's approach - have assigned to Ben to start next week once he's back

**Comment by hardillb** [comment]
Looks like the code would already do this, but it was being run after the code to create the personal team. fix was just to move the code up a little.
