### ISSUE TITLE
Custom Catalogue and NPMRC settings are totally hidden when not available to the user

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#4342]
### Current Behavior

On the Instance -> settings -> palette page the options to add custom cataloge or npmrc are removed if not available to the user's team.

### Expected Behavior

The options should be visible, but disabled and the sparkles showing message about available if team upgraded.

### Steps To Reproduce

Start a CE instance of FF
Create instance
look at settings page.

### Environment

- FlowFuse version: 2.7
- Node.js version: 18 
- npm version: 9
- Platform/OS: all 
- Browser: all

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by cstns** [comment]
Here are some prototypes:

- v1
![npm-config_v2](https://github.com/user-attachments/assets/6932dbc6-347d-4680-a6a3-489fcefd3222)

- v2
![npm-config_v3](https://github.com/user-attachments/assets/68783c39-6250-45a5-9c73-59e4193f3a7d)

-v3
![npm-config_v1](https://github.com/user-attachments/assets/b1f770c7-50fb-40c5-8c08-f5bf0875c174)

I'd appreciate some input! The placement is what I'm concerned about at the moment, not the message per say

**Comment by joepavitt** [comment]
v1, but the text left-aligned rather than central please. Can we also grey-out the heading too?

**Comment by joepavitt** [comment]
and modify the background of the textarea to be off-white so that it's more apparent it's in a disabled state

**Comment by cstns** [comment]
I only disabled the textarea for the prototypes, will see what I can do about it
