### ISSUE TITLE
Test NR instance crashed after FF 2.7 upgrade, not starting again

### ISSUE THREAD

**Issue by SynoUser-NL** [FlowFuse/flowfuse#4353]
### Current Behavior

After upgrading Flowfuse to V2.7 and upgrading our Test NodeRED instance, the instance crashed. We were not able to start the instance again.
Error report: { "error": { "code": "unexpected_error", "message": "Failed to start project 26000286-0f11-46ec-8981-d9d16b6bc0ea: TypeError: Cannot read properties of undefined (reading 'options')" } } 

### Expected Behavior

Updating instances should not return an error.

### Steps To Reproduce

- Update FlowFuse from v2.6.1 to v2.7
- Update NodeRED instance stack

### Environment

- FlowFuse version: 2.7
- Node.js version: 20.15
- Platform/OS: docker

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
Hi @SynoUser-NL 

Can you check if you pulled 2.7.0 or 2.7.1? The fix for that error went into 2.7.1.

**Comment by SynoUser-NL** [comment]
Hi @knolleary ,
Update to 2.7.1 worked with the NodeRED instance not starting. Thanks!
Small detail: Launcher version and Forge Application still display as 2.7.0 instead of 2.7.1. Just FYI.
