### ISSUE TITLE
Provide "Access/Visibility" property for folders

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4359]
Extending https://github.com/FlowFuse/nr-launcher/issues/273 to include details on a public HTTP path (if asset is sto to "Public" visibility

User/API will need to support:

- Change Folder Visibility (Node-RED Only, HTTP Public Access) - https://github.com/FlowFuse/nr-launcher/issues/274
    - Define HTTP Endpoint

**Comment by knolleary** [comment]
This task was to cover how we store/configure the sharing options for individual directories.

That has rolled into https://github.com/FlowFuse/flowfuse/issues/4357 - with the `share` property that is exposed on the API.

To avoid headaches, going to close this issue as a it isn't required as a separate task.
