### ISSUE TITLE
Notify team inviter when an invitation is accepted

### ISSUE THREAD

**Issue by gstout52** [FlowFuse/flowfuse#4379]
### Description

**As a user who has invited another user to my FlowFuse team**

**I want to receive a notification when the person I invited to FlowFuse joins my team**

**So that I can easily verify that the colleagues I have invited to my team have joined my team**

**Current Behavior**

If I invite a user to join my FlowFuse team, the user I invited (the invitee) receives an emailed invitation to join my team.

If the user joins, I am not made aware of this.

If the user does not join, I am also not made aware of this.

**Desired Behavior**

When the invitee joins, the inviter receives an email confirming this.

### Which customers would this be available to

None

### Acceptance Criteria

- [ ] When an invitee accepts a team join invitation, the inviter receives an email confirming this.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
Have the foundation product work in place for this:

<img width="522" alt="Screenshot 2024-08-15 at 20 10 34" src="https://github.com/user-attachments/assets/f90f5bde-a84e-4d2c-8ec1-6b3d62a2caa8">
