### ISSUE TITLE
Send reminders to team inviters and invitees if invitee doesn't join

### ISSUE THREAD

**Issue by gstout52** [FlowFuse/flowfuse#4380]
### Description

**As a user who sends or receives a team join invitation**

**(if invitee) I want to be reminded if I forget to join a team I was invited to, or (if inviter) be reminded if someone I invited has not yet joined**

**So that (if invitee) I participate in FlowFuse when my team needs me, or (if inviter) I ensure that the right team members are in FlowFuse**

**Current Behavior**
Currently, after a user sends an invitation to join, there is no follow-up of any kind to the inviter.
Currently, after a user receives a team join invitation and does not accept it, there is no reminder message sent.

**Desired Behavior**

If two days after sending an invitation the invitee has not joined the team, then:
- The invitee receives a reminder email
- The inviter receives an email stating that the invitee has not yet accepted

### Which customers would this be available to

None

### Acceptance Criteria

- [ ] If two days after sending an invitation the invitee has not joined the team, then the invitee receives a reminder email
- [ ] If two days after sending an invitation the invitee has not joined the team, then the inviter receives an email stating that the invitee has not yet accepted

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
This one is a little trickier, and is likely to need some HS intervention, as not sure we can reliably track this within the source/product itself

**Comment by joepavitt** [comment]
We do have "housekeeper" tasks that run intermittently, so is actually doable.

**Comment by knolleary** [comment]
I suspect we have a lot of 'dormant' invites - we may want to tidy them up before we start sending reminders.

**Comment by hardillb** [comment]
316 invites in the DB at the moment, but large number look to be expired.

Will add a housekeeping task to remove expired invites as part of the work

**Comment by knolleary** [comment]
> If I use a fixed time everyday to run it, I should be able to check for creation dates, more than 2 days ago and less than 3.

Sounds good to me.

**Comment by joepavitt** [comment]
@hardillb this can be closed, right?
