### ISSUE TITLE
Separate Themes In DevOps Pipelines Instances

### ISSUE THREAD

**Issue by Skaedian** [FlowFuse/flowfuse#4418]
### Description

Reference: https://discourse.nodered.org/t/separate-themes-in-devops-pipelines/90503

Currently, when using DevOps Pipelines, if you have a dark theme applied to your development instance and you deploy to your production instance, the production instance will also apply a dark theme. 

It would be handy if the Production and Development instances in a DevOps Pipeline could have separate themes to assist with identifying the instance better (my team has a standard where our development instances are dark-themed, while our production instances are light-themed). 

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by hardillb** [comment]
What version of FlowFuse are you using?

**Comment by hardillb** [comment]
re: https://github.com/FlowFuse/flowfuse/issues/3920

**Comment by Skaedian** [comment]
Hi @hardillb 

Our version is:
    Forge Application | v2.6.1
    NodeJS | v20.14.0

**Comment by joepavitt** [comment]
Thanks @Skaedian - difficult as a key driver of the DevOps pipeline is the ability to move over the _full_ flow/settings. We could look to introduce the ability to make particular options/content not transfer as part of the DevOps Pipeline, though this wouldn't be a _quick_-win

**Comment by hardillb** [comment]
closed by #4425
