### ISSUE TITLE
Assets upload dialog 2nd upload of same asset not possible

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#4421]
If I select the same file to upload a 2nd time, it does not populate the text element nor does it enable confirm button

_Originally posted by @Steve-Mcl in https://github.com/FlowFuse/flowfuse/pull/4384#pullrequestreview-2268169637_

**Comment by joepavitt** [comment]
Two layers to this:

1. Make it clearer why the button is not available
2. Support version control (which is an "out of MVP scope" item in https://github.com/FlowFuse/flowfuse/issues/4194)

**Comment by Steve-Mcl** [comment]
I am referring to the first in this follow-up...

1. Select an asset to upload e.g. `text.txt`. 
3. Select the same asset to upload again.`text.txt` 

The text portion of the dialog is not filled in. 

However, if I upload something else first then I select text.txt it works. Even in the same folder.

**Comment by joepavitt** [comment]
Thanks Steve - I suspect that means the `@change` event is not being cleared correctly, so we need to clear the selection upon cancel/upload the first time around

**Comment by Steve-Mcl** [comment]
Added to dev board and marked as bug. We should try to get fix rolled out before users report it 🤞

**Comment by cstns** [comment]
closng as resolved in https://github.com/FlowFuse/flowfuse/pull/4427
