### ISSUE TITLE
API for Deployment History of an Instance

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4424]
Request to have a single API endpoint, e.g. `api/v1/projects/{instanceId}/history` that returns details on every deployment made to that instance in the context of version history.

If I'm not mistaken, the sources for these deployments would be:

- Node-RED Editor - user has clicked the "Deploy" button themselves
- DevOps Pipeline - where we would want detail on where the flows came from
- Rolback Snapshots

A lot of these I think could be gathered from the Audit Log (and reformatted appropriately). 

It is also important to verify if each of these steps in the `history` have an available snapshot that we can revert to. Part of this work is to also determine if there are actually new tables or events we need to be recording in order to support this functionality.

**Comment by joepavitt** [comment]
> For example, are expecting to be able to display individual changes to settings or flows? That would take either capturing all settings and flows (or a delta) with each "change".

My expectation would be a `flow.json` at each stage, then we can just calc the diff as required, rather than storing the diff at each stage which gets messy given their varying sources.

> Another level of detail is what version of the launcher was an instance running on. 

TMI for the customer I think. They care about their flow deployments, not underlying hardware/installation stack. This is just a history of the work the user has explicitly pushed to the flows, i.e. the `flow.json`

**Comment by Steve-Mcl** [comment]
@joepavitt the [grandfather issue](https://github.com/FlowFuse/flowfuse/issues/3574) states:

> ### Which customers would this be available to
> Other - Open for discussion


I am working on the assumption this is a feature for everyone, but I will need to know sooner rather than later if it is for licensed only and also whether this will require a feature flag (for team type specific enable/disable)

**Comment by joepavitt** [comment]
I'd say it's Team/Enterprise. It's around audit-ability and compliance, but also would be a fundamental feature for future Version Control, which is then relevant for Team. Let's go "Team".

**Comment by Steve-Mcl** [comment]
FYI. Following up on this. Nick and I had a meeting to resolve the situation and the PR has been updated to address concerns.

**Comment by Steve-Mcl** [comment]
@joepavitt API output examples here: https://github.com/FlowFuse/flowfuse/pull/4509#issuecomment-2358483015
