### ISSUE TITLE
Add warning to Assets tab if instances template excludes 10-file.js

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#4447]
### Current Behavior

Users with instances that use "Default v1" templates have the core file nodes replaced by the FF modified version that works with the file-server.

This means they can't access the new persistent storage directory

### Expected Behavior

Give a message to contact FF Admin to edit instance settings to remove `10-file.js` from excluded nodes list.

(may also want to copy over any files from the old system)

### Environment

- FlowFuse version: 2.8.0
- Node.js version: 18.x
- npm version: 9.x
- Platform/OS: FF Cloud
- Browser: All

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by cstns** [comment]
How would one know when to display the message?
