### ISSUE TITLE
Different pictogram on instances info popup to its empty state

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#4450]
### Current Behavior

![image](https://github.com/user-attachments/assets/21b34ba1-6c25-49d7-a69a-8a427a091b34)

### Expected Behavior

Like "applications" and "devices" the pictograms in the info popup should be the same as the empty state pictogram

### Steps To Reproduce

visit team with no instances
click info link in the header

### Environment

- FlowFuse version: 2.8 (live/prod)
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
@Yndira-E could you confirm which of the 2 are the correct pictogram please?

**Comment by Yndira-E** [comment]
The one on the background is an empty state pictogram, it's the right one but it doesn't have the right colours to be on that modal.
We should use [this one](https://drive.google.com/open?id=13JZapYHZthSEEwZSc92OjbpGMldARGpf&usp=drive_fs).
