### ISSUE TITLE
Navigating directly to immersive view, assets are empty

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#4459]
### Current Behavior

![opera_uHevsONRsU](https://github.com/user-attachments/assets/a30cbb9b-2f59-4732-8caa-31c60e36a12a)

### Expected Behavior

when a URL of `httpx://instance/xxxxx/editor/assets` is navigated, the assets should be shown

### Steps To Reproduce

paste a link to /editor/assets into browser

### Environment

- FlowFuse version: 2.8 (prod)
- Node.js version:
- npm version:
- Platform/OS: win
- Browser: chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by abdulrehman-code** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler
