### ISSUE TITLE
This question is about the remote（flowfuse instance） and local （device agent）run two identical instances，How we manage

### ISSUE THREAD

**Issue by dingling1990** [FlowFuse/flowfuse#4480]
### Description

I created an instance and used the device agent at the same time. When I send the snapshot to my device agent, the remote（flowfuse instance） and local （device agent） run the same flow at the same time, so there are duplicate operations. I think it's the same flow if remote and local. Should it be interlocked, or is there any other solution to suspend the remote instance from running?

Looking forward to your reply

**Comment by knolleary** [comment]
Hi @dingling1990 

When you have a Device assigned to an Instance, then yes, it will be running the deployed flows. You can suspend the Instance, but we don't have a way to suspend the device.

If you are running with an Enterprise license, an alternative is to use the Device Editor feature - where you can remotely edit the flows on the device directly.

**Comment by dingling1990** [comment]
Hi@knolleary    The Device Editor feature just used by  FlowFuse Cloud ？

**Comment by hardillb** [comment]
As Nick mentioned it is an enterprise licensed feature, as such available on FlowFuse Cloud or to users who have purchased a licence.

It is not available in the Open Source version.
