### ISSUE TITLE
http in node - related question.

### ISSUE THREAD

**Issue by VINISHVV** [FlowFuse/flowfuse#4482]
### Current Behavior

Dear All,

I am a big fan of node-red projects from last one year. Recently i installed a flowfuse self hosted version for upgrade existing node-red flows.

I have created a new instance in flowfuse which is accessible from both editor  menu and directly accessible through the domain name shown in flowfuse.

I have added an http in node in the new instance flow which support post methods. But i m unable to send any data to this node as its showing error.

can you help with this issue.

### Expected Behavior

The flow needs to starts basis the input received in the http in node.

### Steps To Reproduce

Create a new instance. and deploy required flows.
Map the domain A record for access the new instance
add an http in node in the newly created instance.
initiate a post method APi call to the end point created.

### Environment

- FlowFuse version: - v2.8.0 node-red ver -3.02
- Node.js version: - 16.20.2
- npm version: - LATEST
- Platform/OS: -UBUNTU
- Browser: - CHROME

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
Hello,

Can you share some more details about this please, specifically the errors that are shown, and also fill out the environment section of the template so we know what version of FlowFuse and how you installed it.

**Comment by VINISHVV** [comment]
@hardillb - modified the details

**Comment by VINISHVV** [comment]
@hardillb i am running my flowfuse in AWS (   https://aws.amazon.com/marketplace/search?prevFilters=%257B%2522ref_%2522%3A%2522mp_nav_category_96c2cd16-fe69-4b18-99cc-e016c61e820c%2522%2C%2522category%2522%3A%252296c2cd16-fe69-4b18-99cc-e016c61e820c%2522%257D&searchTerms=flowfuse )


Error i am gtting in postman

![image](https://github.com/user-attachments/assets/9d8a3ad2-9d04-40c5-a55a-5f8e468e2f16)

**Comment by hardillb** [comment]
OK, that is returning the flowfuse home page. Which implies that the request is being sent to the hostname for the FlowFuse application, not the Node-RED instance.

To help we really are going to need to know the hostnames you are using here and how you've setup the DNS.

Assuming the following:
- The FlowFuse application is running on `forge.example.com`
- The instance is running on `instance1.example.com`

Then you should be pointing postman at `https://instance1.example.com/path` where `path` is the value entered into the http-in node config dialog.

If that is what you are using, then I will need to see the logs from the nginx container in the AWS machine.

**Comment by hardillb** [comment]
But the fact you said you can access the Node-RED editor on it's dedicated hostname that implies that nginx should be working correctly

**Comment by VINISHVV** [comment]
> OK, that is returning the flowfuse home page. Which implies that the request is being sent to the hostname for the FlowFuse application, not the Node-RED instance.
> 
> To help we really are going to need to know the hostnames you are using here and how you've setup the DNS.
> 
> Assuming the following:
> 
> * The FlowFuse application is running on `forge.example.com`
> * The instance is running on `instance1.example.com`
> 
> Then you should be pointing postman at `https://instance1.example.com/path` where `/path` is the value entered into the http-in node config dialog.
> 
> If that is what you are using, then I will need to see the logs from the nginx container in the AWS machine.

Your understanding is absolutely correct!

**Comment by VINISHVV** [comment]
> But the fact you said you can access the Node-RED editor on it's dedicated hostname that implies that nginx should be working correctly

i can access the editor using the domain name ( example https://instance1.example.com )

**Comment by hardillb** [comment]
Then as I said I'll need access to the following:

- The FlowFuse config file from `/opt/flowforge/etc/flowforge.yml`
- The nginx logs showing the request (output of `docker logs flowforge-nginx-1`)

You can get both of these by using SSH to connect to the AWS EC2 machine, the same as when you ran through the setup wizard when you installed from the marketplace.

**Comment by VINISHVV** [comment]
@hardillb 

Nginx log showing below output.

nginx.1     | instance.xxxxx.org 223.31.157.134 - - [14/Sep/2024:04:28:45 +0000] "POST /GooglePay4 HTTP/1.1" 302 0 "-" "PostmanRuntime/7.29.0" "172.18.0.8:1880"
nginx.1     | forge.xxxxx.org 223.31.157.134 - - [14/Sep/2024:04:28:45 +0000] "GET /account/authorize?response_type=code&redirect_uri=https%3A%2F%2Finstance.xxxxx.org%2F_ffAuth%2Fcallback&scope=httpAuth-2.8.0&code_challenge=VzhULZDkTABSFinyPRc9BYUqfa0gleGjs1Oy8D03Htg&code_challenge_method=S256&state=MYFpBSp7xSbK5YRTmx9F8sXy&client_id=ffp_jozYag-8R72G-AG5f07U2oAcvb9RE8n8yw0h6Z_4OCA HTTP/1.1" 302 0 "https://instance.xxxxx.org/GooglePay4" "PostmanRuntime/7.29.0" "172.18.0.2:3000"
nginx.1     | forge.xxxxx.org 223.31.157.134 - - [14/Sep/2024:04:28:45 +0000] "GET /account/request/Uo-Vc4dleGmiLg8jUg3ML0GxgYEok5goolp1qsEmTnE/editor HTTP/1.1" 200 954 "https://forge.xxxxx.org/account/authorize?response_type=code&redirect_uri=https%3A%2F%2Finstance.xxxxx.org%2F_ffAuth%2Fcallback&scope=httpAuth-2.8.0&code_challenge=VzhULZDkTABSFinyPRc9BYUqfa0gleGjs1Oy8D03Htg&code_challenge_method=S256&state=MYFpBSp7xSbK5YRTmx9F8sXy&client_id=ffp_jozYag-8R72G-AG5f07U2oAcvb9RE8n8yw0h6Z_4OCA" "PostmanRuntime/7.29.0" "172.18.0.2:3000"

**Flowfuse config**
port: 3000
host: 0.0.0.0
domain: xxxxxx.org
base_url: https://forge.xxxxxx.org
api_url: http://forge:3000

#################################################
# Database Configuration                        #
#################################################

db:
  logging: false
  ## The database type: sqlite|postgres
  type: postgres
  ### SQLite options

  ## The database filename. Relative to $FLOWFORGE_HOME/var/
  ## Set to ':memory:' for a database that is wiped on restart
  # storage: forge.db

  ### Postgres options

  host: postgres
  user: forge
  password: secret

#################################################
# Project Driver Configuration                  #
#################################################

driver:
  ## The type of backend driver to use
  ##  Can be: localfs/docker/stub/k8s
  type: docker

  options:
    ## Options to be passed to the driver

    ### LocalFS options

    ## The first port number to assign to projects
    # start_port: 7880

    ## Path to find node executable if not on the default path
    # node_path: /usr/bin/node

    ### Docker options

    ## Docker socket path
    socket: /tmp/docker.sock
    # registry: hub.flowforge.com

    ### K8S options

    ## Kubectl conf file to contact the cluster
    # config_file: /opt/share/projects/flowforge/test/config
    # regsitry: hub.flowforge.com

broker:
  url: mqtt://flowforge-broker:1883
  public_url: wss://mqtt.xxxxxx.org

fileStore:
  url: http://file-server:3001

create_admin: true

**Comment by hardillb** [comment]
Ahhh, 

How have you configured security for the HTTP end points for that instance in the FlowFuse Application?

![image](https://github.com/user-attachments/assets/bdea329b-8e23-4de6-b598-cfb4afac8d50)


Have you enabled FlowFuse User Authentication?

If so you will need to included a user security token in the header when making the request.

You can generate a user token under the security settings for your user

**Comment by VINISHVV** [comment]
@hardillb  - Thank you. The issue is related to my limited knowledge; I have not added the token in my API request.
