### ISSUE TITLE
Default credentials of an agent device

### ISSUE THREAD

**Issue by Mfinadmin** [FlowFuse/flowfuse#4483]
### Description

Hi
I just added a device in flowfuse and it's running properly. Can you help me with the default login credentials to login that particular nodered device.

I can access the home page using the editor url. But not sure how to set user credentials

**Comment by hardillb** [comment]
There are none

To access the editor of a node-red instance running under the device agent you need to enable developer mode and use the tunnel from the FlowFuse application.

https://flowfuse.com/docs/device-agent/deploy/

For self hosted FlowFuse this is an enterprise licensed feature

**Comment by Mfinadmin** [comment]
Thank you.. will upgrade license or move to cloud solutions
