### ISSUE TITLE
Restart Node-RED option for Device Agent from Forge app

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#4484]
### Description

Sometimes Node-RED can fail in a way that will still respond to http requests but not process messages. In this situation the device agent will leave it running.

The fix would be to restart the Node-RED instance, but for a remote device agent there may be no way to log into the machine ot restart the whole device agent. So instead allow the device agent to be allowed to restart Node-RED on a command from the Forge app.

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by Steve-Mcl** [comment]
Hey Ben, is there an issue with the "restart" operation devices already have...

![image](https://github.com/user-attachments/assets/beca94f1-b465-450f-8918-5a0601e6c2e8)

**Comment by hardillb** [comment]
No, it was 22:00 on Saturday night and I missed it.
