### ISSUE TITLE
Some operations are obscured by HS chat bubble widget

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#4488]
Nick has stated on Slack there is still pages in admin views that have this overlap issue. In particular team types.

See also: https://github.com/FlowFuse/flowfuse/pull/4477#issuecomment-2352563844

The CSS (while working locally) does not seem to affect the widget once deployed. Possibly due to how script injects the widget?

> <img width="236" alt="image" src="https://github.com/user-attachments/assets/a6da82f9-59f2-4290-bbad-7b015e1b70b5">
> 
> 
> And despite the screenshots in the PR description, the iframe is still the large square - here I've used browser tools to draw its outline - nothing inside that square is clickable.

_Originally posted by @Steve-Mcl in https://github.com/FlowFuse/flowfuse/issues/2897#issuecomment-2352673539_

**Comment by Steve-Mcl** [comment]
FWIW, I finally got a reply from the MOD who anounched movable widgets.

> Hi [@SDMcLaughlin](https://community.hubspot.com/t5/user/viewprofilepage/user-id/818048)! The draggable widget feature is currently in beta but we plan to release it to all applicable HubSpot portals within the next month.


REF: https://community.hubspot.com/t5/HubSpot-Ideas/More-Chat-Widget-Styling-Options/idc-p/1040095/highlight/true#M193200

**Comment by Steve-Mcl** [comment]
> Nick has stated on Slack there is still pages in admin views that have this overlap issue.

> TeamTypes
> ![image](https://github.com/user-attachments/assets/62e44509-3d39-478b-93a1-91fce50684de)

**Comment by Steve-Mcl** [comment]
verified on prod

users
![image](https://github.com/user-attachments/assets/628eca0e-5a70-4a52-aac7-ca3305fcb7f7)

team types
![image](https://github.com/user-attachments/assets/d64cd894-6855-4082-85dc-8b1b8240f769)

**Comment by knolleary** [comment]
@Steve-Mcl To clarify - are we fixing this on a case-by-case basis for each and every view? Or are we fixing the highlevel layout to just work for all views?

I ask because https://app.flowfuse.com/admin/flow-blueprints is also affected

**Comment by Steve-Mcl** [comment]
@Steve-Mcl To clarify - are we fixing this on a case-by-case basis for each and every view? Or are we fixing the highlevel layout to just work for all views?

No, not fixing at high level. Not all views use the same container. It was easier and quicker to approach each one as it is found.

Additionally, I have deliberately decorated each fix with the same searchable comment as it is my full intention to remove them all once the widget is draggable (which was the original request)

I have been  _reliably informed_ that within approx 2 weeks time (by a HS team member) that the drag feature will be out of beta - at which time it is my full intention to undo the hacks.

**Comment by Steve-Mcl** [comment]
follow up issue here: https://github.com/FlowFuse/flowfuse/issues/4512
