### ISSUE TITLE
It is possible to change an instance name via the API, but this will break kubernetes objects

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#4499]
### Current Behavior

If working with the API to update a instances settings it is possible to change it's name.

This will break kubernetes installs as the name is used to identify k8s objects.

### Expected Behavior

Instance names are fixed at creation

### Steps To Reproduce

```
curl --request PUT \
  --url https://forge.ff.example.com/api/v1/projects/0d450195-b200-497b-85fb-e0d1279a6168 \
  --header 'Authorization: Bearer ffpat_REDACTED' \
  --header 'Content-Type: application/json' \
  --data '{
  "name": "low-code-demo-app",
	"hostname": "low-code-demo-app.stage.ff.example.com"
}'
```

### Environment

- FlowFuse version: 2.8.0
- Node.js version: 20.x
- npm version: 9.x
- Platform/OS: all
- Browser: all

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
This should work if the instance is suspended, but not running.

Look at adding blocks in the API endpoint for this.

**Comment by hardillb** [comment]
OK, I think I've got this sorted, but there is an extra bit in the project put method I think needs removing.

@knolleary can you have a quick look at

https://github.com/FlowFuse/flowfuse/blob/3171bfbbca060f35312d8611fff94c45e9da7f90/forge/routes/api/project.js#L386-L403

I'm not sure where we use the KEY_HOSTNAME value later as both docker and k8s driver both generate `project.url` value and then use this when setting up HTTP ingress (and the custom hostname is in it's own key'd value `KEY_CUSTOM_HOSTNAME `)

**Comment by knolleary** [comment]
@hardillb I can't see anywhere we use the hostname setting.

The runtime code supports getting/setting the value under the `hostname` property on the Instance object. But as far as I can see, the UI doesn't do anything with it.

I *think* this is old redundant code.
