### ISSUE TITLE
Reverse trial new user education

### ISSUE THREAD

**Issue by gstout52** [FlowFuse/flowfuse#4500]
**Story**:

As a new Team free trial user, I want to learn about features exclusive to the Team plan, so that I can make the best use of my free trial.

**Goal**:

As of September 13, 2024, free trials are now on the Team tier. At the end of the trial period, users can pay to stay on Team, drop down to Starter, contact Sales to move to Enterprise, or churn. We want new Team users to begin to use Team features as soon as possible, to increase the probability that the user builds something of value during the free trial period.

**Experiment**:

After the product tour closes - so, whether or not the user actually completed the tour - a box appears in the lower right-hand corner and asks users what they want to do first. This can be a small modal that floats above the contact support widget. 

Here is a copy recommendation, in brackets:

[Welcome to your free trial of FlowFuse! Where would you like to get started?

Create a DevOps Pipeline
Set up Project Nodes
Build a Dashboard
Create a Node-RED flow]

For this iteration, each of the recommended actions contains a url to an existing piece of documentation. In a subsequent iteration, we can consider a more hands-on, in-product experience.

**Sources**:
- Create a DevOps Pipeline: link to https://flowfuse.com/docs/user/devops-pipelines/ 
- Set up Project Nodes https://flowfuse.com/docs/user/projectnodes/#flowfuse-project-nodes
- Build a Dashboard: https://flowfuse.com/blog/2024/04/how-to-build-an-application-with-node-red-dashboard-2/
- Create a Node-RED Flow: https://www.youtube.com/watch?v=47EvfmJji-k 

**Analytics Needs**:

Create new events in PostHog. The event can be something like 'clicked trial popup link' and each of the documentation items can be a property of the event. This will enable us to track both any clicks of the popup, and which particular item was clicked. 

This will enable us to evaluate the effectiveness of early in-product education at activation, retention, and conversion.

**Comment by gstout52** [comment]
@joepavitt Open to feedback on which sources to link to. Two of the sources stand out. 
- If there is nothing more substantial about how to use Project Nodes, let's stick with what I found. Otherwise, let's swap out the resource.
- The webinar where Rob walks through a first flow is great, but it's also long and uses "FlowForge" for our company name.

**Comment by cstns** [comment]
Should we prompt the education modal during the each session start whilst the user has the team trial active or should it be just a one-off thing after the product tour ends?

Thinking out loud here, we could add a _close_ button which disables the modal until the next session starts and a _hide permanently_ button that will disable the modal for all future sessions during the trial.

This would imply a bit of scope creep in storing the user's preference somewhere in the database and exposing it to the frontend but would make the entire feature more robust.

**Comment by joepavitt** [comment]
I think the scope here is just at the end of the Product Tour

**Comment by gstout52** [comment]
We know that users impulsively close modals when they first create an account for anything. So, if it's not much extra work, a helpful addition in the spirit of @cstns idea is this:

When the education modal displays, the user can close it at any time. If they close it, a second message displays that says, "You can access these resources at any time by clicking the drop-down arrow in the upper-right corner."

Then, in that dropdown menu, create a button that says something like, "Getting Started." If the user clicks that button, the modal reappears.

**Comment by cstns** [comment]
Link clicks will be captured under the `clicked-trial-education-link` event and the properties will be `{title: 'link title', href: 'link href'}`

Not sure if i have to update anything on postog's side

**Comment by joepavitt** [comment]
> **Not sure if i have to update anything on postog's side**

No need, it _just works_

**Comment by cstns** [comment]
awesome!

Also added a `clicked-open-education-modal` posthog event that's triggered when trial users open the education modal. Thought it might come in handy

**Comment by cstns** [comment]
Had a discussion with @joepavitt, and we decided that in order to avoid overlap with the support chat we'll move the modal to the top right section of the page.

**Comment by gstout52** [comment]
> awesome!
> 
> Also added a `clicked-open-education-modal` posthog event that's triggered when trial users open the education modal. Thought it might come in handy

Will this event fire when the modal opens the first time, automatically, or only when the user opens it manually through the menu?

**Comment by cstns** [comment]
> @cstns Will this event fire when the modal opens the first time, automatically, or only when the user opens it manually through the menu?

Only when clicked manually from the dropdown menu. I figured it wouldn't be useful on the initial load but I can add it easily if needed

**Comment by gstout52** [comment]
@cstns That sounds good, just wanted to clarify!

**Comment by gstout52** [comment]
@cstns Do you have an estimate for when this will be live?

**Comment by joepavitt** [comment]
@gstout52 in about 10 mins. My fault, I reviewed, was waiting on tests to pass, and forgot to loop-back.
