### ISSUE TITLE
Chat window on FlowFuse Cloud is obscured

### ISSUE THREAD

**Issue by robmarcer** [FlowFuse/flowfuse#4502]
### Current Behavior

![Screenshot on 2024-09-17 at 17-26-26](https://github.com/user-attachments/assets/a2a19b72-1eb4-427a-ad31-65d0c0b6f8ed)

The chat window is mostly obscured

### Expected Behavior

I should be able to see it.

### Steps To Reproduce

Login to FF Cloud, try to open the chat window.

### Environment

- FlowFuse version: Current (FF Cloud)
- Node.js version:
- npm version:
- Platform/OS: Mac / Windows current
- Browser: Chrome current

### Have you provided an initial effort estimate for this issue?

I can not provide an initial effort estimate

**Comment by robmarcer** [comment]
@Steve-Mcl, @hardillb said you might want to take a look at this. :-)

**Comment by Steve-Mcl** [comment]
@robmarcer thanks, will do.

**Comment by Steve-Mcl** [comment]
fixed on prod:

![image](https://github.com/user-attachments/assets/ce2e1dcb-2382-48ca-a7a7-0ac84cf390b6)
