### ISSUE TITLE
Emailing template contains what seems to be a css class

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#4593]
### Current Behavior

![image](https://github.com/user-attachments/assets/3649d73f-35ee-44b5-8bce-6da88e2f8507)
The emailing template starts with what seems to be a css class

### Expected Behavior

The heading should be the starting point

### Steps To Reproduce

Trigger a team invitation email

### Environment

- FlowFuse version: 2.9.0
- Node.js version: n/a
- npm version: n/a
- Platform/OS: n/a
- Browser: n/a

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
It is the `alt` text of the header image

**Comment by cstns** [comment]
Unfortunately, I can't replicate the behavior using a local email server

Removing the alt text from the header image could fix the problem but I'm unable to confirm it.

**Comment by cstns** [comment]
Never mind, I can check on staging
