### ISSUE TITLE
Occasional pipeline test failure on postgres

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#4652]
We have had a couple test run failures on postgres with the following test. It is a timing issue as it has only happened a couple times (to my knowledge).

I suspect there's an async action updating the `isDeploying` flag in parallel to the query of the state - leading to non-deterministic result.

```
1) Pipelines API
       Deploy Pipeline Stage
         With action=use_latest_snapshot
           For instance=>device group
             Copies the existing instance snapshot to the next stages device group:
     AssertionError: expected Object {
  id: 'B9kj4VeLZP',
  name: 'device-group-b',
  description: 'an unnamed device group',
  deviceCount: 1,
  targetMatchCount: 0,
  activeMatchCount: 0,
  developerModeCount: 0,
  runningCount: 0,
  isDeploying: false,
  hasTargetSnapshot: false
} to have property isDeploying of true (got false)
      at Assertion.fail (node_modules/should/cjs/should.js:275:17)
      at Assertion.value [as property] (node_modules/should/cjs/should.js:356:19)
      at Context.<anonymous> (test/unit/forge/ee/routes/api/pipeline_spec.js:2490:49)
      at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

**Comment by hardillb** [comment]
OK, I'm really struggling to see how this test works.

The `isDeploying` field tracks how many devices have applied their targetsnapshot, but I can't see any code that is simulating a device downloading a new snapshot.

**Comment by hardillb** [comment]
@Steve-Mcl Might need to talk this through with you on Thursday

**Comment by Steve-Mcl** [comment]
This likely related to (and fixed in) an open PR waiting review: https://github.com/FlowFuse/flowfuse/pull/4686#issue-2609741322

**Comment by hardillb** [comment]
I'm going to move this to review needed as the referenced PR is merged, we can move it back if we see the failure again.

**Comment by hardillb** [comment]
I've not seen or heard of a failure in a while, I'm going to say this is closed
