### ISSUE TITLE
MQTT Broker Empty state icon and pictogram

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#4680]
### Related Issue

https://github.com/FlowFuse/flowfuse/pull/4646

### Description

**Considerations:**
- Where will the image be displayed/shared, product? blog post? social media? presentation? website?
- empty state icon will be displayed within the flowfuse application when the broker feature is disabled
- the pictogram will be displayed on the help panel on the broker page

**Inspirations:**
- instance-timeline [here](https://drive.google.com/open?id=1HH9s7oj1NGkcrzsv6P1A-6mq94FugLvT&usp=drive_fs)
- timeline_red [here](https://drive.google.com/open?id=1HJ4T4h7RQU4XEiO8mUP0Ceq1Mor46drX&usp=drive_fs)

**Comment by Yndira-E** [comment]
Hi @cstns how about these?

[Pictogram](https://drive.google.com/open?id=1LLVscF8nz8iXeKs5ro1i412l2OyAzkVH&usp=drive_fs)
[Empty state](https://drive.google.com/open?id=1LOVuJz21eiPPxiF27WnUlSH83smU6b3Y&usp=drive_fs)
