### ISSUE TITLE
Follow up after MQTT Broker UI

### ISSUE THREAD

**Issue by cstns** [FlowFuse/flowfuse#4685]
### Description

After a hastily development of the mqtt broker page, dx and scalability is lacking alongside other things that need addressing. 

Todo
- Extract standalone logic into distinct components
- improve css styling/rules
- check if a new icon for the mqtt broker is needed for the broker's empty state but not due to lack of license/team-feature
- address snapshot lint selector warnings
  - test/e2e/frontend/cypress/tests/instances/version-history/snapshots.spec.js:56
  - test/e2e/frontend/cypress/tests/instances/version-history/snapshots.spec.js:59
  - test/e2e/frontend/cypress/tests/instances/version-history/snapshots.spec.js:445
  - test/e2e/frontend/cypress/tests/instances/version-history/snapshots.spec.js:731
- add more and improve existing ee e2e tests

### Epic/Story

https://github.com/FlowFuse/flowfuse/issues/1350

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
Add copy button next to username/clientid in list of clients to make easier to use
