### ISSUE TITLE
Allow FF Dashboards to be embedded in iframes

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#4689]
### Description

Our current security headers are preventing FF Dashboards from being embedded in iframes in 3rd party sites.

We need to expose an option to allow embedding of the dashboard - and set the security headers appropriately, whilst not breaking the immersive editor that has its own requirements for these headers.

 - https://app-eu1.hubspot.com/help-desk/26586079/view/233410279/ticket/17075304691/thread/8319676606#email

### Which customers would this be available to

Everyone - CE/Starter/Team/Enterprise

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
Second customer asking for this:

https://app-eu1.hubspot.com/help-desk/26586079/view/233410279/ticket/40326383853/thread/9054388418#live-chat

**Comment by hardillb** [comment]
Looking at this I think we need an extra `httpNodeMiddleware` that can set  the header `Content-Security-Policy: frame-ancestors` to a provided value.

This should be possible since `httpNodeMiddleware` can be an array, so we should be able to add more than just the `flowforgeAuthMiddleware` that is currently injected

**Comment by hardillb** [comment]
I tried hard coding the following:

```
httpNodeMiddleware: [flowforgeAuthMiddleware, function(req,res,next) {
        res.set("Content-Security-Policy", "frame-ancestors 'self' '*'");
        next()
    }],
```

And this was overridden by the `httpAdminMiddleware`

**Comment by hardillb** [comment]
OK, so the dashboard v2 doesn't appear to use the `httpAdminMiddleware`

**Comment by hardillb** [comment]
Progress, it can be added to `ui: { path: '/ui', middleware: [flowforgeAuthMiddleware, ... ]}`

**Comment by hardillb** [comment]
OK, now I have the right place to inject this into the settings.js. UX design questions.

How do we expose this to the user?

As a field in the Instance settings to insert a ancestor URL (or `'*'`)?

Any field will need to be nr-lancher version checked to flag it will only work with newer launcher versions.

**Comment by hardillb** [comment]
Too early nr-launcher version
![Image](https://github.com/user-attachments/assets/3df54322-878c-4992-8ce0-5ccb24c10d15)

right nr-launcher version
![Image](https://github.com/user-attachments/assets/0ab656a9-8b4e-44b2-ac94-caca30c8700c)

Gone with on/off not a list of allowed URLs to start with.

**Comment by cstns** [comment]
The too early nr-launcher version message should be highlighted somehow. I feel that for an mvp iteration the ui is more than enough and looks good!

**Comment by hardillb** [comment]
Verified on Prod
