### ISSUE TITLE
Direct users to documentation to set up MQTT clients

### ISSUE THREAD

**Issue by gstout52** [FlowFuse/flowfuse#4707]
### Description

Users setting up a MQTT client for the first time need documentation on how to do this. Here is the documentation url: https://flowfuse.com/docs/cloud/introduction/#enterprise-team-broker

1) Add a link to our documentation in the modal that appears when a user clicks the 'information' button on the broker page
![image](https://github.com/user-attachments/assets/1512f226-5c4d-47e5-9301-1430ac9073a7)

2) When a user clicks 'Create Client', a modal appears. Add a link to our documentation in that modal. Suggestion: under the Access Control Rules, add the text 'See our documentation for setting up a MQTT client' and make 'See our documentation' link to the documentation page. 
![image](https://github.com/user-attachments/assets/0eae1135-992d-4eb4-bbd8-58ce511237fb)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
Need to work out exactly what docs to point to here, given this will show up on both FFC and Self Hosted

**Comment by hardillb** [comment]
https://github.com/FlowFuse/flowfuse/pull/4775 covers the adding the docs and the first point but doesn't add the second part.
