### ISSUE TITLE
Add global "Search" into FlowFuse navigation header

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4729]
### Description

As part of the work being done to improve the overall navigation of FlowFuse, I am working on a new Applications page. Currently, we treat this a little like a "home" page, but it's causing it to be too busy. 

One of the most useful features here is the "Search", which allows users to find any applications/devices/instances. I want to make the "Applications" page more consistent with others, and reduce the noise, so this would include removing the _global_ search from the Applications page.

Given the value of the feature though, there is merit in moving this to the navigation bar, and consequently making it available to _every_ page in FlowFuse.

### Quick Mockup:

<img width="874" alt="Screenshot 2024-11-04 at 13 36 25" src="https://github.com/user-attachments/assets/c592f6fc-6a60-4947-9b02-54e24e447507">

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

```[tasklist]
### Tasks
- [ ] Add search bar UI frontend
- [ ] https://github.com/FlowFuse/flowfuse/issues/4756
```

**Comment by joepavitt** [comment]
View of an actual search taking place:

<img width="734" alt="Screenshot 2024-11-04 at 14 51 11" src="https://github.com/user-attachments/assets/d564c034-5987-490d-a3ec-887808eff840">

**Comment by cstns** [comment]
> View of an actual search taking place (ignore the "Applications" view in the b/g)
> <img alt="Screenshot 2024-11-04 at 14 51 11" width="734" src="https://private-user-images.githubusercontent.com/99246719/382800605-d564c034-5987-490d-a3ec-887808eff840.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA4MDY0NzYsIm5iZiI6MTczMDgwNjE3NiwicGF0aCI6Ii85OTI0NjcxOS8zODI4MDA2MDUtZDU2NGMwMzQtNTk4Ny00OTBkLWEzZWMtODg3ODA4ZWZmODQwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA1VDExMjkzNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxNDZlYzRiZTY4MWFiOWYzM2E0Nzk4ZGFjOGRhMTQ4ZDdkYjFmMTYzOWQ2NGIwY2I4Y2I2NDBhZjFmNmQ5NTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.D2ZgQdY6Ex_vvVRzM0ySaZXLQXXOJFs4PwZ1_wvvxOw">

Will this be an algolia integration?

**Comment by joepavitt** [comment]
> Will this be an algolia integration?

No need, we will provide our own Search API for devices/instances

**Comment by cstns** [comment]
@knolleary, Is it ok with you to use the existing applications api (which we currently use for the applications search) `forge/routes/api/team.js:263` for this search as well or should I wait/implement a new endpoint for it?

One drawback is that the instances/devices results are nested under applications, another is that it's scoped to the current team (which is another question that needs asking).

@joepavitt, is the global search truly a global search or should it be scoped to the current team?

**Comment by joepavitt** [comment]
> should it be scoped to the current team?

Current Team

**Comment by knolleary** [comment]
> Is it ok with you to use the existing applications api (which we currently use for the applications search) forge/routes/api/team.js:263 for this search as well or should I wait/implement a new endpoint for it?

@cstns Using the existing API means you end up doing the search in the browser - which has to load all the data using that API first.

It would be cleaner to have a search API that lets us do the work on the server side, only if needed. Happy to discuss specifics on Monday.
