### ISSUE TITLE
UX debt: "Error: Api Error" on version mismatch

### ISSUE THREAD

**Issue by ZJvandeWeg** [FlowFuse/flowfuse#4738]
### Description

> That means they had out of date flows in their editor when they clicked deploy; so the editor will have told there there are server-side changes to merge in first

Internal discussion: https://flowforgeworkspace.slack.com/archives/C032Q63FGG1/p1730727477141449

I don't think this error is helpful or end users as an error, and recovery should be explained or linked to in the docs.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by ZJvandeWeg** [comment]
cc @joepavitt -- Please schedule

**Comment by knolleary** [comment]
I'll pick this up as its a Node-RED audit log entry - agreed it isn't a useful message for the end user to audit log. But I want to understand the scenario its being hit. My understanding is it is generated when a user clicks Deploy, but they don't have the latest flows in the editor; the runtime returns this error to tell the editor there is a version mismatch between what the editor thinks its overwriting and what is actually there. This allows the editor to prompt the user to merge remote changes.

However, from the slack discussion, it wasn't clear if that was the case here - and that snapshot deployments were somehow involved.

I will:

1. see if I can recreate given the information available - to ensure nothing unexpected is happening
2. add a filter for this event so it doesn't get audit-logged.
