### ISSUE TITLE
Build UI for displaying Broker Topic Hierarchy

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4752]
### Phase 1:

![image](https://github.com/user-attachments/assets/5921467f-6c6e-4018-b628-34c2b25cabe7)

API available in https://github.com/FlowFuse/flowfuse/pull/4748

**Comment by cstns** [comment]
@joepavitt, I'd also like some help with the helptext content

**Comment by cstns** [comment]
> @Yndira-E can you give me a hand with the empty state and helptext pictograms?
I'll re-use the existing broker pictograms fro the time being and replace them later on if someone says so

> @joepavitt, I'd also like some help with the helptext content
I've generated some placehoder text using an llm, it can be adjusted as we go
