### ISSUE TITLE
Accessing an instance directly results in blank screen

### ISSUE THREAD

**Issue by Steve-Mcl** [FlowFuse/flowfuse#4758]
### Current Behavior

![image](https://github.com/user-attachments/assets/2422772d-83b9-4ea9-8d9f-993021c89d0f)

### Expected Behavior

Opening a Link to an instance overview should render correctly

### Steps To Reproduce

Navigate to an instance
Click the title bar link to navigate to FF

### Environment

- FlowFuse version: Live FFC 2.10
- Node.js version:
- npm version:
- Platform/OS: Win / Mac
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by cstns** [comment]
Introduced by https://github.com/FlowFuse/flowfuse/issues/4673. Caused by the fact that the featuresCheck getter getting accesses before the features state getting hydrated
