### ISSUE TITLE
Ability to map exisitng LDAP SSO groups to teams

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#4768]
### Description

Customer has hard rules on LDAP group names, not allowed to match `ff-[team-slug]-[role]`  group names.

Would like a way to explicitly set group name for a given team

### Which customers would this be available to

Enterprise Tier Only (EE)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

 - https://app-eu1.hubspot.com/contacts/26586079/record/0-2/8845845707

**Comment by hardillb** [comment]
I think the prefix/postfix option is actually a most practical solution.

It means we don't need to keep a table of group to team/role mappings

**Comment by knolleary** [comment]
Feels like a sensible quick solution that is most flexible. An alternative would be to require the actual pre/post strings to be provided - not as flexible, although perhaps more deterministic. Stick with lengths for now.

**Comment by hardillb** [comment]
OK, got the changes done, will add some extra groups to my SSO test rig after lunch

**Comment by hardillb** [comment]
Just thinking that using the length does mean it's possible to match other groups...

e.g. prefix 5 matches both 

- `test_ff-dev-owner`
- `fooo_ff-tev-owner`

I don't think this is a problem as only LDAP/SAML admins should be able to create groups?
