### ISSUE TITLE
Allow Team Members to toggle Device Developer Mode

### ISSUE THREAD

**Issue by hardillb** [FlowFuse/flowfuse#4778]
### Description

Currently Team Members can only access the Device Editor if a Team Owner has already enabled Developer Mode.

Customer would like to allow Team Member to toggle Developer Mode.

This is may need to be a instance level setting as current users may depend on this role separation. 

### Which customers would this be available to

Team + Enterprise Tiers (EE)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by joepavitt** [comment]
@hardillb what customer is this for?

**Comment by hardillb** [comment]
https://app-eu1.hubspot.com/contacts/26586079/record/0-2/8845845707

@joepavitt

**Comment by hardillb** [comment]
This would be a large change to the current permissions, I feel this should be configurable by the FlowFuse Admin. Will look to see if the current permission model can allow this

**Comment by hardillb** [comment]
Something like: 

```
    app.put('/:deviceId/mode', {
        preHandler: async () => {
            if (app.settings.memberEnableDevice === true) {
                return app.needsPermission('device:editor')
            } else {
                return app.needsPermission('device:edit')
            }
        },
        schema: {
            summary: 'Set device mode',
```

**Comment by hardillb** [comment]
- Does this want to be a `flowfuse.yml` config option or in the admin settings?
- If this is in admin settings should it be configurable on a TeamType or per team level (to allow for use on FlowFuse Cloud)?

**Comment by hardillb** [comment]
The UI will also need to know if this is enabled as it disables the toggle for anybody other than `Owner`

**Comment by knolleary** [comment]
Only just seeing your comments from a couple hours ago. We should resist making this a config option if we feel its a better sensible default behaviour.

I believe that putting a device in/out of developer mode is a common developer task and entirely reasonable to be done by a Member role user - as they are doing the engineering work typically.

I think we relax the permission - and only if a user highlights a concern should we consider making it customisable.

**Comment by hardillb** [comment]
Bah, just as I'd got variable permissions working :stuck_out_tongue_winking_eye:

I'll back out the other bits

**Comment by hardillb** [comment]
This is merged so moving to done
