### ISSUE TITLE
Sidebar sometimes fails to update when switching to admin/user views

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#4797]
### Current Behavior

*Sometimes* when navigating to the admin or user views via the dropdown menu, the sidebar does not update and still shows the menu items for the Team I was in. The only way to resync is to reload the page

### Expected Behavior

Sidebar to update

### Steps To Reproduce

It does not happen everytime. I haven't hit it enough times to spot a pattern - but I have hit it enough times to know I'm not imagining it.

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by cstns** [comment]
Tried for the last half hour to reproduce it and couldn't. I may have encountered it but not 100% sure if it was that or just me messing with the app for too long. 

I'll put a pin in it for the time being and keep an eye out to see if I'm able to to trigger it and find a reproducible pattern

**Comment by cstns** [comment]
Opening again because it reproduced it on staging
