### ISSUE TITLE
Topic Hierarchy: add 'copy topic' to copy full topic string to clipboard

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#4801]
The Topic Hierarchy lets me see the topics being used in a tree-like fashion. But to make use of the information I still have to manually type out the topic.

I would like a one-click copy button that gives me the full topic string copied to my clipboard.

**Comment by Steve-Mcl** [comment]
Any preference on copy button?

I've done this literally as (screenshot below), but its not the best UX on wide screens IMHO. 
Perhaps copy on item-click or context menu on item-click would be better? 

_Looks nice on smaller screen_
![Image](https://github.com/user-attachments/assets/cdedf771-134c-4bf2-a5a7-501b4b9c8416)


_Lots of mouse miles on larger screen_
![Image](https://github.com/user-attachments/assets/71827927-9ab6-478a-be0b-60f0d823e916)
