### ISSUE TITLE
Team View: Bill of Materials

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4823]
Provide a `/<team>/dependencies` view, similar to how we show Instances. Detail should allow filtering by applications or instance, and detail the high-level dependencies found in the Team's ecosystem.

```[tasklist]
### Tasks
- [x] GET /team/bom https://github.com/FlowFuse/flowfuse/pull/4849
- [ ] UI https://github.com/FlowFuse/flowfuse/pull/4872
```

**Comment by joepavitt** [comment]
Quick first iteration
![Team _ Dependencies](https://github.com/user-attachments/assets/6bee4d63-eeb1-414a-9a23-e88bb67fe999)

**Comment by hardillb** [comment]
I'll grab the API here

**Comment by cstns** [comment]
Should i use the same empty state, feature not-available and empty state logos from the application dependencies?

**Comment by joepavitt** [comment]
yes please
