### ISSUE TITLE
Add notification filter for team type and subscription status

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#4830]
### Description

The notification hub currently allows us to target users based on their role on teams. We have an additional requirement to target users with an active subscription, and for teams of a certain type.

ie 'send a notification to all Owners of teams with an active subscription'

This will avoid sending certain notifications to dormant users and expired trial owners.

### Which customers would this be available to

Other (See comments)

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by gstout52** [comment]
@knolleary Just to clarify, will this filter allow Owners with teams still on trial to receive the message? The goal is to be able to send a notification to Owners of teams on Team that are actively paying, so past the trial stage.

**Comment by knolleary** [comment]
@gstout52 I will ensure there are appropriate filters to cover that scenario
