### ISSUE TITLE
Clicking on the Restart button while an NR instance is being created breaks the provisioning/restart flow

### ISSUE THREAD

**Issue by AllanOricil** [FlowFuse/flowfuse#4839]
### Current Behavior

Clicking on the Restart button while an NR instance is being created breaks the provisioning/restart flow

![image](https://github.com/user-attachments/assets/79637a40-5b30-47dc-800a-a7cab77838ec)

The NR instance will be in Stopped state forever. It can no longer be restarted. The only option is to delete and recreate.

### Expected Behavior

Action buttons, with the exception of DELETE, must be disabled while an NR instance is being created or restarted. A User must not be able to click on the restart button if the provisioning/restarting flow is running.

### Steps To Reproduce

1. Create a flow
2. imediatelly click on the "restart" button

![image](https://github.com/user-attachments/assets/cb9f5652-8af1-45aa-ac8a-f658f8da0662)

3. Verify the flow will change its state to "stopped"
4. Verify the flow can no longer be restarted

### Environment

- FlowFuse version: 1.15
- Node.js version: 18
- npm version: 10
- Platform/OS: Linux/Amd64
- Browser: Chrome

### Have you provided an initial effort estimate for this issue?

I am not a FlowFuse team member

**Comment by hardillb** [comment]
@AllanOricil is this really based on FF v1.15? If so can you test this on v2.11 please, there have been a LOT of changes sine 1.15

**Comment by hardillb** [comment]
Also which install type is this? Docker, Kubernetes or localfs?

**Comment by AllanOricil** [comment]
@hardillb there are custom fork changes on top of v1.15 but they are just cosmetics/branding stuff
@hardillb flowfuse-docker-compose

I can try v2 but it will take time.

**Comment by hardillb** [comment]
I can see a possible problem with triggering a restart in the nr-launcher while the Instance is in "INSTALLING" or "LOADING" state.

I propose we only act on restart requests when the instance in in the following states:

- RUNNING
- SAFE
- CRASHED

But we should also lock out the restart button in the UI if not in these states

**Comment by hardillb** [comment]
Verified on staging
