### ISSUE TITLE
Instance related notifications not cleared when instance deleted

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#4845]
### Current Behavior

If an instance crashes or enters safe mode, we send a notification to team owners.

If the instance is deleted, those notifications are not cleared; so the user still sees them and can click on them - which then 404s as the instance has been deleted.

### Expected Behavior

When an instance is deleted, clear any related notifications.

NB: due to the design of notifications, we can't lean on a delete cascade at the DB level; we need a post-delete hook in the Instance model to do the work.

As we will have notifications in this state already, we will need a migration to tidy up the table.

### Steps To Reproduce

- Crash an instance to generate a notification in the notification inbox
- Delete the instance
- Check the notification inbox - the notification should be removed

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by hardillb** [comment]
on destroy hook done,

Just working out how to do the clean up migration

**Comment by hardillb** [comment]
Struggling to come up with a migration query for this to remove orphaned notifications.

The Notification table doesn't store the instance id in a format that is easy to query for.

We can use something like

```
app.db.models.findAll({
  where: {
    reference: { [Op.endsWith]: project.id }
  }
})
```

But this can only search for a given project id, we can't do something like "where reference doesn't ends with in (select id from projects)" which I think we would need.

Best I can think so far is to get all notifications, and then check them against the projects list
