### ISSUE TITLE
Hide Environment Variable

### ISSUE THREAD

**Issue by joepavitt** [FlowFuse/flowfuse#4858]
### Description

Some environment variables may contain passwords, we should offer the option to "hide" the value of these by default, may also pair with https://github.com/FlowFuse/flowfuse/issues/2289

Not sure where we'd be able to store the state of these fields, as there would need to be database persistence on the preference.

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by knolleary** [comment]
Duplicate of https://github.com/FlowFuse/flowfuse/issues/4835
