### ISSUE TITLE
Application view has double banners

### ISSUE THREAD

**Issue by knolleary** [FlowFuse/flowfuse#4938]
### Current Behavior

On an application view, we get double banners:

<img width="1205" alt="image" src="https://github.com/user-attachments/assets/8029e2d5-ddd9-4eea-8c26-a4a9b8c0ceb2" />

### Expected Behavior

One banner

### Steps To Reproduce

Have a team with a banner showing

Ways of triggering the banner:

 - Login as an admin and view a team you aren't a member of
 - View a team in trial mode
 - View a team with an expired subscription
 - 

### Environment

- FlowFuse version:
- Node.js version:
- npm version:
- Platform/OS:
- Browser:

### Have you provided an initial effort estimate for this issue?

I have provided an initial effort estimate

**Comment by cstns** [comment]
fixed by https://github.com/FlowFuse/flowfuse/pull/4939
