### ISSUE TITLE
Move billing setup stage.

### ISSUE THREAD

**Issue by sammachin** [FlowFuse/flowfuse#594]
### Epic

#590

### Description

As a owner 

I want to create projects on the free tier without having to setup billing

So that I can asses the value of the platform

We need to move the points at which the user is prompted to enable billing and walk through the UX of this in light of having a free tier and potentially other project types #380

The desired experience is that a user can create a team on the free team plan and then create projects on the free tier but when they select a paid tier they should then be checked and prompted to setup billing, with the option to drop back and continue on free.

**Comment by knolleary** [comment]
Addressed by #1578
