### ISSUE TITLE
MQTT Launcher Communications

### ISSUE THREAD

**Issue by sammachin** [FlowFuse/flowfuse#755]
### Epic

#464

### Description

**As a:** user

**I want:** My cloud instances to communicate to the forge application over MQTT instead of polling

**So that:** I have a realtime interface and do not rely on polling

**Comment by joepavitt** [comment]
Fairly sure this is now the case given project nodes, and the underlying MQTT broker in place @knolleary?

**Comment by knolleary** [comment]
Not quite. For the command/control of the nr-launcher instances, we still use HTTP comms.

MQTT comms are used to interact with Devices and the comms between Project Nodes.

There hasn't been a compelling need to move the launcher command/control over to MQTT. We can close this off. If a need presents itself, we can raise a new epic to address it.
