### ISSUE TITLE
Stop/Start Flows from Forge App

### ISSUE THREAD

**Issue by sammachin** [FlowFuse/flowfuse#837]
### Epic

#787

### Description

**As a:** user 

**I want to:** be able to stop and start the flows in my Node-RED 3.x projects

**So that:** I can edit flows without the runtime running

Points to consider:
~Is there an existing API that can be called on Node-RED to stop/start flows~ Yes its in the admin API
~Do we need to also expose the stop/start flows option in the deploy menu of Node-RED~ Yes at present its all or nothing
Can the flow status from Node-RED be communicated back to the forge application. 

### Which customers would this be availble to

Specific Project Types (EE)

### Acceptance Criteria

- [ ] User can change the flow state from forge app
- [ ] State is syncronised between forge app and node-red
- [ ] Admin can enable this feature based on stack/project type
- [ ] Node-RED 2.x stacks have the option disabled

**Comment by joepavitt** [comment]
This has been in place for some time - closing
