### ISSUE TITLE
Create read only Public Project URLs

### ISSUE THREAD

**Issue by sammachin** [FlowFuse/flowfuse#855]
### Description

**As a:** project owner

**I want to:** be able to create a public url that allows anyone to access the Node-RED editor in view only mode for my project

**So that:** I can share access to my flows

The Public URLs are a different use case to read only users in #657 This scenario the pubic url gives no access to the forge application, the URL should just hit a flowforge branded landing page and then allow someone to login to the node-red editor.

### Which customers would this be availble to

Specific Team Tiers (EE)

### Acceptance Criteria

- [ ] Button to enable/generate a URL in the project settings.
- [ ] Visting the URL goes to a flowforge branded landing page, (with link to Sign Up to ff) and some custom copy (TBD)
- [ ] User clicks through  to the Node-RED editor in Read Only mode
- ...

**Comment by joepavitt** [comment]
Closing as now covered by https://github.com/FlowFuse/flowfuse/issues/3626
